--------------------------------------------------------
--  DDL for View CORE_CISCO_L71302_GGSN_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71302_GGSN_DAY" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_DROPPED") AS 
  SELECT TRUNC( FECHA, 'DD') as FECHA, GWNAME, SERVID, SERVNAME, SUM(UPLINK_DROPPED) AS UPLINK_DROPPED
FROM CORE_CISCO_L71302_GGSN_HIST
GROUP BY TRUNC( FECHA, 'DD'), GWNAME, SERVID, SERVNAME
;
