--------------------------------------------------------
--  DDL for View CORE_CISCO_L71302_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71302_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_DROPPED") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME, SUM(UPLINK_DROPPED) AS UPLINK_DROPPED
FROM CORE_CISCO_L71302_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
;
