--------------------------------------------------------
--  DDL for View CORE_CISCO_L81804_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81804_GGSN_HOUR" ("FECHA", "GWNAME", "DIAMETER_CC_TERMINATION_SUCC_R") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME,
ROUND (((DECODE (SUM(CCMSGCCRFINAL), 0, 0, SUM(CCMSGCCAFINAL) / SUM(CCMSGCCRFINAL)) )*100),2) as DIAMETER_CC_TERMINATION_SUCC_R
FROM CORE_CISCO_L81804_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), GWNAME
;
