--------------------------------------------------------
--  DDL for View CORE_CISCO_L81513_GGSN_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81513_GGSN_DAY" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_THP_MBPS_GBR") AS 
  SELECT TRUNC( FECHA, 'DD') AS FECHA, GWNAME, SERVID, SERVNAME,
ROUND (AVG(DOWNLINK_THP_MBPS_GBR), 2)  AS DOWNLINK_THP_MBPS_GBR
FROM CORE_CISCO_L81513_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DD'), GWNAME, SERVID, SERVNAME
;
