--------------------------------------------------------
--  DDL for View CORE_CISCO_L81505_GGSN_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81505_GGSN_BH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_THP_MBPS") AS 
  SELECT hist.FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, hist.UPLINK_THP_MBPS
FROM (
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, GWNAME, SERVID, SERVNAME,
      ROUND (AVG(UPLINK_THP_MBPS), 2) AS UPLINK_THP_MBPS
      FROM CORE_CISCO_L81505_GGSN_HIST
      GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
) hist
INNER JOIN L81505_L81513_BH_AUX2 aux
ON hist.FECHA = aux.FECHA
AND hist.GWNAME = aux.GWNAME
AND hist.SERVID = aux.SERVID
AND hist.SERVNAME = aux.SERVNAME
;
