--------------------------------------------------------
--  DDL for View CORE_CISCO_L71303_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71303_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_THROUGHPUT") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(DOWNLINK_THROUGHPUT), 2) AS DOWNLINK_THROUGHPUT
FROM CORE_CISCO_L71303_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
;
