--------------------------------------------------------
--  DDL for View CORE_CISCO_L71301_GGSN_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71301_GGSN_BH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_THROUGHPUT") AS 
  SELECT hist.FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, hist.UPLINK_THROUGHPUT
FROM (
    SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(UPLINK_THROUGHPUT), 2) AS UPLINK_THROUGHPUT
    FROM CORE_CISCO_L71301_GGSN_HIST
    GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
) hist
INNER JOIN L71301_L71303_BH_AUX2 aux
ON hist.FECHA = aux.FECHA
AND hist.GWNAME = aux.GWNAME
AND hist.SERVID = aux.SERVID
AND hist.SERVNAME = aux.SERVNAME
;
