--------------------------------------------------------
--  DDL for View CORE_CISCO_L81201_GGSN_ISABHW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81201_GGSN_ISABHW" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "CURRENT_NUM_SESS") AS 
  SELECT TRUNC(hist.FECHA , 'DAY') AS FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, ROUND(AVG(hist.CURRENT_NUM_SESS),2 ) AS CURRENT_NUM_SESS
FROM(
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(CURRENT_NUM_SESS), 2) AS CURRENT_NUM_SESS
      FROM CORE_CISCO_L81201_GGSN_HIST
      GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
    ) hist
INNER JOIN (
           SELECT FECHA, GWNAME, SERVID, SERVNAME, SEQNUM
            FROM (
                  SELECT FECHA , GWNAME, SERVID, SERVNAME, ROW_NUMBER()
                        OVER (
                          PARTITION BY TRUNC(FECHA , 'DAY'), GWNAME, SERVID, SERVNAME
                          ORDER BY VALOR DESC) SEQNUM
                  FROM L81505_L81513_BH_AUX2
                  )
            WHERE SEQNUM < 4
        ) bh
ON bh.FECHA = hist.FECHA
AND bh.GWNAME = hist.GWNAME
AND bh.SERVID = hist.SERVID
AND bh.SERVNAME = hist.SERVNAME
GROUP BY TRUNC(hist.FECHA , 'DAY'), hist.GWNAME, hist.SERVID, hist.SERVNAME
;
