--------------------------------------------------------
--  DDL for View CORE_CISCO_L81505_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81505_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_THP_MBPS") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME,
ROUND (AVG(UPLINK_THP_MBPS), 2)AS UPLINK_THP_MBPS
FROM CORE_CISCO_L81505_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
;
