--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B04_GGSN_ISABHM
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B04_GGSN_ISABHM" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DPCA_CCA_MESSAGES_REJECTED") AS 
  SELECT TRUNC(hist.FECHA , 'MONTH') AS FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, ROUND(AVG(hist.DPCA_CCA_MESSAGES_REJECTED),2 ) AS DPCA_CCA_MESSAGES_REJECTED
FROM(
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, GWNAME, SERVID, SERVNAME,
      ROUND ((DECODE (SUM(DPCAMSGCCRINIT), 0, 0, SUM(DPCAMSGCCAINITREJ) / SUM(DPCAMSGCCRINIT))),2) as DPCA_CCA_MESSAGES_REJECTED
      FROM CORE_CISCO_L81B04_GGSN_HIST
      GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
    ) hist
INNER JOIN (
           SELECT FECHA, GWNAME, SERVID, SERVNAME, SEQNUM
            FROM (
                  SELECT FECHA , GWNAME, SERVID, SERVNAME, ROW_NUMBER()
                        OVER (
                          PARTITION BY TRUNC(FECHA , 'MONTH'), GWNAME, SERVID, SERVNAME
                          ORDER BY VALOR DESC) SEQNUM
                  FROM L81505_L81513_BH_AUX2
                  )
            WHERE SEQNUM < 4
        ) bh
ON bh.FECHA = hist.FECHA
AND bh.GWNAME = hist.GWNAME
AND bh.SERVID = hist.SERVID
AND bh.SERVNAME = hist.SERVNAME
GROUP BY TRUNC(hist.FECHA , 'MONTH'), hist.GWNAME, hist.SERVID, hist.SERVNAME
;
