--------------------------------------------------------
--  DDL for View CORE_CISCO_L81201_GGSN_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81201_GGSN_BH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "CURRENT_NUM_SESS") AS 
  SELECT hist.FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, hist.CURRENT_NUM_SESS
FROM (
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, GWNAME, SERVID, SERVNAME,
      ROUND (AVG(CURRENT_NUM_SESS), 2) AS CURRENT_NUM_SESS
      FROM CORE_CISCO_L81201_GGSN_HIST
      GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
) hist
INNER JOIN L81505_L81513_BH_AUX2 aux
ON hist.FECHA = aux.FECHA
AND hist.GWNAME = aux.GWNAME
AND hist.SERVID = aux.SERVID
AND hist.SERVNAME = aux.SERVNAME
;
