--------------------------------------------------------
--  DDL for View CORE_CISCO_L81201_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81201_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "CURRENT_NUM_SESS") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME,
ROUND (AVG(CURRENT_NUM_SESS), 2) AS CURRENT_NUM_SESS
FROM CORE_CISCO_L81201_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'),SERVID, SERVNAME, GWNAME
;
