--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B02_GGSN_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B02_GGSN_BH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "GX_SESS_TERMINATED") AS 
  SELECT hist.FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, hist.GX_SESS_TERMINATED
FROM (
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, GWNAME, SERVID, SERVNAME,
      SUM(DPCATERM) AS GX_SESS_TERMINATED
      FROM CORE_CISCO_L81B02_GGSN_HIST
      GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
) hist
INNER JOIN L81505_L81513_BH_AUX2 aux
ON hist.FECHA = aux.FECHA
;
