--------------------------------------------------------
--  DDL for View CORE_CISCO_L71302_GGSN_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71302_GGSN_MONTH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_DROPPED") AS 
  SELECT TRUNC( FECHA  , 'MONTH') AS FECHA, GWNAME, SERVID, SERVNAME, SUM(UPLINK_DROPPED) AS UPLINK_DROPPED
FROM CORE_CISCO_L71302_GGSN_HIST
GROUP BY  GWNAME, SERVID, SERVNAME, TRUNC( FECHA  , 'MONTH')
;
