--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B02_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B02_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "GX_SESS_TERMINATED") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME,
SUM(DPCATERM) AS GX_SESS_TERMINATED
FROM CORE_CISCO_L81B02_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), SERVID, SERVNAME, GWNAME
;
