--------------------------------------------------------
--  DDL for View CORE_CISCO_L81513_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81513_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_THP_MBPS_GBR") AS 
  SELECT TRUNC(FECHA, 'HH24')  as FECHA, GWNAME, SERVID, SERVNAME,
ROUND (AVG(DOWNLINK_THP_MBPS_GBR), 2) AS DOWNLINK_THP_MBPS_GBR
FROM CORE_CISCO_L81513_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24') , SERVID, GWNAME, SERVNAME
;
