--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B03_GGSN_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B03_GGSN_MONTH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DPCA_CCA_MESSAGES_ACCEPTED") AS 
  SELECT TRUNC( FECHA, 'DAY') as FECHA, GWNAME,  SERVID, SERVNAME,
ROUND ((DECODE (SUM(DPCAMSGCCRINIT), 0, 0, SUM(DPCAMSGCCAINITACC) / SUM(DPCAMSGCCRINIT))),2) as DPCA_CCA_MESSAGES_ACCEPTED
FROM CORE_CISCO_L81B03_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DAY'), SERVID, SERVNAME,  GWNAME
;
