--------------------------------------------------------
--  DDL for View CORE_CISCO_L81801_GGSN_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81801_GGSN_WEEK" ("FECHA", "GWNAME", "DIAMETER_CC_INITIAL_SUCC_R") AS 
  SELECT TRUNC( FECHA, 'DAY') as FECHA, GWNAME,
ROUND (((DECODE (SUM(CCMSGCCRINIT), 0, 0, SUM(CCMSGCCAINITACCEPT) / SUM(CCMSGCCRINIT)) )*100),2) as DIAMETER_CC_INITIAL_SUCC_R
FROM CORE_CISCO_L81801_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DAY'), GWNAME
;
