--------------------------------------------------------
--  DDL for View CORE_CISCO_L81513_GGSN_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81513_GGSN_BH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_THP_MBPS_GBR") AS 
  SELECT hist.FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, hist.DOWNLINK_THP_MBPS_GBR
FROM (
    SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME,
     ROUND (AVG(DOWNLINK_THP_MBPS_GBR), 2) AS DOWNLINK_THP_MBPS_GBR
    FROM CORE_CISCO_L81513_GGSN_HIST
    GROUP BY TRUNC(FECHA, 'HH24') , SERVID, GWNAME, SERVNAME
) hist
INNER JOIN L81505_L81513_BH_AUX2 aux
ON hist.FECHA = aux.FECHA
AND hist.GWNAME = aux.GWNAME
AND hist.SERVID = aux.SERVID
AND hist.SERVNAME = aux.SERVNAME
;
