--------------------------------------------------------
--  DDL for View CORE_CISCO_L71301_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71301_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_THROUGHPUT") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(UPLINK_THROUGHPUT), 2) AS UPLINK_THROUGHPUT
FROM CORE_CISCO_L71301_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
;
