--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B04_GGSN_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B04_GGSN_WEEK" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DPCA_CCA_MESSAGES_REJECTED") AS 
  SELECT TRUNC( FECHA, 'DAY') as FECHA, GWNAME,  SERVID, SERVNAME,
ROUND ((DECODE (SUM(DPCAMSGCCRINIT), 0, 0, SUM(DPCAMSGCCAINITREJ) / SUM(DPCAMSGCCRINIT))),2) as DPCA_CCA_MESSAGES_REJECTED
FROM CORE_CISCO_L81B04_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DAY'), SERVID, SERVNAME,  GWNAME
;
