--------------------------------------------------------
--  DDL for View CORE_CISCO_L81804_GGSN_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81804_GGSN_DAY" ("FECHA", "GWNAME", "DIAMETER_CC_TERMINATION_SUCC_R") AS 
  SELECT TRUNC( FECHA, 'DD') as FECHA, GWNAME,
ROUND (((DECODE (SUM(CCMSGCCRFINAL), 0, 0, SUM(CCMSGCCAFINAL) / SUM(CCMSGCCRFINAL)) )*100),2) as DIAMETER_CC_TERMINATION_SUCC_R
FROM CORE_CISCO_L81804_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DD'), GWNAME
;
