--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B03_GGSN_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B03_GGSN_BH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DPCA_CCA_MESSAGES_ACCEPTED") AS 
  SELECT hist.FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, hist.DPCA_CCA_MESSAGES_ACCEPTED
FROM (
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, GWNAME, SERVID, SERVNAME,
      ROUND ((DECODE (SUM(DPCAMSGCCRINIT), 0, 0, SUM(DPCAMSGCCAINITACC) / SUM(DPCAMSGCCRINIT))),2) as DPCA_CCA_MESSAGES_ACCEPTED
      FROM CORE_CISCO_L81B03_GGSN_HIST
      GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
) hist
INNER JOIN L81505_L81513_BH_AUX2 aux
ON hist.FECHA = aux.FECHA
;
