--------------------------------------------------------
--  DDL for View CORE_CISCO_L71304_GGSN_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71304_GGSN_DAY" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_DROPPED") AS 
  SELECT TRUNC( FECHA, 'DD') as FECHA, GWNAME, SERVID, SERVNAME, SUM(DOWNLINK_DROPPED) AS DOWNLINK_DROPPED
FROM CORE_CISCO_L71304_GGSN_HIST
GROUP BY TRUNC( FECHA, 'DD'), GWNAME, SERVID, SERVNAME
;
