--------------------------------------------------------
--  DDL for View CORE_CISCO_L81C01_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81C01_GGSN_HOUR" ("FECHA", "GWNAME", "PGW_LICENSING") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SUM(PGWACTIVEDATA) AS PGW_LICENSING
FROM CORE_CISCO_L81C01_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), GWNAME
;
