--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B01_GGSN_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B01_GGSN_DAY" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "CURRENT_ACTIVE_GX_SESS") AS 
  SELECT TRUNC( FECHA, 'DD') as FECHA, GWNAME, SERVID, SERVNAME, SUM(DPCACURSESS) AS CURRENT_ACTIVE_GX_SESS
FROM CORE_CISCO_L81B01_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DD'), SERVID, SERVNAME,GWNAME
;
