--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B01_GGSN_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B01_GGSN_WEEK" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "CURRENT_ACTIVE_GX_SESS") AS 
  SELECT TRUNC( FECHA, 'DAY') as FECHA, GWNAME, SERVID, SERVNAME, SUM(DPCACURSESS) AS CURRENT_ACTIVE_GX_SESS
FROM CORE_CISCO_L81B01_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DAY'), SERVID, SERVNAME,GWNAME
;
