--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B03_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B03_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DPCA_CCA_MESSAGES_ACCEPTED") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME,
ROUND ((DECODE (SUM(DPCAMSGCCRINIT), 0, 0, SUM(DPCAMSGCCAINITACC) / SUM(DPCAMSGCCRINIT))),2) as DPCA_CCA_MESSAGES_ACCEPTED
FROM CORE_CISCO_L81B03_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), SERVID, SERVNAME, GWNAME
;
