--------------------------------------------------------
--  DDL for View CORE_CISCO_L71304_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71304_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_DROPPED") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME, SUM(DOWNLINK_DROPPED) AS DOWNLINK_DROPPED
FROM CORE_CISCO_L71304_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
;
