--------------------------------------------------------
--  DDL for View CORE_CISCO_L71301_GGSN_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71301_GGSN_MONTH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_THROUGHPUT") AS 
  SELECT TRUNC( FECHA  , 'MONTH') AS FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(UPLINK_THROUGHPUT), 2) AS UPLINK_THROUGHPUT
FROM CORE_CISCO_L71301_GGSN_HIST
GROUP BY  GWNAME, SERVID, SERVNAME, TRUNC( FECHA  , 'MONTH')
;
