--------------------------------------------------------
--  DDL for View CORE_CISCO_L71304_GGSN_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71304_GGSN_MONTH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_DROPPED") AS 
  SELECT TRUNC( FECHA  , 'MONTH') AS FECHA, GWNAME, SERVID, SERVNAME, SUM(DOWNLINK_DROPPED) AS DOWNLINK_DROPPED
FROM CORE_CISCO_L71304_GGSN_HIST
GROUP BY  GWNAME, SERVID, SERVNAME, TRUNC( FECHA  , 'MONTH')
;
