--------------------------------------------------------
--  DDL for View CORE_CISCO_L81B01_GGSN_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81B01_GGSN_HOUR" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "CURRENT_ACTIVE_GX_SESS") AS 
  SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME,
SUM(DPCACURSESS) AS CURRENT_ACTIVE_GX_SESS
FROM CORE_CISCO_L81B01_GGSN_HIST
WHERE FECHA >= SYSDATE - 45
GROUP BY TRUNC(FECHA, 'HH24'),SERVID, SERVNAME, GWNAME
;
