--------------------------------------------------------
--  DDL for View CORE_CISCO_L81513_GGSN_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81513_GGSN_WEEK" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_THP_MBPS_GBR") AS 
  SELECT TRUNC( FECHA  , 'DAY') AS FECHA ,GWNAME, SERVID, SERVNAME, ROUND (AVG(DOWNLINK_THP_MBPS_GBR), 2) AS DOWNLINK_THP_MBPS_GBR
FROM CORE_CISCO_L81513_GGSN_HIST
GROUP BY GWNAME, SERVID, SERVNAME, TRUNC( FECHA  , 'DAY')
;
