--------------------------------------------------------
--  DDL for View CORE_CISCO_L81801_GGSN_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81801_GGSN_BH" ("FECHA", "GWNAME", "DIAMETER_CC_INITIAL_SUCC_R") AS 
  SELECT hist.FECHA, hist.GWNAME, hist.DIAMETER_CC_INITIAL_SUCC_R
FROM (
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, GWNAME,
      ROUND (((DECODE (SUM(CCMSGCCRINIT), 0, 0, SUM(CCMSGCCAINITACCEPT) / SUM(CCMSGCCRINIT)) )*100),2) as DIAMETER_CC_INITIAL_SUCC_R
      FROM CORE_CISCO_L81801_GGSN_HIST
      GROUP BY TRUNC(FECHA, 'HH24'), GWNAME
) hist
INNER JOIN L81505_L81513_BH_AUX2 aux
ON hist.FECHA = aux.FECHA
AND hist.GWNAME = aux.GWNAME
;
