--------------------------------------------------------
--  DDL for View CORE_CISCO_L71304_GGSN_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L71304_GGSN_BH" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "DOWNLINK_DROPPED") AS 
  SELECT hist.FECHA, hist.GWNAME, hist.SERVID, hist.SERVNAME, hist.DOWNLINK_DROPPED
FROM (
    SELECT TRUNC(FECHA, 'HH24') as FECHA, GWNAME, SERVID, SERVNAME, SUM(DOWNLINK_DROPPED) AS DOWNLINK_DROPPED
    FROM CORE_CISCO_L71304_GGSN_HIST
    GROUP BY TRUNC(FECHA, 'HH24'), SERVID, GWNAME, SERVNAME
) hist
INNER JOIN L71301_L71303_BH_AUX2 aux
ON hist.FECHA = aux.FECHA
AND hist.GWNAME = aux.GWNAME
AND hist.SERVID = aux.SERVID
AND hist.SERVNAME = aux.SERVNAME
;
