--------------------------------------------------------
--  DDL for View CORE_CISCO_L81505_GGSN_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81505_GGSN_DAY" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "UPLINK_THP_MBPS") AS 
  SELECT TRUNC( FECHA, 'DD')  AS FECHA, GWNAME, SERVID, SERVNAME,
ROUND (AVG(UPLINK_THP_MBPS), 2) AS UPLINK_THP_MBPS
FROM CORE_CISCO_L81505_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DD'), GWNAME, SERVID, SERVNAME
;
