--------------------------------------------------------
--  DDL for View CORE_CISCO_L81201_GGSN_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CORE_CISCO_L81201_GGSN_WEEK" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "CURRENT_NUM_SESS") AS 
  SELECT TRUNC( FECHA, 'DAY') as FECHA, GWNAME, SERVID, SERVNAME,ROUND (AVG(CURRENT_NUM_SESS), 2) AS CURRENT_NUM_SESS
FROM CORE_CISCO_L81201_GGSN_HIST
GROUP BY  TRUNC( FECHA, 'DAY'), SERVID, SERVNAME,GWNAME
;
