--------------------------------------------------------
--  DDL for View CSFB_REDIR_CR_ATT_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CSFB_REDIR_CR_ATT_HOUR" ("PERIOD_START_TIME", "CSFB_REDIR_CR_ATT") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS PERIOD_START_TIME,
      SUM(CSFB_REDIR_CR_ATT) AS CSFB_REDIR_CR_ATT
FROM CSFB_REDIR_CR_ATT
GROUP BY TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , CO_NAME
;
