--------------------------------------------------------
--  DDL for View CSFB_REDIR_CR_ATT_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CSFB_REDIR_CR_ATT_MONTH" ("PERIOD_START_TIME", "CO_NAME", "CSFB_REDIR_CR_ATT") AS 
  SELECT TRUNC( PERIOD_START_TIME  , 'MONTH') AS PERIOD_START_TIME, CO_NAME,
		SUM(CSFB_REDIR_CR_ATT) AS CSFB_REDIR_CR_ATT
FROM CSFB_REDIR_CR_ATT_HISTORICAL
GROUP BY TRUNC( PERIOD_START_TIME  , 'MONTH'), CO_NAME
;
