--------------------------------------------------------
--  DDL for View CSFB_REDIR_CR_ATT_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CSFB_REDIR_CR_ATT_WEEK" ("PERIOD_START_TIME", "CO_NAME", "CSFB_REDIR_CR_ATT") AS 
  SELECT TRUNC( PERIOD_START_TIME  , 'DAY') AS PERIOD_START_TIME, CO_NAME,
    SUM(CSFB_REDIR_CR_ATT) AS CSFB_REDIR_CR_ATT
FROM CSFB_REDIR_CR_ATT_HISTORICAL
GROUP BY TRUNC( PERIOD_START_TIME  , 'DAY'), CO_NAME
;
