--------------------------------------------------------
--  DDL for View CSFB_REDIR_CR_ATT_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."CSFB_REDIR_CR_ATT_DAY" ("PERIOD_START_TIME", "CO_NAME", "CSFB_REDIR_CR_ATT") AS 
  SELECT TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR') AS PERIOD_START_TIME, CO_NAME,
			SUM(CSFB_REDIR_CR_ATT) AS CSFB_REDIR_CR_ATT
FROM CSFB_REDIR_CR_ATT_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR'), CO_NAME
;
