--------------------------------------------------------
--  DDL for Table ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "HARRIAGUE"."ERROR_LOG" 
   (	"ID" NUMBER(*,0), 
	"IMPORT_DATE" DATE, 
	"SOURCE" VARCHAR2(100 BYTE), 
	"TARGET" VARCHAR2(100 BYTE), 
	"LNBTS_ID" NUMBER DEFAULT NULL, 
	"LNCEL_ID" NUMBER DEFAULT NULL, 
	"FINS_ID" NUMBER DEFAULT NULL, 
	"PERIOD_START_TIME" DATE, 
	"MCC_ID" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"MNC_ID" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"TA_ID" VARCHAR2(255 BYTE) DEFAULT NULL, 
	"MMDU_ID" VARCHAR2(255 BYTE) DEFAULT NULL, 
	"UNIT_ID" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"ERROR_NRO" NUMBER, 
	"ERROR_MESG" VARCHAR2(4000 BYTE)
   ) ;
