--------------------------------------------------------
--  Constraints for Table ERROR_LOG
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."ERROR_LOG" ADD CONSTRAINT "ERRROR_LOG_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."ERROR_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."ERROR_LOG" MODIFY ("IMPORT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."ERROR_LOG" MODIFY ("SOURCE" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."ERROR_LOG" MODIFY ("TARGET" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."ERROR_LOG" MODIFY ("PERIOD_START_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."ERROR_LOG" MODIFY ("ERROR_NRO" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."ERROR_LOG" MODIFY ("ERROR_MESG" NOT NULL ENABLE);
