--------------------------------------------------------
--  DDL for View FLNS_5035A_CONS_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5035A_CONS_WEEK" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MMDU_ID", "MME_NAME", "EPS_MMDU_EMM_REG_MIN", "EPS_MMDU_EMM_REG_MAX", "FLNS_5035A") AS 
  SELECT TRUNC(FECHA , 'DAY') AS FECHA, PERIOD_DURATION, FINS_ID,  MMDU_ID, MME_NAME,
        MIN(EPS_MMDU_EMM_REG_MIN) as EPS_MMDU_EMM_REG_MIN,
        MAX(EPS_MMDU_EMM_REG_MAX) as EPS_MMDU_EMM_REG_MAX,
       ROUND (DECODE (SUM(EPS_MMDU_EMM_REG_DENOM), 0 ,0, SUM(EPS_MMDU_EMM_REG_SUM) / SUM(EPS_MMDU_EMM_REG_DENOM) ), 2) AS FLNS_5035A
FROM FLNS_5035A_HISTORICAL
GROUP BY  TRUNC(FECHA , 'DAY'), PERIOD_DURATION, FINS_ID, MME_NAME, MMDU_ID
;
