--------------------------------------------------------
--  DDL for View FLNS_5040B_CONS_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5040B_CONS_WEEK" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_5040B") AS 
  SELECT TRUNC( FECHA  , 'DAY') AS FECHA , PERIOD_DURATION, FINS_ID, MME_NAME,
    ROUND ((DECODE (SUM(EPS_S1HO_FAIL), 0 ,0,
              SUM(EPS_S1HO_SUCC) / SUM(EPS_S1HO_FAIL) ) ) * 100, 2) AS FLNS_5040B
FROM FLNS_5040B_HISTORICAL
GROUP BY FINS_ID, PERIOD_DURATION,MME_NAME,TRUNC( FECHA  , 'DAY')
;
