--------------------------------------------------------
--  DDL for View FLNS_3051A_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3051A_BH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "UNIT_ID", "COMP_AVERAGE_LOAD", "COMP_PEAK_LOAD_PERCENT") AS 
  SELECT hist.FECHA, hist.PERIOD_DURATION, hist.FINS_ID, hist.MME_NAME, hist.UNIT_ID, hist.COMP_AVERAGE_LOAD, hist.COMP_PEAK_LOAD_PERCENT
FROM (
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, PERIOD_DURATION, FINS_ID, MME_NAME,UNIT_ID,
        ROUND(MAX(COMP_AVERAGE_LOAD)/10, 2) AS COMP_AVERAGE_LOAD, MAX(COMP_PEAK_LOAD_PERCENT) AS COMP_PEAK_LOAD_PERCENT
      FROM FLNS_3051A_HISTORICAL
      GROUP BY TRUNC(FECHA, 'HH24'), PERIOD_DURATION,FINS_ID,MME_NAME, UNIT_ID
) hist
INNER JOIN PCOFNS_PS_ULOAD_UNIT1_BH_AUX aux
ON hist.FECHA = aux.FECHA
AND hist.FINS_ID = aux.FINS_ID
AND hist.UNIT_ID = aux.UNIT_ID
AND hist.MME_NAME = aux.MME_NAME
;
