--------------------------------------------------------
--  DDL for View FLNS_5017A_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5017A_BH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_5017A") AS 
  SELECT hist.FECHA, hist.PERIOD_DURATION, hist.FINS_ID, hist.MME_NAME, hist.TA_ID, hist.FLNS_5017A
FROM (
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, PERIOD_DURATION, FINS_ID, TA_ID,MME_NAME,
       ROUND ((DECODE (SUM(EPS_PAGING_FAIL), 0 ,0, SUM(EPS_PAGING_SUCC) / SUM(EPS_PAGING_FAIL) ) ) * 100, 2) AS FLNS_5017A
      FROM FLNS_5017A_HISTORICAL
      GROUP BY TRUNC(FECHA, 'HH24'), PERIOD_DURATION, FINS_ID,MME_NAME, TA_ID
) hist
INNER JOIN PCOFNS_PS_MMMT_TA_BH_AUX aux
ON hist.FECHA = aux.FECHA
AND hist.FINS_ID = aux.FINS_ID
AND hist.TA_ID = aux.TA_ID
AND hist.MME_NAME = aux.MME_NAME
;
