--------------------------------------------------------
--  DDL for View FLNS_3051A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3051A_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "UNIT_ID", "COMP_AVERAGE_LOAD", "COMP_PEAK_LOAD_PERCENT") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.UNIT_ID, FLNS.COMP_AVERAGE_LOAD, FLNS.COMP_PEAK_LOAD_PERCENT
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, UNIT_ID,
           COMP_AVERAGE_LOAD, COMP_PEAK_LOAD_PERCENT
    FROM PCOFNS_PS_ULOAD_UNIT1_RAW
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
