--------------------------------------------------------
--  DDL for View FLNS_5035A_CONS_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5035A_CONS_BH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_5035A", "EPS_MMDU_EMM_REG_MIN", "EPS_MMDU_EMM_REG_MAX") AS 
  SELECT hist.FECHA, hist.PERIOD_DURATION, hist.FINS_ID, hist.MME_NAME,  hist.FLNS_5035A, hist.EPS_MMDU_EMM_REG_MIN, hist.EPS_MMDU_EMM_REG_MAX
FROM (
    SELECT TRUNC(FECHA, 'HH24') AS FECHA, PERIOD_DURATION, FINS_ID,MME_NAME,
     MIN(EPS_MMDU_EMM_REG_MIN) AS EPS_MMDU_EMM_REG_MIN,
     MAX(EPS_MMDU_EMM_REG_MAX) AS EPS_MMDU_EMM_REG_MAX,
     ROUND (DECODE (SUM(EPS_MMDU_EMM_REG_DENOM), 0 ,0, SUM(EPS_MMDU_EMM_REG_SUM) / SUM(EPS_MMDU_EMM_REG_DENOM) ), 2) AS FLNS_5035A
    FROM FLNS_5035A_HISTORICAL
    GROUP BY TRUNC(FECHA, 'HH24'), PERIOD_DURATION,FINS_ID,MME_NAME
) hist
INNER JOIN PCOFNS_PS_MMMT_TA_BH_AUX aux
ON hist.FECHA = aux.FECHA
AND hist.FINS_ID = aux.FINS_ID
AND hist.MME_NAME = aux.MME_NAME
;
