--------------------------------------------------------
--  DDL for View FLNS_5014A_CONS_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5014A_CONS_MONTH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_5014A") AS 
  SELECT TRUNC( FECHA  , 'MONTH') AS FECHA, PERIOD_DURATION, FINS_ID, MME_NAME,
    ROUND ((DECODE (SUM(EPS_SERVICE_REQUEST_FAIL), 0 ,0,
              SUM(EPS_SERVICE_REQUEST_SUCC) / SUM(EPS_SERVICE_REQUEST_FAIL) ) ) * 100, 2) AS FLNS_5014A
FROM FLNS_5014A_HISTORICAL
GROUP BY   FINS_ID,  PERIOD_DURATION,  MME_NAME, TRUNC( FECHA  , 'MONTH')
;
