--------------------------------------------------------
--  DDL for View FLNS_3112A_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3112A_MONTH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_3112A") AS 
  SELECT TRUNC(FECHA , 'MONTH') AS FECHA, PERIOD_DURATION, FINS_ID,
       MME_NAME,TA_ID, ROUND (DECODE (AVG(PERIOD_DURATION*60), 0 ,0,
              SUM(FLNS_3112A) / AVG(PERIOD_DURATION*60) ) , 2) AS FLNS_3112A
FROM FLNS_3112A_HISTORICAL
GROUP BY  TRUNC(FECHA , 'MONTH'), PERIOD_DURATION, FINS_ID, TA_ID,MME_NAME
;
