--------------------------------------------------------
--  DDL for View FLNS_3051A_CONS_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3051A_CONS_BH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "COMP_AVERAGE_LOAD", "COMP_PEAK_LOAD_PERCENT") AS 
  SELECT hist.FECHA, hist.PERIOD_DURATION, hist.FINS_ID, hist.MME_NAME, hist.COMP_AVERAGE_LOAD, hist.COMP_PEAK_LOAD_PERCENT
FROM (
      SELECT TRUNC(FECHA, 'HH24') AS FECHA, PERIOD_DURATION,FINS_ID,  MME_NAME,
        ROUND(MAX(COMP_AVERAGE_LOAD)/10, 2) AS COMP_AVERAGE_LOAD, MAX(COMP_PEAK_LOAD_PERCENT) AS COMP_PEAK_LOAD_PERCENT
      FROM FLNS_3051A_HISTORICAL
      GROUP BY TRUNC(FECHA, 'HH24'), PERIOD_DURATION,FINS_ID,MME_NAME
) hist
INNER JOIN PCOFNS_PS_UL_UNIT1_CONS_BH_AUX aux
ON hist.FECHA = aux.FECHA
AND hist.FINS_ID = aux.FINS_ID
AND hist.MME_NAME = aux.MME_NAME
;
