--------------------------------------------------------
--  DDL for View FLNS_3112A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3112A_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_3112A") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.TA_ID, FLNS.FLNS_3112A
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID,
           sum(PDN_CONNECT_FAILED_COLLISION +
                PDN_CONNECT_FAILED_UNSPECIFIED +
                PDN_CONNECTIVITY_FAILED_MME +
                PDN_CONNECTIVITY_FAILED_SGW +
                PDN_CONNECTIVITY_SUCCESSFUL +
                PDN_CONNECTIVITY_FAILED +
                DDBEARER_UEINIT_DEACT_SUCC +
                DDBEARER_UEINIT_DEACT_FAIL +
                DDBEARER_MMEINIT_DEACT_SUCC +
                DDBEARER_MMEINIT_DEACT_ABNORM +
                DDBEARER_PGWINIT_DEACT_SUCC) AS FLNS_3112A
    FROM PCOFNS_PS_SMMT_TA_RAW
    GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
