--------------------------------------------------------
--  DDL for View FLNS_3218A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3218A_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_3218A") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.TA_ID, FLNS.FLNS_3218A
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID,
          sum(EPS_SERVICE_REQUEST_SUCC +
          EPS_SERVICE_REQUEST_FAIL -
          EPS_PAGING_SUCC) AS FLNS_3218A
    FROM PCOFNS_PS_MMMT_TA_RAW
    GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
