--------------------------------------------------------
--  DDL for View FLNS_5001A_CONS_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5001A_CONS_WEEK" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_5001A") AS 
  SELECT TRUNC( FECHA  , 'DAY') AS FECHA, PERIOD_DURATION, FINS_ID,MME_NAME,
        ROUND ((DECODE (SUM(EPS_ATTACH_FAIL), 0 ,0,
              SUM(EPS_ATTACH_SUCC) / SUM(EPS_ATTACH_FAIL) ) ) * 100, 2) AS FLNS_5001A
FROM FLNS_5001A_HISTORICAL
GROUP BY FINS_ID, PERIOD_DURATION,MME_NAME, TRUNC( FECHA  , 'DAY')
;
