--------------------------------------------------------
--  DDL for View FLNS_5014A_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5014A_DAY" ("FECHA", "PERIOD_DURATION", "FINS_ID", "TA_ID", "MME_NAME", "FLNS_5014A") AS 
  SELECT TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, PERIOD_DURATION,FINS_ID, TA_ID, MME_NAME,
ROUND ((DECODE (SUM(EPS_SERVICE_REQUEST_FAIL), 0 ,0,
              SUM(EPS_SERVICE_REQUEST_SUCC) / SUM(EPS_SERVICE_REQUEST_FAIL) ) ) * 100, 2) AS FLNS_5014A
FROM FLNS_5014A_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR'), PERIOD_DURATION,FINS_ID, TA_ID, MME_NAME
;
