--------------------------------------------------------
--  DDL for View FLNS_3102D_CONS_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3102D_CONS_BH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_3102D") AS 
  SELECT hist.FECHA, hist.PERIOD_DURATION, hist.FINS_ID, hist.MME_NAME, hist.FLNS_3102D
FROM (
    SELECT TRUNC(FECHA, 'HH24') AS FECHA, PERIOD_DURATION, FINS_ID, MME_NAME,
       ROUND (DECODE (AVG(PERIOD_DURATION*60), 0 ,0, SUM(FLNS_3102D) / AVG(PERIOD_DURATION*60) ) , 2) AS FLNS_3102D
    FROM FLNS_3102D_HISTORICAL
    GROUP BY TRUNC(FECHA, 'HH24'), PERIOD_DURATION,FINS_ID, MME_NAME
) hist
INNER JOIN PCOFNS_PS_MMMT_TA_CONS_BH_AUX aux
ON hist.FECHA = aux.FECHA
AND hist.FINS_ID = aux.FINS_ID
AND hist.MME_NAME = aux.MME_NAME
;
