--------------------------------------------------------
--  DDL for View FLNS_5014A
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5014A" ("FECHA", "PERIOD_DURATION", "FINS_ID", "TA_ID", "MME_NAME", "EPS_SERVICE_REQUEST_SUCC", "EPS_SERVICE_REQUEST_FAIL") AS 
  SELECT FECHA, PERIOD_DURATION, FINS_ID, TA_ID, MME_NAME, EPS_SERVICE_REQUEST_SUCC, EPS_SERVICE_REQUEST_FAIL
FROM FLNS_5014A_HISTORICAL
WHERE FECHA >= (SELECT SYSDATE - 45 FROM DUAL)
;
