--------------------------------------------------------
--  DDL for View FLNS_5011B_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5011B_DAY" ("FECHA", "PERIOD_DURATION", "FINS_ID", "TA_ID", "MME_NAME", "FLNS_5011B") AS 
  SELECT TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, PERIOD_DURATION, FINS_ID, TA_ID, MME_NAME,
ROUND ((DECODE (SUM(EPS_PATH_SWITCH_X2_FAIL), 0 ,0,
              SUM(EPS_PATH_SWITCH_X2_SUCC) / SUM(EPS_PATH_SWITCH_X2_FAIL) ) ) * 100, 2) AS FLNS_5011B
FROM FLNS_5011B_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR'), PERIOD_DURATION, FINS_ID, TA_ID,MME_NAME
;
