--------------------------------------------------------
--  DDL for View FLNS_5020A_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5020A_DAY" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_5020A") AS 
  SELECT TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, PERIOD_DURATION, FINS_ID, MME_NAME,
		TA_ID, ROUND ((DECODE (SUM(EPS_DEF_BEARER_ACT_FAIL), 0 ,0,
              SUM(EPS_DEF_BEARER_ACT_SUCC) / SUM(EPS_DEF_BEARER_ACT_FAIL) ) ) * 100, 2) AS FLNS_5020A
FROM FLNS_5020A_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR'),  PERIOD_DURATION,FINS_ID,MME_NAME, TA_ID
;
