--------------------------------------------------------
--  DDL for View FLNS_3287A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3287A_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_3287A") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.FLNS_3287A
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID,
            SUM(SRVCC_CS_HO_2G_SUCC +
                SRVCC_CS_HO_2G_FAIL +
                SRVCC_CS_HANDOVER_SUCC +
                SRVCC_CS_HO_3G_FAIL +
                SRVCC_PS_AND_CS_HANDOVER_SUCC +
                SRVCC_PS_AND_CS_HO_3G_FAIL +
                SRVCC_EME_HO_2G_SUCC +
                SRVCC_EME_HO_2G_FAIL +
                SRVCC_EME_HO_3G_SUCC +
                SRVCC_EME_HO_3G_FAIL) AS FLNS_3287A
    FROM PCOFNS_PS_UMLM_FLEXINS_RAW
    GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
