--------------------------------------------------------
--  DDL for View FLNS_5017A_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5017A_HOUR" ("FECHA", "PERIOD_DURATION", "FINS_ID", "TA_ID", "MME_NAME", "FLNS_5017A") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS FECHA,
		 PERIOD_DURATION, FINS_ID, TA_ID,MME_NAME, ROUND ((DECODE (SUM(EPS_PAGING_FAIL), 0 ,0,
              SUM(EPS_PAGING_SUCC) / SUM(EPS_PAGING_FAIL) ) ) * 100, 2) AS FLNS_5017A
FROM FLNS_5017A
GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI'),
		 PERIOD_DURATION, FINS_ID,MME_NAME, TA_ID
;
