--------------------------------------------------------
--  DDL for View FLNS_5047A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5047A_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "EPS_BEARER_DEFAULT_NBR_SUM", "EPS_BEARER_DEFAULT_NBR_DEN") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA,
       FLNS.PERIOD_DURATION,
       FLNS.FINS_ID,
       MO.MME_NAME,
       FLNS.EPS_BEARER_DEFAULT_NBR_SUM,
       FLNS.EPS_BEARER_DEFAULT_NBR_DEN
  FROM (SELECT PERIOD_START_TIME,
               PERIOD_DURATION,
               FINS_ID,
               SUM(EPS_BEARER_DEFAULT_NBR_SUM) AS EPS_BEARER_DEFAULT_NBR_SUM,
               AVG(EPS_BEARER_DEFAULT_NBR_DEN) AS EPS_BEARER_DEFAULT_NBR_DEN
          FROM PCOFNS_PS_MULM_MMDU_RAW
         GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID) FLNS
 INNER JOIN (SELECT SGSN_NAME AS MME_NAME, SGSN_ID
               FROM VW_SGSN_OBJECTS
              WHERE VALID_FINISH_DATE > SYSDATE AND ORDEN = '1') MO
    ON MO.SGSN_ID = FLNS.FINS_ID
;
