--------------------------------------------------------
--  DDL for View FLNS_5020A_CONS_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5020A_CONS_MONTH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_5020A") AS 
  SELECT TRUNC( FECHA  , 'MONTH') AS FECHA, PERIOD_DURATION, FINS_ID, MME_NAME,
    ROUND ((DECODE (SUM(EPS_DEF_BEARER_ACT_FAIL), 0 ,0,
              SUM(EPS_DEF_BEARER_ACT_SUCC) / SUM(EPS_DEF_BEARER_ACT_FAIL) ) ) * 100, 2) AS FLNS_5020A
FROM FLNS_5020A_HISTORICAL
GROUP BY   FINS_ID, PERIOD_DURATION,MME_NAME, TRUNC( FECHA  , 'MONTH')
;
