--------------------------------------------------------
--  DDL for View FLNS_5001A_CONS_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5001A_CONS_HOUR" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_5001A") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS FECHA,
      PERIOD_DURATION, FINS_ID, MME_NAME, ROUND ((DECODE (SUM(EPS_ATTACH_FAIL), 0 ,0,
              SUM(EPS_ATTACH_SUCC) / SUM(EPS_ATTACH_FAIL) ) ) * 100, 2) AS FLNS_5001A
FROM FLNS_5001A
GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , PERIOD_DURATION,
          FINS_ID,  MME_NAME
;
