--------------------------------------------------------
--  DDL for View FLNS_3109B_CONS_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3109B_CONS_MONTH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_3109B") AS 
  SELECT TRUNC( FECHA  , 'MONTH') AS FECHA, PERIOD_DURATION, FINS_ID,
       MME_NAME, ROUND (DECODE (AVG(PERIOD_DURATION*60*4), 0 ,0,
              AVG(FLNS_3109B) / AVG(PERIOD_DURATION*60*4) ) , 2) AS FLNS_3109B
FROM FLNS_3109B_HISTORICAL
GROUP BY  TRUNC( FECHA  , 'MONTH'), PERIOD_DURATION, FINS_ID, MME_NAME
;
