--------------------------------------------------------
--  DDL for View FLNS_3102D_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3102D_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_3102D") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.TA_ID, FLNS.FLNS_3102D
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID,
            SUM(INTRATAU_WO_SGW_CHANGE_SUCC +
				INTRAMME_TAU_SGW_CHG_SUCC +
				INTRATAU_WO_SGW_CHANGE_FAIL +
				EPS_PERIODIC_TAU_SUCC +
	      EPS_PERIODIC_TAU_FAIL) AS FLNS_3102D
    FROM PCOFNS_PS_MMMT_TA_RAW
    GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
