--------------------------------------------------------
--  DDL for View FLNS_5040B_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5040B_DAY" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_5040B") AS 
  SELECT TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, PERIOD_DURATION, FINS_ID, MME_NAME,
		TA_ID, ROUND ((DECODE (SUM(EPS_S1HO_FAIL), 0 ,0,
              SUM(EPS_S1HO_SUCC) / SUM(EPS_S1HO_FAIL) ) ) * 100, 2) AS FLNS_5040B
FROM FLNS_5040B_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR'),MME_NAME, PERIOD_DURATION, FINS_ID, TA_ID
;
