--------------------------------------------------------
--  DDL for View FLNS_3115A_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3115A_WEEK" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_3115A") AS 
  SELECT TRUNC(FECHA , 'DAY') AS FECHA, PERIOD_DURATION, FINS_ID,
       MME_NAME,TA_ID, ROUND (DECODE (AVG(PERIOD_DURATION*60), 0 ,0,
              AVG(FLNS_3115A) / AVG(PERIOD_DURATION*60) ) , 2) AS FLNS_3115A
FROM FLNS_3115A_HISTORICAL
GROUP BY  TRUNC(FECHA , 'DAY'), PERIOD_DURATION, FINS_ID, TA_ID,MME_NAME
;
