--------------------------------------------------------
--  DDL for View FLNS_5011B
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5011B" ("FECHA", "PERIOD_DURATION", "FINS_ID", "TA_ID", "MME_NAME", "EPS_PATH_SWITCH_X2_SUCC", "EPS_PATH_SWITCH_X2_FAIL") AS 
  SELECT FECHA, PERIOD_DURATION, FINS_ID, TA_ID, MME_NAME, EPS_PATH_SWITCH_X2_SUCC, EPS_PATH_SWITCH_X2_FAIL
FROM FLNS_5011B_HISTORICAL
WHERE FECHA >= (SELECT SYSDATE - 45 FROM DUAL)
;
