--------------------------------------------------------
--  DDL for View FLNS_5035A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5035A_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "MMDU_ID", "EPS_MMDU_EMM_REG_SUM", "EPS_MMDU_EMM_REG_DENOM", "EPS_MMDU_EMM_REG_MIN", "EPS_MMDU_EMM_REG_MAX") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.MMDU_ID, FLNS.EPS_MMDU_EMM_REG_SUM,
        FLNS.EPS_MMDU_EMM_REG_DENOM, FLNS.EPS_MMDU_EMM_REG_MIN, FLNS.EPS_MMDU_EMM_REG_MAX
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, MMDU_ID,
        SUM(EPS_MMDU_EMM_REG_SUM) AS EPS_MMDU_EMM_REG_SUM,
        SUM(EPS_MMDU_EMM_REG_DENOM)  AS EPS_MMDU_EMM_REG_DENOM,
        EPS_MMDU_EMM_REG_MIN,
        EPS_MMDU_EMM_REG_MAX
  FROM PCOFNS_PS_MULM_MMDU_RAW
  GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, MMDU_ID,EPS_MMDU_EMM_REG_MIN,EPS_MMDU_EMM_REG_MAX
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
