--------------------------------------------------------
--  DDL for View FLNS_5035A_CONS_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5035A_CONS_HOUR" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "MMDU_ID", "EPS_MMDU_EMM_REG_MIN", "EPS_MMDU_EMM_REG_MAX", "FLNS_5035A") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS FECHA,
      PERIOD_DURATION, FINS_ID, MME_NAME, MMDU_ID,
      MIN(EPS_MMDU_EMM_REG_MIN) as EPS_MMDU_EMM_REG_MIN,
      MAX(EPS_MMDU_EMM_REG_MAX) as EPS_MMDU_EMM_REG_MAX,
      ROUND (DECODE (SUM(EPS_MMDU_EMM_REG_DENOM), 0 ,0, SUM(EPS_MMDU_EMM_REG_SUM) / SUM(EPS_MMDU_EMM_REG_DENOM) ), 2) AS FLNS_5035A
FROM FLNS_5035A_HISTORICAL
WHERE FECHA >= (SELECT SYSDATE - 45 FROM DUAL)
GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , PERIOD_DURATION,
          FINS_ID,  MME_NAME, MMDU_ID
;
