--------------------------------------------------------
--  DDL for View FLNS_3106A_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3106A_BH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_3106A") AS 
  SELECT hist.FECHA, hist.PERIOD_DURATION, hist.FINS_ID, hist.MME_NAME, hist.TA_ID, hist.FLNS_3106A
FROM (
    SELECT TRUNC(FECHA, 'HH24') AS FECHA, PERIOD_DURATION, FINS_ID, TA_ID,MME_NAME,
      ROUND (DECODE (AVG(PERIOD_DURATION*60), 0 ,0, SUM(FLNS_3106A) / AVG(PERIOD_DURATION*60) ) , 2) AS FLNS_3106A
    FROM FLNS_3106A_HISTORICAL
    GROUP BY TRUNC(FECHA, 'HH24'), PERIOD_DURATION,FINS_ID, TA_ID,MME_NAME
) hist
INNER JOIN PCOFNS_PS_MMMT_TA_BH_AUX aux
ON hist.FECHA = aux.FECHA
AND hist.FINS_ID = aux.FINS_ID
AND hist.TA_ID = aux.TA_ID
AND hist.MME_NAME = aux.MME_NAME
;
