--------------------------------------------------------
--  DDL for View FLNS_5001A_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5001A_MONTH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_5001A") AS 
  SELECT TRUNC( FECHA  , 'MONTH') AS FECHA, PERIOD_DURATION, FINS_ID,
      MME_NAME,TA_ID, ROUND ((DECODE (SUM(EPS_ATTACH_FAIL), 0 ,0,
              SUM(EPS_ATTACH_SUCC) / SUM(EPS_ATTACH_FAIL) ) ) * 100, 2) AS FLNS_5001A
FROM FLNS_5001A_HISTORICAL
GROUP BY   FINS_ID, TA_ID, PERIOD_DURATION,MME_NAME, TRUNC( FECHA  , 'MONTH')
;
