--------------------------------------------------------
--  DDL for View FLNS_3109B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3109B_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_3109B") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.FLNS_3109B
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID,
          sum(SGSAP_UPLINK_SUCC +
            SGSAP_UPLINK_FAIL +
            SGSAP_DOWNLINK_SUCC +
            SGSAP_DOWNLINK_FAIL) AS FLNS_3109B
    FROM PCOFNS_PS_SGSM_FLEXINS_RAW
    GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
