--------------------------------------------------------
--  DDL for View FLNS_5014A_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5014A_HOUR" ("FECHA", "PERIOD_DURATION", "FINS_ID", "TA_ID", "MME_NAME", "FLNS_5014A") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS FECHA,
		PERIOD_DURATION,FINS_ID, TA_ID, MME_NAME, ROUND ((DECODE (SUM(EPS_SERVICE_REQUEST_FAIL), 0 ,0,
              SUM(EPS_SERVICE_REQUEST_SUCC) / SUM(EPS_SERVICE_REQUEST_FAIL) ) ) * 100, 2) AS FLNS_5014A
FROM FLNS_5014A
GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , PERIOD_DURATION,
			FINS_ID, MME_NAME, TA_ID
;
