--------------------------------------------------------
--  DDL for View FLNS_3104B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3104B_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_3104B") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.TA_ID, FLNS.FLNS_3104B
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID,
          sum(EPS_PATH_SWITCH_X2_SUCC +
            EPS_X2HO_SGW_CHG_SUCC +
            EPS_PATH_SWITCH_X2_FAIL +
            EPS_S1HO_SUCC +
            INTRAMME_S1HO_SGW_CHG_SUCC +
            EPS_S1HO_FAIL +
            INTRAMME_S1HO_SGW_CHG_FAIL) AS FLNS_3104B
    FROM PCOFNS_PS_MMMT_TA_RAW
    GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
