--------------------------------------------------------
--  DDL for View FLNS_3109B_CONS_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3109B_CONS_DAY" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_3109B") AS 
  SELECT TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, PERIOD_DURATION, FINS_ID,
       MME_NAME, ROUND (DECODE (AVG(PERIOD_DURATION*60*4), 0 ,0,
              AVG(FLNS_3109B) / AVG(PERIOD_DURATION*60*4) ) , 2) AS FLNS_3109B
FROM FLNS_3109B_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR'), PERIOD_DURATION, FINS_ID, MME_NAME
;
