--------------------------------------------------------
--  DDL for View FLNS_3051A_CONS_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3051A_CONS_DAY" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "COMP_AVERAGE_LOAD", "COMP_PEAK_LOAD_PERCENT") AS 
  SELECT TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, PERIOD_DURATION, FINS_ID,
       MME_NAME, ROUND(MAX(COMP_AVERAGE_LOAD)/10, 2) AS COMP_AVERAGE_LOAD, MAX(COMP_PEAK_LOAD_PERCENT) AS COMP_PEAK_LOAD_PERCENT
FROM FLNS_3051A_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR'), PERIOD_DURATION, FINS_ID, MME_NAME
;
