--------------------------------------------------------
--  DDL for View FLNS_5001A_CONS_BH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5001A_CONS_BH" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_5001A") AS 
  SELECT hist.FECHA, hist.PERIOD_DURATION, hist.FINS_ID, hist.MME_NAME, hist.FLNS_5001A
FROM (
    SELECT TRUNC(FECHA, 'HH24') AS FECHA, PERIOD_DURATION, FINS_ID, MME_NAME,
      ROUND ((DECODE (SUM(EPS_ATTACH_FAIL), 0 ,0, SUM(EPS_ATTACH_SUCC) / SUM(EPS_ATTACH_FAIL) ) ) * 100, 2) AS FLNS_5001A
    FROM FLNS_5001A_HISTORICAL
    GROUP BY TRUNC(FECHA, 'HH24') , PERIOD_DURATION, FINS_ID, MME_NAME
) hist
INNER JOIN PCOFNS_PS_MMMT_TA_CONS_BH_AUX aux
ON hist.FECHA = aux.FECHA
AND hist.FINS_ID = aux.FINS_ID
AND hist.MME_NAME = aux.MME_NAME
;
