--------------------------------------------------------
--  DDL for View FLNS_5001A_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5001A_DAY" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_5001A") AS 
  SELECT TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, PERIOD_DURATION, FINS_ID,
       MME_NAME,TA_ID, ROUND ((DECODE (SUM(EPS_ATTACH_FAIL), 0 ,0,
              SUM(EPS_ATTACH_SUCC) / SUM(EPS_ATTACH_FAIL) ) ) * 100, 2) AS FLNS_5001A
FROM FLNS_5001A_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR'), PERIOD_DURATION, FINS_ID, TA_ID,MME_NAME
;
