--------------------------------------------------------
--  DDL for View FLNS_5029B_CONS_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5029B_CONS_DAY" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "FLNS_5029B") AS 
  SELECT TO_DATE(SUBSTR(FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA,
       PERIOD_DURATION,FINS_ID,MME_NAME,
       ROUND(DECODE(SUM(EPS_ECM_CONN_DENOM), 0, 0, SUM(EPS_ECM_CONN_SUM) / SUM(EPS_ECM_CONN_DENOM)), 2) AS FLNS_5029B
  FROM FLNS_5029B_HISTORICAL
 GROUP BY TO_DATE(SUBSTR(FECHA, 0, 10), 'DD/MM/RRRR'), PERIOD_DURATION, FINS_ID, MME_NAME
;
