--------------------------------------------------------
--  DDL for View FLNS_5005A
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5005A" ("FECHA", "PERIOD_DURATION", "FINS_ID", "TA_ID", "MME_NAME", "EPS_PERIODIC_TAU_SUCC", "EPS_PERIODIC_TAU_FAIL") AS 
  SELECT FECHA, PERIOD_DURATION, FINS_ID, TA_ID, MME_NAME, EPS_PERIODIC_TAU_SUCC, EPS_PERIODIC_TAU_FAIL
FROM FLNS_5005A_HISTORICAL
WHERE FECHA >= (SELECT SYSDATE - 45 FROM DUAL)
;
