--------------------------------------------------------
--  DDL for View FLNS_3113A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_3113A_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "TA_ID", "FLNS_3113A") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA, FLNS.PERIOD_DURATION, FLNS.FINS_ID, MO.MME_NAME, FLNS.TA_ID, FLNS.FLNS_3113A
FROM (
    SELECT PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID,
          sum(INTERMME_TAU_WO_SGW_CHG_SUCC +
          INTERMME_TAU_IN_FAIL +
          INTERMME_TAU_OUT_SUCC +
          INTERMME_TAU_OUT_FAIL) AS FLNS_3113A
    FROM PCOFNS_PS_MMMT_TA_RAW
    GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID, TA_ID
) FLNS
INNER JOIN (
    SELECT SGSN_NAME AS MME_NAME,SGSN_ID FROM VW_SGSN_OBJECTS
    WHERE VALID_FINISH_DATE > SYSDATE
) MO
ON  MO.SGSN_ID = FLNS.FINS_ID
;
