--------------------------------------------------------
--  DDL for View FLNS_5032B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."FLNS_5032B_HISTORICAL" ("FECHA", "PERIOD_DURATION", "FINS_ID", "MME_NAME", "EPS_ECM_IDLE_SUM", "EPS_ECM_IDLE_DENOM") AS 
  SELECT FLNS.PERIOD_START_TIME AS FECHA,
       FLNS.PERIOD_DURATION,
       FLNS.FINS_ID,
       MO.MME_NAME,
       FLNS.EPS_ECM_IDLE_SUM,
       FLNS.EPS_ECM_IDLE_DENOM
  FROM (SELECT PERIOD_START_TIME,
               PERIOD_DURATION,
               FINS_ID,
               SUM(EPS_ECM_IDLE_SUM) AS EPS_ECM_IDLE_SUM,
               AVG(EPS_ECM_IDLE_DENOM) AS EPS_ECM_IDLE_DENOM
          FROM PCOFNS_PS_UMLM_FLEXINS_RAW
         GROUP BY PERIOD_START_TIME, PERIOD_DURATION, FINS_ID) FLNS
 INNER JOIN (SELECT SGSN_NAME AS MME_NAME, SGSN_ID
               FROM VW_SGSN_OBJECTS
              WHERE VALID_FINISH_DATE > SYSDATE AND ORDEN = '1') MO
    ON MO.SGSN_ID = FLNS.FINS_ID
;
