--------------------------------------------------------
--  DDL for View L71301_L71303_BH_AUX
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."L71301_L71303_BH_AUX" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "VALUE") AS 
  SELECT FECHA, GWNAME, SERVID, SERVNAME, VALUE
FROM (
    SELECT B.FECHA, A.GWNAME, A.SERVID, A.SERVNAME, A.VALUE,
    ROW_NUMBER() OVER (
                    PARTITION BY A.FECHA, A.GWNAME, A.SERVID, A.SERVNAME
                    ORDER BY A.VALUE DESC
            ) SEQNUM2
    FROM (
        SELECT FECHA, GWNAME, SERVID, SERVNAME, MAX(VALUE) AS VALUE, SEQNUM
        FROM(
            SELECT TO_DATE( SUBSTR( SDB.FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, SDB.GWNAME, SDB.SERVID, SDB.SERVNAME, (STUB.UPLINK_THROUGHPUT + SDB.DOWNLINK_THROUGHPUT) AS VALUE,
                ROW_NUMBER() OVER (
                    PARTITION BY SDB.GWNAME, SDB.SERVID, SDB.SERVNAME
                    ORDER BY SDB.FECHA
                ) SEQNUM
            FROM (
                    SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA , 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI')  AS FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(UPLINK_THROUGHPUT), 2) AS UPLINK_THROUGHPUT
                    FROM L71301_HISTORICAL_MV
                    GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , SERVID, GWNAME, SERVNAME
                ) STUB
                INNER JOIN (
                  SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI')  AS FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(DOWNLINK_THROUGHPUT), 2) AS DOWNLINK_THROUGHPUT
                  FROM L71303_HISTORICAL_MV
                  GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , SERVID, GWNAME, SERVNAME
                ) SDB
                ON  STUB.FECHA = SDB.FECHA
                AND STUB.SERVID = SDB.SERVID
            )
        GROUP BY FECHA, GWNAME, SERVID, SERVNAME, SEQNUM
    ) A
    INNER JOIN (
        SELECT SDB.FECHA, SDB.GWNAME, SDB.SERVID, SDB.SERVNAME, (STUB.UPLINK_THROUGHPUT + SDB.DOWNLINK_THROUGHPUT) AS VALUE,
            ROW_NUMBER() OVER (
                        PARTITION BY SDB.GWNAME, SDB.SERVID, SDB.SERVNAME
                        ORDER BY SDB.FECHA
                ) SEQNUM
        FROM (
            SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA , 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI')  AS FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(UPLINK_THROUGHPUT), 2) AS UPLINK_THROUGHPUT
            FROM L71301_HISTORICAL_MV
            GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , SERVID, GWNAME, SERVNAME
        ) STUB
        INNER JOIN (
            SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI')  AS FECHA, GWNAME, SERVID, SERVNAME, ROUND (AVG(DOWNLINK_THROUGHPUT), 2) AS DOWNLINK_THROUGHPUT
            FROM L71303_HISTORICAL_MV
            GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , SERVID, GWNAME, SERVNAME
        ) SDB
        ON  STUB.FECHA = SDB.FECHA
        AND STUB.SERVID = SDB.SERVID
    ) B
    ON A.VALUE = B.VALUE
    AND A.GWNAME = B.GWNAME
    AND A.SERVNAME = B.SERVNAME
    AND A.SERVID = B.SERVID
    WHERE A.SEQNUM = B.SEQNUM
)
WHERE SEQNUM2= 1
;
