--------------------------------------------------------
--  DDL for View L81505_L81513_BH_AUX
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."L81505_L81513_BH_AUX" ("FECHA", "GWNAME", "SERVID", "SERVNAME", "VALUE") AS 
  SELECT FECHA, GWNAME, SERVID, SERVNAME, VALUE
FROM (
    SELECT B.FECHA, A.GWNAME, A.SERVID, A.SERVNAME, A.VALUE,
    ROW_NUMBER() OVER (
                    PARTITION BY A.FECHA, A.GWNAME, A.SERVID, A.SERVNAME
                    ORDER BY A.FECHA DESC
            ) SEQNUM2
    FROM (
        SELECT FECHA, GWNAME, SERVID, SERVNAME, MAX(VALUE) AS VALUE, SEQNUM
        FROM(
            SELECT TO_DATE( SUBSTR( SDB.FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA, SDB.GWNAME, SDB.SERVID, SDB.SERVNAME, (STUB.UPLINK_THP_MBPS + SDB.DOWNLINK_THP_MBPS_GBR) AS VALUE,
                ROW_NUMBER() OVER (
                    PARTITION BY SDB.GWNAME, SDB.SERVID, SDB.SERVNAME
                    ORDER BY SDB.FECHA
                ) SEQNUM
            FROM (
                    SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA , 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI')  AS FECHA, GWNAME, SERVID, SERVNAME, SUM(UPLINK_THP_MBPS) AS UPLINK_THP_MBPS
                    FROM L81505_HISTORICAL_MV
                    GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , SERVID, GWNAME, SERVNAME
                ) STUB
                INNER JOIN (
                  SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI')  AS FECHA, GWNAME, SERVID, SERVNAME, SUM(DOWNLINK_THP_MBPS_GBR) AS DOWNLINK_THP_MBPS_GBR
                  FROM L81513_HISTORICAL_MV
                  GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , SERVID, GWNAME, SERVNAME
                ) SDB
                ON  STUB.FECHA = SDB.FECHA
                AND STUB.SERVID = SDB.SERVID
            )
        GROUP BY FECHA, GWNAME, SERVID, SERVNAME, SEQNUM
    ) A
    INNER JOIN (
        SELECT SDB.FECHA, SDB.GWNAME, SDB.SERVID, SDB.SERVNAME, (STUB.UPLINK_THP_MBPS + SDB.DOWNLINK_THP_MBPS_GBR) AS VALUE,
            ROW_NUMBER() OVER (
                        PARTITION BY SDB.GWNAME, SDB.SERVID, SDB.SERVNAME
                        ORDER BY SDB.FECHA
                ) SEQNUM
        FROM (
            SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA , 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI')  AS FECHA, GWNAME, SERVID, SERVNAME, SUM(UPLINK_THP_MBPS) AS UPLINK_THP_MBPS
            FROM L81505_HISTORICAL_MV
            GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , SERVID, GWNAME, SERVNAME
        ) STUB
        INNER JOIN (
            SELECT TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI')  AS FECHA, GWNAME, SERVID, SERVNAME, SUM(DOWNLINK_THP_MBPS_GBR) AS DOWNLINK_THP_MBPS_GBR
            FROM L81513_HISTORICAL_MV
            GROUP BY TO_DATE(SUBSTR( TO_CHAR( FECHA, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , SERVID, GWNAME, SERVNAME
        ) SDB
        ON  STUB.FECHA = SDB.FECHA
        AND STUB.SERVID = SDB.SERVID
    ) B
    ON A.VALUE = B.VALUE
    AND A.GWNAME = B.GWNAME
    AND A.SERVNAME = B.SERVNAME
    AND A.SERVID = B.SERVID
    WHERE A.SEQNUM = B.SEQNUM
)
WHERE SEQNUM2= 1
;
