--------------------------------------------------------
--  DDL for View LTE_5017A_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5017A_WEEK" ("FECHA", "CO_NAME", "INT_ID", "LTE_5017A_NUM", "LTE_5017A_DEN", "LTE_5017A", "EPS_BEARER_SETUP_COMPLETIONS", "EPS_BEARER_SETUP_ATTEMPTS") AS 
  SELECT TRUNC( FECHA  , 'DAY') AS FECHA,
		CO_NAME, INT_ID,
		SUM(LTE_5017A_NUM) AS LTE_5017A_NUM,
		SUM(LTE_5017A_DEN) AS LTE_5017A_DEN,
		ROUND (((DECODE (SUM(LTE_5017A_DEN), 0, 0, SUM(LTE_5017A_NUM) /   SUM(LTE_5017A_DEN)) )*100),2) as LTE_5017A,
		SUM(EPS_BEARER_SETUP_COMPLETIONS) AS EPS_BEARER_SETUP_COMPLETIONS,
		SUM(EPS_BEARER_SETUP_ATTEMPTS) AS EPS_BEARER_SETUP_ATTEMPTS
FROM LTE_5017A_HISTORICAL
GROUP BY TRUNC( FECHA  , 'DAY'), CO_NAME,INT_ID
;
