--------------------------------------------------------
--  DDL for View LTE_5003A_DAY_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5003A_DAY_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "DATA_RB_STP_COMP", "DATA_RB_STP_ATT") AS 
  SELECT TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR') AS PERIOD_START_TIME, CO_NAME, SUM(DATA_RB_STP_COMP) AS DATA_RB_STP_COMP,
SUM(DATA_RB_STP_ATT) AS DATA_RB_STP_ATT
FROM NOKLTE_PS_LRDB_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
GROUP BY  TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR'), CO_NAME
;
