--------------------------------------------------------
--  DDL for View LTE_5544B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5544B_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5544B_NUM", "LTE_5544B_DEN", "SINR_PUCCH_LEVEL_1", "SINR_PUCCH_LEVEL_2", "SINR_PUCCH_LEVEL_3", "SINR_PUCCH_LEVEL_4", "SINR_PUCCH_LEVEL_5", "SINR_PUCCH_LEVEL_6", "SINR_PUCCH_LEVEL_7", "SINR_PUCCH_LEVEL_8", "SINR_PUCCH_LEVEL_9", "SINR_PUCCH_LEVEL_10", "SINR_PUCCH_LEVEL_11", "SINR_PUCCH_LEVEL_12", "SINR_PUCCH_LEVEL_13", "SINR_PUCCH_LEVEL_14", "SINR_PUCCH_LEVEL_15", "SINR_PUCCH_LEVEL_16", "SINR_PUCCH_LEVEL_17", "SINR_PUCCH_LEVEL_18", "SINR_PUCCH_LEVEL_19", "SINR_PUCCH_LEVEL_20", "SINR_PUCCH_LEVEL_21", "SINR_PUCCH_LEVEL_22") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
	(-10*SINR_PUSCH_LEVEL_1
    -9*SINR_PUSCH_LEVEL_2
    -7*SINR_PUSCH_LEVEL_3
    -5*SINR_PUSCH_LEVEL_4
    -3*SINR_PUSCH_LEVEL_5
    -1*SINR_PUSCH_LEVEL_6
    +1*SINR_PUSCH_LEVEL_7
    +3*SINR_PUSCH_LEVEL_8
    +5*SINR_PUSCH_LEVEL_9
    +7*SINR_PUSCH_LEVEL_10
    +9*SINR_PUSCH_LEVEL_11
    +11*SINR_PUSCH_LEVEL_12
    +13*SINR_PUSCH_LEVEL_13
    +15*SINR_PUSCH_LEVEL_14
    +17*SINR_PUSCH_LEVEL_15
    +19*SINR_PUSCH_LEVEL_16
    +21*SINR_PUSCH_LEVEL_17
    +23*SINR_PUSCH_LEVEL_18
    +25*SINR_PUSCH_LEVEL_19
    +27*SINR_PUSCH_LEVEL_20
    +29*SINR_PUSCH_LEVEL_21
    +30*SINR_PUSCH_LEVEL_22) AS  LTE_5544B_NUM,
    (SINR_PUSCH_LEVEL_1+
    SINR_PUSCH_LEVEL_2+
    SINR_PUSCH_LEVEL_3+
    SINR_PUSCH_LEVEL_4+
    SINR_PUSCH_LEVEL_5+
    SINR_PUSCH_LEVEL_6+
    SINR_PUSCH_LEVEL_7+
    SINR_PUSCH_LEVEL_8+
    SINR_PUSCH_LEVEL_9+
    SINR_PUSCH_LEVEL_10+
    SINR_PUSCH_LEVEL_11+
    SINR_PUSCH_LEVEL_12+
    SINR_PUSCH_LEVEL_13+
    SINR_PUSCH_LEVEL_14+
    SINR_PUSCH_LEVEL_15+
    SINR_PUSCH_LEVEL_16+
    SINR_PUSCH_LEVEL_17+
    SINR_PUSCH_LEVEL_18+
    SINR_PUSCH_LEVEL_19+
    SINR_PUSCH_LEVEL_20+
    SINR_PUSCH_LEVEL_21+
    SINR_PUSCH_LEVEL_22) AS LTE_5544B_DEN,
    SINR_PUCCH_LEVEL_1,
    SINR_PUCCH_LEVEL_2,
    SINR_PUCCH_LEVEL_3,
    SINR_PUCCH_LEVEL_4,
    SINR_PUCCH_LEVEL_5,
    SINR_PUCCH_LEVEL_6,
    SINR_PUCCH_LEVEL_7,
    SINR_PUCCH_LEVEL_8,
    SINR_PUCCH_LEVEL_9,
    SINR_PUCCH_LEVEL_10,
    SINR_PUCCH_LEVEL_11,
    SINR_PUCCH_LEVEL_12,
    SINR_PUCCH_LEVEL_13,
    SINR_PUCCH_LEVEL_14,
    SINR_PUCCH_LEVEL_15,
    SINR_PUCCH_LEVEL_16,
    SINR_PUCCH_LEVEL_17,
    SINR_PUCCH_LEVEL_18,
    SINR_PUCCH_LEVEL_19,
    SINR_PUCCH_LEVEL_20,
    SINR_PUCCH_LEVEL_21,
    SINR_PUCCH_LEVEL_22
FROM NOKLTE_PS_LPQUL_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
