--------------------------------------------------------
--  DDL for View LTE_5082A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5082A_HISTORICAL" ("PERIOD_START_TIME", "CO_NAME", "LTE_5082A_NUM", "LTE_5082A_DEN") AS 
  SELECT T1.PERIOD_START_TIME, O1.CO_NAME,
		INTER_ENB_S1_HO_SUCC AS  LTE_5082A_NUM,
		INTER_ENB_S1_HO_ATT AS LTE_5082A_DEN
FROM NOKLTE_PS_LIENBHO_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
;
