--------------------------------------------------------
--  DDL for View LTE_5035A_HOUR_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5035A_HOUR_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "SUCC_INTRA_ENB_HO", "ATT_INTRA_ENB_HO") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS PERIOD_START_TIME,CO_NAME,
SUM(SUCC_INTRA_ENB_HO) AS SUCC_INTRA_ENB_HO,
SUM(ATT_INTRA_ENB_HO) AS ATT_INTRA_ENB_HO
FROM NOKLTE_PS_LIANBHO_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
AND PERIOD_START_TIME >= (SELECT SYSDATE - 45 FROM DUAL)
GROUP BY TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , CO_NAME
;
