--------------------------------------------------------
--  Constraints for Table LTE_NSN_AVAIL_NE_DAY
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."LTE_NSN_AVAIL_NE_DAY" ADD CONSTRAINT "LTE_NSN_AVAIL_NE_DAY_PK" PRIMARY KEY ("FECHA", "ELEMENT_CLASS", "ELEMENT_ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_AVAIL_NE_DAY" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_AVAIL_NE_DAY" MODIFY ("ELEMENT_CLASS" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_AVAIL_NE_DAY" MODIFY ("ELEMENT_ID" NOT NULL ENABLE);
