--------------------------------------------------------
--  DDL for View LTE_5082A_HOUR_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5082A_HOUR_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "INTER_ENB_S1_HO_SUCC", "INTER_ENB_S1_HO_ATT") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS PERIOD_START_TIME, CO_NAME,
SUM(INTER_ENB_S1_HO_SUCC) AS INTER_ENB_S1_HO_SUCC,
SUM(INTER_ENB_S1_HO_ATT) AS INTER_ENB_S1_HO_ATT
FROM NOKLTE_PS_LIENBHO_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
AND PERIOD_START_TIME >= (SELECT SYSDATE - 45 FROM DUAL)
GROUP BY TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , CO_NAME
;
