--------------------------------------------------------
--  DDL for Index LTE_NSN_AVAIL_LCEL_DAYM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HARRIAGUE"."LTE_NSN_AVAIL_LCEL_DAYM_PK" ON "HARRIAGUE"."LTE_NSN_AVAIL_LCEL_DAYM" ("FECHA", "LNCEL_ID") 
   LOCAL
 (PARTITION "LTE_NSN_SERVICE_201506" , 
 PARTITION "LTE_NSN_SERVICE_201507" , 
 PARTITION "LTE_NSN_SERVICE_201508" , 
 PARTITION "LTE_NSN_SERVICE_201509" , 
 PARTITION "LTE_NSN_SERVICE_201510" , 
 PARTITION "LTE_NSN_SERVICE_201511" , 
 PARTITION "LTE_NSN_SERVICE_201512" , 
 PARTITION "LTE_NSN_SERVICE_201601" , 
 PARTITION "LTE_NSN_SERVICE_201602" , 
 PARTITION "LTE_NSN_SERVICE_201603" , 
 PARTITION "LTE_NSN_201604" , 
 PARTITION "LTE_NSN_201605" , 
 PARTITION "LTE_NSN_201606" ) ;
