--------------------------------------------------------
--  DDL for View LTE_5014A_HOUR_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5014A_HOUR_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "S1_SETUP_SUCC", "S1_SETUP_ATT") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS PERIOD_START_TIME, CO_NAME,
SUM(S1_SETUP_SUCC) AS S1_SETUP_SUCC, SUM(S1_SETUP_ATT) AS S1_SETUP_ATT
FROM NOKLTE_PS_LS1AP_LNBTS_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNBTS_ID = O1.CO_GID
AND CO_OC_ID = 3129
AND CO_STATE = 0
AND PERIOD_START_TIME >= (SELECT SYSDATE - 45 FROM DUAL)
GROUP BY TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI'), CO_NAME
;
