--------------------------------------------------------
--  DDL for View LTE_5803A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5803A_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "UL_UE_DATA_BUFF_MAX") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
		UL_UE_DATA_BUFF_MAX
FROM NOKLTE_PS_LCELLD_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
