--------------------------------------------------------
--  DDL for View LTE_5035A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5035A_HISTORICAL" ("PERIOD_START_TIME", "CO_NAME", "LTE_5035A_NUM", "LTE_5035A_DEN") AS 
  SELECT T1.PERIOD_START_TIME, O1.CO_NAME,
		SUCC_INTRA_ENB_HO AS  LTE_5035A_NUM,
		ATT_INTRA_ENB_HO AS LTE_5035A_DEN
FROM NOKLTE_PS_LIANBHO_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
;
