--------------------------------------------------------
--  Constraints for Table LTE_NSN_PAQ_LCEL_DAYM
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."LTE_NSN_PAQ_LCEL_DAYM" ADD CONSTRAINT "LTE_NSN_PAQ_LCEL_DAYM_PK" PRIMARY KEY ("FECHA", "LNCEL_ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_PAQ_LCEL_DAYM" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_PAQ_LCEL_DAYM" MODIFY ("LNCEL_ID" NOT NULL ENABLE);
