--------------------------------------------------------
--  Constraints for Table LTE_NSN_PAQ_NE_HOUR
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."LTE_NSN_PAQ_NE_HOUR" ADD CONSTRAINT "LTE_NSN_PAQ_NE_HOUR_PK" PRIMARY KEY ("FECHA", "ELEMENT_CLASS", "ELEMENT_ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_PAQ_NE_HOUR" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_PAQ_NE_HOUR" MODIFY ("ELEMENT_CLASS" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_PAQ_NE_HOUR" MODIFY ("ELEMENT_ID" NOT NULL ENABLE);
