--------------------------------------------------------
--  DDL for View LTE_5115A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5115A_HISTORICAL" ("PERIOD_START_TIME", "CO_NAME", "LTE_5115A_NUM", "LTE_5115A_DEN") AS 
  SELECT T1.PERIOD_START_TIME, O1.CO_NAME,
		HO_INTFREQ_GAP_SUCC AS  LTE_5115A_NUM,
		HO_INTFREQ_GAP_ATT AS LTE_5115A_DEN
FROM NOKLTE_PS_LHO_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
;
