--------------------------------------------------------
--  DDL for View LTE_5025D_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5025D_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5025D_NUM", "LTE_5025D_DEN", "EPC_EPS_BEARER_REL_REQ_NORM", "EPC_EPS_BEARER_REL_REQ_DETACH", "EPC_EPS_BEARER_REL_REQ_RNL", "EPC_EPS_BEARER_REL_REQ_OTH", "ENB_EPSBEAR_REL_REQ_RNL_REDIR", "ENB_EPS_BEARER_REL_REQ_RNL", "ENB_EPS_BEARER_REL_REQ_TNL", "ENB_EPS_BEARER_REL_REQ_OTH", "PRE_EMPT_GBR_BEARER", "PRE_EMPT_NON_GBR_BEARER") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
		(ENB_EPS_BEARER_REL_REQ_RNL+
		ENB_EPS_BEARER_REL_REQ_TNL+
		ENB_EPS_BEARER_REL_REQ_OTH) AS  LTE_5025D_NUM,
		(EPC_EPS_BEARER_REL_REQ_NORM+
		EPC_EPS_BEARER_REL_REQ_DETACH+
		EPC_EPS_BEARER_REL_REQ_RNL+
		EPC_EPS_BEARER_REL_REQ_OTH+
		ENB_EPSBEAR_REL_REQ_RNL_REDIR+
		ENB_EPS_BEARER_REL_REQ_RNL+
		ENB_EPS_BEARER_REL_REQ_TNL+
		ENB_EPS_BEARER_REL_REQ_OTH+
		PRE_EMPT_GBR_BEARER+
		PRE_EMPT_NON_GBR_BEARER) AS LTE_5025D_DEN,
		EPC_EPS_BEARER_REL_REQ_NORM,
		EPC_EPS_BEARER_REL_REQ_DETACH,
		EPC_EPS_BEARER_REL_REQ_RNL,
		EPC_EPS_BEARER_REL_REQ_OTH,
		ENB_EPSBEAR_REL_REQ_RNL_REDIR,
		ENB_EPS_BEARER_REL_REQ_RNL,
		ENB_EPS_BEARER_REL_REQ_TNL,
		ENB_EPS_BEARER_REL_REQ_OTH,
		PRE_EMPT_GBR_BEARER,
		PRE_EMPT_NON_GBR_BEARER
FROM NOKLTE_PS_LEPSB_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
