--------------------------------------------------------
--  DDL for View LTE_5292B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5292B_HISTORICAL" ("PERIOD_START_TIME", "CO_NAME", "PDCP_DATA_RATE_MEAN_DL") AS 
  SELECT T1.PERIOD_START_TIME, O1.CO_NAME, PDCP_DATA_RATE_MEAN_DL
FROM NOKLTE_PS_LCELLT_MNC1_RAW@OSSRC3 T1,
     UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
;
