--------------------------------------------------------
--  DDL for View LTE_5025A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5025A_HISTORICAL" ("PERIOD_START_TIME", "CO_NAME", "LTE_5025A_NUM", "LTE_5025A_DEN") AS 
  SELECT T1.PERIOD_START_TIME, O1.CO_NAME,
    SUM(ENB_EPS_BEARER_REL_REQ_RNL+ ENB_EPS_BEARER_REL_REQ_TNL+ ENB_EPS_BEARER_REL_REQ_OTH) AS  LTE_5025A_NUM,
    SUM(EPC_EPS_BEARER_REL_REQ_NORM+ EPC_EPS_BEARER_REL_REQ_DETACH+EPC_EPS_BEARER_REL_REQ_RNL+EPC_EPS_BEARER_REL_REQ_OTH) AS LTE_5025A_DEN
FROM NOKLTE_PS_LEPSB_MNC1_RAW@OSSRC3.WORLD T1,
     UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
GROUP BY T1.PERIOD_START_TIME, O1.CO_NAME
;
