--------------------------------------------------------
--  DDL for View LTE_5014A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5014A_HISTORICAL" ("PERIOD_START_TIME", "CO_NAME", "LTE_5014A_NUM", "LTE_5014A_DEN") AS 
  SELECT T1.PERIOD_START_TIME, O1.CO_NAME,
		S1_SETUP_SUCC AS  LTE_5014A_NUM,
		S1_SETUP_ATT AS LTE_5014A_DEN
FROM NOKLTE_PS_LS1AP_LNBTS_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNBTS_ID = O1.CO_GID
AND CO_OC_ID = 3129
AND CO_STATE = 0
;
