--------------------------------------------------------
--  DDL for View LTE_5048B_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5048B_WEEK" ("PERIOD_START_TIME", "CO_NAME", "LTE_5048B_NUM", "LTE_5048B_DEN", "LTE_5048B") AS 
  SELECT TRUNC( PERIOD_START_TIME  , 'DAY') AS PERIOD_START_TIME, CO_NAME,
SUM(LTE_5048B_NUM) AS LTE_5048B_NUM,
SUM(LTE_5048B_DEN) AS LTE_5048B_DEN,
ROUND (((DECODE (SUM(LTE_5048B_DEN), 0, 0, SUM(LTE_5048B_NUM) /
  SUM(LTE_5048B_DEN)) )*100),2) as LTE_5048B
FROM LTE_5048B_HISTORICAL
GROUP BY TRUNC( PERIOD_START_TIME  , 'DAY'), CO_NAME
;
