--------------------------------------------------------
--  DDL for View LTE_5014A_DAY_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5014A_DAY_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "S1_SETUP_SUCC", "S1_SETUP_ATT") AS 
  SELECT TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR') AS PERIOD_START_TIME, CO_NAME, SUM(S1_SETUP_SUCC) AS S1_SETUP_SUCC,
SUM(S1_SETUP_ATT) AS S1_SETUP_ATT
FROM NOKLTE_PS_LS1AP_LNBTS_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNBTS_ID = O1.CO_GID
AND CO_OC_ID = 3129
AND CO_STATE = 0
GROUP BY  TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR'), CO_NAME
;
