--------------------------------------------------------
--  Constraints for Table LTE_NSN_AVAIL_NE_IBHW
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."LTE_NSN_AVAIL_NE_IBHW" ADD CONSTRAINT "LTE_NSN_AVAIL_NE_IBHW_PK" PRIMARY KEY ("FECHA", "ELEMENT_CLASS", "ELEMENT_ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_AVAIL_NE_IBHW" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_AVAIL_NE_IBHW" MODIFY ("ELEMENT_CLASS" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_AVAIL_NE_IBHW" MODIFY ("ELEMENT_ID" NOT NULL ENABLE);
