--------------------------------------------------------
--  DDL for View LTE_5289B_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5289B_DAY" ("PERIOD_START_TIME", "CO_NAME", "LTE_5289B") AS 
  SELECT TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR') AS PERIOD_START_TIME, CO_NAME,
		ROUND(AVG(PDCP_DATA_RATE_MEAN_UL),2) AS LTE_5289B
FROM LTE_5289B_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR'), CO_NAME
;
