--------------------------------------------------------
--  DDL for View LTE_NSN_BH_AUX_LNCEL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_NSN_BH_AUX_LNCEL" ("FECHA", "CO_NAME", "INT_ID", "VALUE") AS 
  SELECT FECHA , CO_NAME, INT_ID, VALUE
FROM (
SELECT B.FECHA , A.CO_NAME, A.INT_ID,  A.VALUE,
    ROW_NUMBER() OVER (
                    PARTITION BY A.FECHA , A.CO_NAME, A.INT_ID
                    ORDER BY A.VALUE DESC
            ) SEQNUM2
FROM (
    SELECT TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') AS FECHA,
             CO_NAME, INT_ID, MAX(PDCP_SDU_VOL_DL) AS VALUE, SEQNUM
    FROM (
      SELECT FECHA,CO_NAME, INT_ID, PDCP_SDU_VOL_DL,
        ROW_NUMBER() OVER (
                        PARTITION BY CO_NAME, INT_ID
                        ORDER BY FECHA
                ) SEQNUM
      FROM (
          SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS FECHA,
              CO_NAME, INT_ID, SUM(PDCP_SDU_VOL_DL) AS PDCP_SDU_VOL_DL
          FROM NOKLTE_PS_LCELLT_MNC1_RAW
          GROUP BY TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , CO_NAME, INT_ID
        )
    )
    GROUP BY TO_DATE( SUBSTR( FECHA, 0, 10), 'DD/MM/RRRR') , CO_NAME, INT_ID, SEQNUM
) A
INNER JOIN (
  SELECT FECHA,CO_NAME, INT_ID, PDCP_SDU_VOL_DL,
        ROW_NUMBER() OVER (
                        PARTITION BY CO_NAME, INT_ID
                        ORDER BY FECHA
                ) SEQNUM
  FROM (
      SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS FECHA,
              CO_NAME, INT_ID, SUM(PDCP_SDU_VOL_DL) AS PDCP_SDU_VOL_DL
      FROM NOKLTE_PS_LCELLT_MNC1_RAW
      GROUP BY TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , CO_NAME, INT_ID
    )
) B
ON A.CO_NAME = B.CO_NAME
AND A.INT_ID = B.INT_ID
AND A.SEQNUM = B.SEQNUM
)
WHERE SEQNUM2= 1
;
