--------------------------------------------------------
--  DDL for View LTE_5218C_WEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5218C_WEEK" ("FECHA", "CO_NAME", "LTE_5218C_NUM", "LTE_5218C_DEN", "LTE_5218C", "SIGN_CONN_ESTAB_COMP", "SIGN_CONN_ESTAB_ATT_MO_S", "SIGN_CONN_ESTAB_ATT_MT", "SIGN_CONN_ESTAB_ATT_MO_D", "SIGN_CONN_ESTAB_ATT_OTHERS", "SIGN_CONN_ESTAB_ATT_EMG") AS 
  SELECT TRUNC( FECHA  , 'DAY') AS FECHA,
    CO_NAME,
    SUM(LTE_5218C_NUM) AS LTE_5218C_NUM,
    SUM(LTE_5218C_DEN) AS LTE_5218C_DEN,
    ROUND (((DECODE (SUM(LTE_5218C_DEN), 0, 0, SUM(LTE_5218C_NUM) / SUM(LTE_5218C_DEN)) )*100),2) as LTE_5218C,
    SUM(SIGN_CONN_ESTAB_COMP) AS  SIGN_CONN_ESTAB_COMP,
    SUM(SIGN_CONN_ESTAB_ATT_MO_S) AS SIGN_CONN_ESTAB_ATT_MO_S,
    SUM(SIGN_CONN_ESTAB_ATT_MT) AS SIGN_CONN_ESTAB_ATT_MT,
    SUM(SIGN_CONN_ESTAB_ATT_MO_D) AS SIGN_CONN_ESTAB_ATT_MO_D,
    SUM(SIGN_CONN_ESTAB_ATT_OTHERS) AS SIGN_CONN_ESTAB_ATT_OTHERS,
    SUM(SIGN_CONN_ESTAB_ATT_EMG) AS SIGN_CONN_ESTAB_ATT_EMG
FROM LTE_5218C_HISTORICAL
GROUP BY TRUNC( FECHA  , 'DAY'), INT_ID, CO_NAME
;
