--------------------------------------------------------
--  DDL for View LTE_5060E_DAY_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5060E_DAY_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "SIGN_CONN_ESTAB_COMP", "SIGN_CONN_ESTAB_ATT_MO_S", "SIGN_CONN_ESTAB_ATT_MT", "SIGN_CONN_ESTAB_ATT_MO_D", "SIGN_CONN_ESTAB_ATT_OTHERS", "SIGN_CONN_ESTAB_ATT_EMG", "EPS_BEARER_STP_COM_INI_QCI1", "EPS_BEARER_STP_COM_INI_QCI_2", "EPS_BEARER_STP_COM_INI_QCI_3", "EPS_BEARER_STP_COM_INI_QCI_4", "EPS_BEAR_STP_COM_INI_NON_GBR", "EPS_BEARER_STP_ATT_INI_QCI_1", "EPS_BEARER_STP_ATT_INI_QCI_2", "EPS_BEARER_STP_ATT_INI_QCI_3", "EPS_BEARER_STP_ATT_INI_QCI_4", "EPS_BEAR_STP_ATT_INI_NON_GBR") AS 
  SELECT TO_DATE( SUBSTR( T1.PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR') AS PERIOD_START_TIME, O1.CO_NAME,
  SUM(SIGN_CONN_ESTAB_COMP) AS  SIGN_CONN_ESTAB_COMP,
  SUM(SIGN_CONN_ESTAB_ATT_MO_S) AS  SIGN_CONN_ESTAB_ATT_MO_S,
  SUM(SIGN_CONN_ESTAB_ATT_MT) AS  SIGN_CONN_ESTAB_ATT_MT,
  SUM(SIGN_CONN_ESTAB_ATT_MO_D) AS  SIGN_CONN_ESTAB_ATT_MO_D,
  SUM(SIGN_CONN_ESTAB_ATT_OTHERS) AS  SIGN_CONN_ESTAB_ATT_OTHERS,
  SUM(SIGN_CONN_ESTAB_ATT_EMG) AS  SIGN_CONN_ESTAB_ATT_EMG,
  SUM(EPS_BEARER_STP_COM_INI_QCI1) AS  EPS_BEARER_STP_COM_INI_QCI1,
  SUM(EPS_BEARER_STP_COM_INI_QCI_2) AS  EPS_BEARER_STP_COM_INI_QCI_2,
  SUM(EPS_BEARER_STP_COM_INI_QCI_3) AS  EPS_BEARER_STP_COM_INI_QCI_3,
  SUM(EPS_BEARER_STP_COM_INI_QCI_4) AS  EPS_BEARER_STP_COM_INI_QCI_4,
  SUM(EPS_BEAR_STP_COM_INI_NON_GBR) AS  EPS_BEAR_STP_COM_INI_NON_GBR,
  SUM(EPS_BEARER_STP_ATT_INI_QCI_1) AS  EPS_BEARER_STP_ATT_INI_QCI_1,
  SUM(EPS_BEARER_STP_ATT_INI_QCI_2) AS  EPS_BEARER_STP_ATT_INI_QCI_2,
  SUM(EPS_BEARER_STP_ATT_INI_QCI_3) AS  EPS_BEARER_STP_ATT_INI_QCI_3,
  SUM(EPS_BEARER_STP_ATT_INI_QCI_4) AS  EPS_BEARER_STP_ATT_INI_QCI_4,
  SUM(EPS_BEAR_STP_ATT_INI_NON_GBR) AS  EPS_BEAR_STP_ATT_INI_NON_GBR
FROM NOKLTE_PS_LUEST_MNC1_RAW@OSSRC3.WORLD T1,
   NOKLTE_PS_LEPSB_MNC1_RAW@OSSRC3.WORLD T2,
     UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND T2.LNCEL_ID = T1.LNCEL_ID
AND T2.PERIOD_START_TIME = T1.PERIOD_START_TIME
AND CO_OC_ID = 3130
AND CO_STATE = 0
GROUP BY  TO_DATE( SUBSTR( T1.PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR'), CO_NAME
;
