--------------------------------------------------------
--  DDL for View LTE_288B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_288B_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "PDCP_DATA_RATE_MAX_UL") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
		PDCP_DATA_RATE_MAX_UL
FROM NOKLTE_PS_LCELLT_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
