--------------------------------------------------------
--  DDL for View LTE_5031B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5031B_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5031B_NUM", "LTE_5031B_DEN", "DISC_RRC_PAGING", "RRC_PAGING_REQUESTS") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA , O1.CO_NAME, O1.CO_GID AS INT_ID,
    	DISC_RRC_PAGING AS  LTE_5031B_NUM,
        RRC_PAGING_REQUESTS AS LTE_5031B_DEN,
        DISC_RRC_PAGING,
        RRC_PAGING_REQUESTS
FROM NOKLTE_PS_LRRC_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
