--------------------------------------------------------
--  DDL for View LTE_5195A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5195A_HISTORICAL" ("PERIOD_START_TIME", "CO_NAME", "LTE_5195A_NUM", "LTE_5195A_DEN") AS 
  SELECT T1.PERIOD_START_TIME, O1.CO_NAME,
		ISYS_HO_SUCC AS  LTE_5195A_NUM,
		ISYS_HO_ATT AS LTE_5195A_DEN
FROM NOKLTE_PS_LISHO_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
;
