--------------------------------------------------------
--  DDL for View LTE_5569A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5569A_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5569A_NUM", "LTE_5569A_DEN", "RACH_STP_COMPLETIONS", "RACH_STP_ATT_SMALL_MSG", "RACH_STP_ATT_LARGE_MSG", "RACH_STP_ATT_DEDICATED") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
	RACH_STP_COMPLETIONS AS  LTE_5569A_NUM,
    (RACH_STP_ATT_SMALL_MSG+
    RACH_STP_ATT_LARGE_MSG+
    RACH_STP_ATT_DEDICATED) AS LTE_5569A_DEN,
    RACH_STP_COMPLETIONS,
    RACH_STP_ATT_SMALL_MSG,
    RACH_STP_ATT_LARGE_MSG,
    RACH_STP_ATT_DEDICATED
FROM NOKLTE_PS_LCELLD_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
