--------------------------------------------------------
--  DDL for View LTE_5113B_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5113B_MONTH" ("PERIOD_START_TIME", "CO_NAME", "LTE_5113B_NUM", "LTE_5113B_DEN", "LTE_5113B") AS 
  SELECT TRUNC( PERIOD_START_TIME  , 'MONTH') AS PERIOD_START_TIME, CO_NAME, SUM(LTE_5113B_NUM) AS LTE_5113B_NUM,
SUM(LTE_5113B_DEN) AS LTE_5113B_DEN,
ROUND (((DECODE (SUM(LTE_5113B_DEN), 0, 0, SUM(LTE_5113B_NUM) /
  SUM(LTE_5113B_DEN)) )*100),2) as LTE_5113B
FROM LTE_5113B_HISTORICAL
GROUP BY TRUNC( PERIOD_START_TIME  , 'MONTH'), CO_NAME
;
