--------------------------------------------------------
--  DDL for View LTE_5801D_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5801D_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5801D_NUM", "LTE_5801D_DEN", "SUM_ACTIVE_UE_DATA_UL", "DENOM_ACTIVE_UE_DATA_UL") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
		SUM_ACTIVE_UE_DATA_UL AS  LTE_5801D_NUM,
		DENOM_ACTIVE_UE_DATA_UL AS LTE_5801D_DEN,
		SUM_ACTIVE_UE_DATA_UL,
		DENOM_ACTIVE_UE_DATA_UL
FROM NOKLTE_PS_LCELLD_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
