--------------------------------------------------------
--  DDL for View LTE_5444B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5444B_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5444B_NUM", "LTE_5444B_DEN", "RSSI_PUSCH_LEVEL_01", "RSSI_PUSCH_LEVEL_02", "RSSI_PUSCH_LEVEL_03", "RSSI_PUSCH_LEVEL_04", "RSSI_PUSCH_LEVEL_05", "RSSI_PUSCH_LEVEL_06", "RSSI_PUSCH_LEVEL_07", "RSSI_PUSCH_LEVEL_08", "RSSI_PUSCH_LEVEL_09", "RSSI_PUSCH_LEVEL_10", "RSSI_PUSCH_LEVEL_11", "RSSI_PUSCH_LEVEL_12", "RSSI_PUSCH_LEVEL_13", "RSSI_PUSCH_LEVEL_14", "RSSI_PUSCH_LEVEL_15", "RSSI_PUSCH_LEVEL_16", "RSSI_PUSCH_LEVEL_17", "RSSI_PUSCH_LEVEL_18", "RSSI_PUSCH_LEVEL_19", "RSSI_PUSCH_LEVEL_20", "RSSI_PUSCH_LEVEL_21", "RSSI_PUSCH_LEVEL_22") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME,  O1.CO_GID AS INT_ID,
	(-120*RSSI_PUSCH_LEVEL_01
	-119*RSSI_PUSCH_LEVEL_02
    -117*RSSI_PUSCH_LEVEL_03
    -115*RSSI_PUSCH_LEVEL_04
    -113*RSSI_PUSCH_LEVEL_05
    -111*RSSI_PUSCH_LEVEL_06
    -109*RSSI_PUSCH_LEVEL_07
    -107*RSSI_PUSCH_LEVEL_08
    -105*RSSI_PUSCH_LEVEL_09
    -103*RSSI_PUSCH_LEVEL_10
    -101*RSSI_PUSCH_LEVEL_11
    -99*RSSI_PUSCH_LEVEL_12
    -97*RSSI_PUSCH_LEVEL_13
    -95*RSSI_PUSCH_LEVEL_14
    -93*RSSI_PUSCH_LEVEL_15
    -91*RSSI_PUSCH_LEVEL_16
    -89*RSSI_PUSCH_LEVEL_17
    -87*RSSI_PUSCH_LEVEL_18
    -85*RSSI_PUSCH_LEVEL_19
    -83*RSSI_PUSCH_LEVEL_20
    -81*RSSI_PUSCH_LEVEL_21
    -80*RSSI_PUSCH_LEVEL_22) AS  LTE_5444B_NUM,
    (RSSI_PUSCH_LEVEL_01+
    RSSI_PUSCH_LEVEL_02+
    RSSI_PUSCH_LEVEL_03+
    RSSI_PUSCH_LEVEL_04+
    RSSI_PUSCH_LEVEL_05+
    RSSI_PUSCH_LEVEL_06+
    RSSI_PUSCH_LEVEL_07+
    RSSI_PUSCH_LEVEL_08+
    RSSI_PUSCH_LEVEL_09+
    RSSI_PUSCH_LEVEL_10+
    RSSI_PUSCH_LEVEL_11+
    RSSI_PUSCH_LEVEL_12+
    RSSI_PUSCH_LEVEL_13+
    RSSI_PUSCH_LEVEL_14+
    RSSI_PUSCH_LEVEL_15+
    RSSI_PUSCH_LEVEL_16+
    RSSI_PUSCH_LEVEL_17+
    RSSI_PUSCH_LEVEL_18+
    RSSI_PUSCH_LEVEL_19+
    RSSI_PUSCH_LEVEL_20+
    RSSI_PUSCH_LEVEL_21+
    RSSI_PUSCH_LEVEL_22) AS LTE_5444B_DEN,
    RSSI_PUSCH_LEVEL_01,
    RSSI_PUSCH_LEVEL_02,
    RSSI_PUSCH_LEVEL_03,
    RSSI_PUSCH_LEVEL_04,
    RSSI_PUSCH_LEVEL_05,
    RSSI_PUSCH_LEVEL_06,
    RSSI_PUSCH_LEVEL_07,
    RSSI_PUSCH_LEVEL_08,
    RSSI_PUSCH_LEVEL_09,
    RSSI_PUSCH_LEVEL_10,
    RSSI_PUSCH_LEVEL_11,
    RSSI_PUSCH_LEVEL_12,
    RSSI_PUSCH_LEVEL_13,
    RSSI_PUSCH_LEVEL_14,
    RSSI_PUSCH_LEVEL_15,
    RSSI_PUSCH_LEVEL_16,
    RSSI_PUSCH_LEVEL_17,
    RSSI_PUSCH_LEVEL_18,
    RSSI_PUSCH_LEVEL_19,
    RSSI_PUSCH_LEVEL_20,
    RSSI_PUSCH_LEVEL_21,
    RSSI_PUSCH_LEVEL_22
FROM NOKLTE_PS_LPQUL_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
