--------------------------------------------------------
--  DDL for View LTE_5427A_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5427A_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5427A_NUM", "LTE_5427A_DEN", "UE_REP_CQI_LEVEL_00", "UE_REP_CQI_LEVEL_01", "UE_REP_CQI_LEVEL_02", "UE_REP_CQI_LEVEL_03", "UE_REP_CQI_LEVEL_04", "UE_REP_CQI_LEVEL_05", "UE_REP_CQI_LEVEL_06", "UE_REP_CQI_LEVEL_07", "UE_REP_CQI_LEVEL_08", "UE_REP_CQI_LEVEL_09", "UE_REP_CQI_LEVEL_10", "UE_REP_CQI_LEVEL_11", "UE_REP_CQI_LEVEL_12", "UE_REP_CQI_LEVEL_13", "UE_REP_CQI_LEVEL_14", "UE_REP_CQI_LEVEL_15") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
		(1*UE_REP_CQI_LEVEL_01+
		2*UE_REP_CQI_LEVEL_02+
		3*UE_REP_CQI_LEVEL_03+
		4*UE_REP_CQI_LEVEL_04+
		5*UE_REP_CQI_LEVEL_05+
		6*UE_REP_CQI_LEVEL_06+
		7*UE_REP_CQI_LEVEL_07+
		8*UE_REP_CQI_LEVEL_08+
		9*UE_REP_CQI_LEVEL_09+
		10*UE_REP_CQI_LEVEL_10+
		11*UE_REP_CQI_LEVEL_11+
		12*UE_REP_CQI_LEVEL_12+
		13*UE_REP_CQI_LEVEL_13+
		14*UE_REP_CQI_LEVEL_14+
		15*UE_REP_CQI_LEVEL_15) AS  LTE_5427A_NUM,
		(UE_REP_CQI_LEVEL_00+UE_REP_CQI_LEVEL_01+
		UE_REP_CQI_LEVEL_02+UE_REP_CQI_LEVEL_03+
		UE_REP_CQI_LEVEL_04+UE_REP_CQI_LEVEL_05+
		UE_REP_CQI_LEVEL_06+UE_REP_CQI_LEVEL_07+
		UE_REP_CQI_LEVEL_08+UE_REP_CQI_LEVEL_09+
		UE_REP_CQI_LEVEL_10+UE_REP_CQI_LEVEL_11+
		UE_REP_CQI_LEVEL_12+UE_REP_CQI_LEVEL_13+
		UE_REP_CQI_LEVEL_14+UE_REP_CQI_LEVEL_15) AS LTE_5427A_DEN,
		UE_REP_CQI_LEVEL_00,
		UE_REP_CQI_LEVEL_01,
		UE_REP_CQI_LEVEL_02,
		UE_REP_CQI_LEVEL_03,
		UE_REP_CQI_LEVEL_04,
		UE_REP_CQI_LEVEL_05,
		UE_REP_CQI_LEVEL_06,
		UE_REP_CQI_LEVEL_07,
		UE_REP_CQI_LEVEL_08,
		UE_REP_CQI_LEVEL_09,
		UE_REP_CQI_LEVEL_10,
		UE_REP_CQI_LEVEL_11,
		UE_REP_CQI_LEVEL_12,
		UE_REP_CQI_LEVEL_13,
		UE_REP_CQI_LEVEL_14,
		UE_REP_CQI_LEVEL_15
FROM NOKLTE_PS_LPQDL_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
