--------------------------------------------------------
--  DDL for View LTE_5113B_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5113B_HISTORICAL" ("PERIOD_START_TIME", "CO_NAME", "LTE_5113B_NUM", "LTE_5113B_DEN") AS 
  SELECT T1.PERIOD_START_TIME, O1.CO_NAME,
		(EPS_BEARER_SETUP_COMPLETIONS - EPS_BEARER_STP_COM_INI_QCI1 -
			EPS_BEARER_STP_COM_INI_QCI_2 - EPS_BEARER_STP_COM_INI_QCI_3 -
			EPS_BEARER_STP_COM_INI_QCI_4 - EPS_BEAR_STP_COM_INI_NON_GBR) AS  LTE_5113B_NUM,
		(EPS_BEARER_SETUP_ATTEMPTS - EPS_BEARER_STP_ATT_INI_QCI_1 -
			EPS_BEARER_STP_ATT_INI_QCI_2 - EPS_BEARER_STP_ATT_INI_QCI_3 -
			EPS_BEARER_STP_ATT_INI_QCI_4 - EPS_BEAR_STP_ATT_INI_NON_GBR) AS LTE_5113B_DEN
FROM NOKLTE_PS_LEPSB_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
;
