--------------------------------------------------------
--  DDL for View LTE_5134A_HOUR_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5134A_HOUR_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "PDCP_SDU_DELAY_DL_DTCH_MEAN") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS PERIOD_START_TIME, CO_NAME,
		SUM(PDCP_SDU_DELAY_DL_DTCH_MEAN) AS PDCP_SDU_DELAY_DL_DTCH_MEAN
FROM NOKLTE_PS_LCELLD_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
GROUP BY  TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI'), CO_NAME
;
