--------------------------------------------------------
--  DDL for View LTE_5292B_DAY
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5292B_DAY" ("PERIOD_START_TIME", "CO_NAME", "LTE_5292B") AS 
  SELECT TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR') AS PERIOD_START_TIME, CO_NAME,
			ROUND(AVG(PDCP_DATA_RATE_MEAN_DL),2) AS LTE_5292B
FROM LTE_5292B_HISTORICAL
GROUP BY  TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR'), CO_NAME
;
