--------------------------------------------------------
--  DDL for View LTE_5003A_HOUR_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5003A_HOUR_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "DATA_RB_STP_COMP", "DATA_RB_STP_ATT") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS PERIOD_START_TIME, CO_NAME,
SUM(DATA_RB_STP_COMP) AS DATA_RB_STP_COMP, SUM(DATA_RB_STP_ATT) AS DATA_RB_STP_ATT
FROM NOKLTE_PS_LRDB_MNC1_RAW@OSSRC3.WORLD T1,
	   UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
AND PERIOD_START_TIME >= (SELECT SYSDATE - 45 FROM DUAL)
GROUP BY TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI'), CO_NAME
;
