--------------------------------------------------------
--  Constraints for Table LTE_NSN_SERVICE_LCEL_HOUR
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."LTE_NSN_SERVICE_LCEL_HOUR" ADD CONSTRAINT "LTE_NSN_SERVICE_LCEL_HOUR_PK" PRIMARY KEY ("FECHA", "LNCEL_ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_SERVICE_LCEL_HOUR" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."LTE_NSN_SERVICE_LCEL_HOUR" MODIFY ("LNCEL_ID" NOT NULL ENABLE);
