--------------------------------------------------------
--  DDL for View LTE_5218C_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5218C_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5218C_NUM", "LTE_5218C_DEN", "SIGN_CONN_ESTAB_COMP", "SIGN_CONN_ESTAB_ATT_MO_S", "SIGN_CONN_ESTAB_ATT_MT", "SIGN_CONN_ESTAB_ATT_MO_D", "SIGN_CONN_ESTAB_ATT_OTHERS", "SIGN_CONN_ESTAB_ATT_EMG") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
		SIGN_CONN_ESTAB_COMP AS  LTE_5218C_NUM,
		(SIGN_CONN_ESTAB_ATT_MO_S+
		SIGN_CONN_ESTAB_ATT_MT+
		SIGN_CONN_ESTAB_ATT_MO_D+
		SIGN_CONN_ESTAB_ATT_OTHERS+
		SIGN_CONN_ESTAB_ATT_EMG) AS LTE_5218C_DEN,
		SIGN_CONN_ESTAB_COMP,
		SIGN_CONN_ESTAB_ATT_MO_S,
		SIGN_CONN_ESTAB_ATT_MT,
		SIGN_CONN_ESTAB_ATT_MO_D,
		SIGN_CONN_ESTAB_ATT_OTHERS,
		SIGN_CONN_ESTAB_ATT_EMG
FROM NOKLTE_PS_LUEST_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
