--------------------------------------------------------
--  DDL for View LTE_5289B_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5289B_HOUR" ("PERIOD_START_TIME", "LTE_5289B") AS 
  SELECT TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') AS PERIOD_START_TIME,
      ROUND(AVG(PDCP_DATA_RATE_MEAN_UL),2) AS LTE_5289B
FROM LTE_5289B
GROUP BY TO_DATE(SUBSTR( TO_CHAR( PERIOD_START_TIME, 'DD/MM/RRRR HH24:MI'), 0, 13),'DD/MM/YYYY HH24:MI') , CO_NAME
;
