--------------------------------------------------------
--  DDL for View LTE_5025A_DAY_COUNTERS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5025A_DAY_COUNTERS" ("PERIOD_START_TIME", "CO_NAME", "ENB_EPS_BEARER_REL_REQ_RNL", "ENB_EPS_BEARER_REL_REQ_TNL", "ENB_EPS_BEARER_REL_REQ_OTH", "EPC_EPS_BEARER_REL_REQ_NORM", "EPC_EPS_BEARER_REL_REQ_DETACH", "EPC_EPS_BEARER_REL_REQ_RNL", "EPC_EPS_BEARER_REL_REQ_OTH") AS 
  SELECT TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR') AS PERIOD_START_TIME, CO_NAME,
SUM(ENB_EPS_BEARER_REL_REQ_RNL) AS ENB_EPS_BEARER_REL_REQ_RNL,
SUM(ENB_EPS_BEARER_REL_REQ_TNL) AS ENB_EPS_BEARER_REL_REQ_TNL,
SUM(ENB_EPS_BEARER_REL_REQ_OTH) AS ENB_EPS_BEARER_REL_REQ_OTH,
SUM(EPC_EPS_BEARER_REL_REQ_NORM) AS EPC_EPS_BEARER_REL_REQ_NORM,
SUM(EPC_EPS_BEARER_REL_REQ_DETACH) AS EPC_EPS_BEARER_REL_REQ_DETACH,
SUM(EPC_EPS_BEARER_REL_REQ_RNL) AS EPC_EPS_BEARER_REL_REQ_RNL,
SUM(EPC_EPS_BEARER_REL_REQ_OTH) AS EPC_EPS_BEARER_REL_REQ_OTH
FROM NOKLTE_PS_LEPSB_MNC1_RAW@OSSRC3.WORLD T1,
     UTP_COMMON_OBJECTS@OSSRC3       O1
WHERE T1.LNCEL_ID = O1.CO_GID
AND CO_OC_ID = 3130
AND CO_STATE = 0
GROUP BY  TO_DATE( SUBSTR( PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR'), CO_NAME
;
