--------------------------------------------------------
--  DDL for View LTE_5292D_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5292D_HISTORICAL" ("FECHA", "CO_NAME", "INT_ID", "LTE_5292D_NUM", "LTE_5292D_DEN", "PDCP_SDU_VOL_DL", "ACTIVE_TTI_DL") AS 
  SELECT T1.PERIOD_START_TIME AS FECHA, O1.CO_NAME, O1.CO_GID AS INT_ID,
		PDCP_SDU_VOL_DL AS  LTE_5292D_NUM,
		ACTIVE_TTI_DL AS LTE_5292D_DEN,
		PDCP_SDU_VOL_DL,
		ACTIVE_TTI_DL
FROM NOKLTE_PS_LCELLT_MNC1_RAW@OSSRC3.WORLD T1
INNER JOIN UTP_COMMON_OBJECTS@OSSRC3.WORLD       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
;
