--------------------------------------------------------
--  DDL for View LTE_5003A_MONTH
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."LTE_5003A_MONTH" ("PERIOD_START_TIME", "CO_NAME", "LTE_5003A_NUM", "LTE_5003A_DEN", "LTE_5003A") AS 
  SELECT TRUNC( PERIOD_START_TIME  , 'MONTH') AS PERIOD_START_TIME, CO_NAME, SUM(LTE_5003A_NUM) AS LTE_5003A_NUM,
SUM(LTE_5003A_DEN) AS LTE_5003A_DEN, ROUND (((DECODE (SUM(LTE_5003A_DEN), 0, 0, SUM(LTE_5003A_NUM) /
  SUM(LTE_5003A_DEN)) )*100),2) as LTE_5003A
FROM LTE_5003A_HISTORICAL
GROUP BY TRUNC( PERIOD_START_TIME  , 'MONTH'),CO_NAME
;
