--------------------------------------------------------
--  DDL for Materialized View MV_LTE_TRAFIC_LCEL_BH_AUX
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "HARRIAGUE"."MV_LTE_TRAFIC_LCEL_BH_AUX"
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TBS_AUXILIAR" 
  BUILD DEFERRED
  USING INDEX 
  REFRESH COMPLETE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  ENABLE QUERY REWRITE
  AS SELECT FECHA, LNCEL_ID, VALOR
FROM (
      SELECT F1.FECHA,
             F1.LNCEL_ID,
             F1.TRAFICO_DL VALOR,
             ROW_NUMBER() OVER (PARTITION BY TRUNC(F1.FECHA),
                                             F1.LNCEL_ID
                                    ORDER BY (F1.TRAFICO_DL) DESC,
                                             F1.FECHA DESC) SEQNUM
      FROM (
             SELECT T1.FECHA, T1.LNCEL_ID, T1.TRAFICO_DL
             FROM LTE_NSN_SERVICE_LCEL_HOUR T1,
                  (SELECT PRM_VALUE AS FECHA_DESDE FROM CALIDAD_PARAMETROS WHERE PRM_ID = 275) T2,
                  (SELECT PRM_VALUE AS FECHA_HASTA FROM CALIDAD_PARAMETROS WHERE PRM_ID = 276) T3
             WHERE FECHA BETWEEN TO_DATE(T2.FECHA_DESDE, 'DD.MM.YYYY')
                           AND TO_DATE(T3.FECHA_HASTA, 'DD.MM.YYYY') + (86399 / 86400)
           ) F1
      )
WHERE SEQNUM = 1
;
 

   COMMENT ON MATERIALIZED VIEW "HARRIAGUE"."MV_LTE_TRAFIC_LCEL_BH_AUX"  IS 'snapshot table for snapshot HARRIAGUE.MV_LTE_TRAFIC_LCEL_BH_AUX';
