--------------------------------------------------------
--  Constraints for Table NOKLTE_PS_LS1AP_LNBTS_RAW
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."NOKLTE_PS_LS1AP_LNBTS_RAW" ADD CONSTRAINT "NOKLTE_PK_LS1AP_LNBTS_RAW" PRIMARY KEY ("INT_ID", "PERIOD_START_TIME") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PS_LS1AP_LNBTS_RAW" MODIFY ("INT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PS_LS1AP_LNBTS_RAW" MODIFY ("LNBTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PS_LS1AP_LNBTS_RAW" MODIFY ("PERIOD_START_TIME" NOT NULL ENABLE);
