--------------------------------------------------------
--  DDL for Table NOKLTE_PS_LHO_MNC1_RAW
--------------------------------------------------------

  CREATE TABLE "HARRIAGUE"."NOKLTE_PS_LHO_MNC1_RAW" 
   (	"INT_ID" NUMBER, 
	"CO_NAME" VARCHAR2(50 BYTE), 
	"MRBTS_ID" NUMBER, 
	"LNBTS_ID" NUMBER, 
	"LNCEL_ID" NUMBER, 
	"MCC_ID" VARCHAR2(10 BYTE), 
	"MNC_ID" VARCHAR2(10 BYTE), 
	"PERIOD_START_TIME" DATE, 
	"PERIOD_DURATION" NUMBER, 
	"PERIOD_DURATION_SUM" NUMBER, 
	"HO_INTFREQ_ATT" NUMBER, 
	"HO_INTFREQ_GAP_ATT" NUMBER, 
	"HO_INTFREQ_SUCC" NUMBER, 
	"HO_INTFREQ_GAP_SUCC" NUMBER, 
	"HO_INTFREQ_FAIL" NUMBER, 
	"HO_INTFREQ_GAP_FAIL" NUMBER, 
	"HO_EMG_PREP" NUMBER, 
	"HO_EMG_PREP_FAIL" NUMBER, 
	"HO_EMG_ATT" NUMBER, 
	"HO_EMG_SUCC" NUMBER, 
	"HO_DRX_ATT" NUMBER, 
	"HO_DRX_SUCC" NUMBER, 
	"MRO_LATE_HO" NUMBER, 
	"MRO_EARLY_TYPE1_HO" NUMBER, 
	"MRO_EARLY_TYPE2_HO" NUMBER, 
	"HO_LB_ATT" NUMBER, 
	"HO_LB_SUCC" NUMBER
   ) ;
