--------------------------------------------------------
--  DDL for Table NOKLTE_PS_LCELAV_MNC1_RAW_TEST
--------------------------------------------------------

  CREATE TABLE "HARRIAGUE"."NOKLTE_PS_LCELAV_MNC1_RAW_TEST" 
   (	"MRBTS_ID" NUMBER, 
	"LNBTS_ID" NUMBER, 
	"LNCEL_ID" NUMBER, 
	"MCC_ID" VARCHAR2(10 BYTE), 
	"MNC_ID" VARCHAR2(10 BYTE), 
	"PERIOD_START_TIME" DATE, 
	"PERIOD_DURATION" NUMBER, 
	"PERIOD_DURATION_SUM" NUMBER, 
	"CHNG_TO_CELL_AVAIL" NUMBER, 
	"CHNG_TO_CELL_PLAN_UNAVAIL" NUMBER, 
	"CHNG_TO_CELL_UNPLAN_UNAVAIL" NUMBER, 
	"SAMPLES_CELL_AVAIL" NUMBER, 
	"SAMPLES_CELL_PLAN_UNAVAIL" NUMBER, 
	"SAMPLES_CELL_UNPLAN_UNAVAIL" NUMBER, 
	"DENOM_CELL_AVAIL" NUMBER
   ) ;
