--------------------------------------------------------
--  Constraints for Table NOKLTE_PS_LCELAV_MNC1_RAW_TEST
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."NOKLTE_PS_LCELAV_MNC1_RAW_TEST" MODIFY ("LNCEL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PS_LCELAV_MNC1_RAW_TEST" MODIFY ("MCC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PS_LCELAV_MNC1_RAW_TEST" MODIFY ("MNC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PS_LCELAV_MNC1_RAW_TEST" MODIFY ("PERIOD_START_TIME" NOT NULL ENABLE);
