--------------------------------------------------------
--  DDL for Table NOKLTE_PS_LRRC_MNC1_RAW_TEST
--------------------------------------------------------

  CREATE TABLE "HARRIAGUE"."NOKLTE_PS_LRRC_MNC1_RAW_TEST" 
   (	"MRBTS_ID" NUMBER, 
	"LNBTS_ID" NUMBER, 
	"LNCEL_ID" NUMBER, 
	"MCC_ID" VARCHAR2(10 BYTE), 
	"MNC_ID" VARCHAR2(10 BYTE), 
	"PERIOD_START_TIME" DATE, 
	"PERIOD_DURATION" NUMBER, 
	"PERIOD_DURATION_SUM" NUMBER, 
	"REJ_RRC_CONN_RE_ESTAB" NUMBER, 
	"DISC_RRC_PAGING" NUMBER, 
	"RRC_PAGING_MESSAGES" NUMBER, 
	"RRC_PAGING_REQUESTS" NUMBER, 
	"RRC_CON_RE_ESTAB_ATT" NUMBER, 
	"RRC_CON_RE_ESTAB_SUCC" NUMBER, 
	"RRC_CON_RE_ESTAB_ATT_HO_FAIL" NUMBER, 
	"RRC_CON_RE_ESTAB_SUCC_HO_FAIL" NUMBER, 
	"RRC_CON_RE_ESTAB_ATT_OTHER" NUMBER, 
	"RRC_CON_RE_ESTAB_SUCC_OTHER" NUMBER, 
	"REPORT_CGI_REQ" NUMBER, 
	"SUCC_CGI_REPORTS" NUMBER, 
	"RRC_CON_REL_REDIR_H_ENB" NUMBER, 
	"RRC_PAGING_ETWS_CMAS" NUMBER
   ) ;
