--------------------------------------------------------
--  Constraints for Table NOKLTE_PV_LENBLD_LNBTS_RAW
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."NOKLTE_PV_LENBLD_LNBTS_RAW" ADD CONSTRAINT "NOKLTE_PK_LENBLD_LNBTS_RAW" PRIMARY KEY ("PERIOD_START_TIME", "INT_ID", "LNBTS_ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PV_LENBLD_LNBTS_RAW" MODIFY ("INT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PV_LENBLD_LNBTS_RAW" MODIFY ("LNBTS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."NOKLTE_PV_LENBLD_LNBTS_RAW" MODIFY ("PERIOD_START_TIME" NOT NULL ENABLE);
