--------------------------------------------------------
--  DDL for Table NOKLTE_PS_LISHO_MNC1_RAW
--------------------------------------------------------

  CREATE TABLE "HARRIAGUE"."NOKLTE_PS_LISHO_MNC1_RAW" 
   (	"INT_ID" NUMBER, 
	"CO_NAME" VARCHAR2(50 BYTE), 
	"MRBTS_ID" NUMBER, 
	"LNBTS_ID" NUMBER, 
	"LNCEL_ID" NUMBER, 
	"MCC_ID" VARCHAR2(10 BYTE), 
	"MNC_ID" VARCHAR2(10 BYTE), 
	"PERIOD_START_TIME" DATE, 
	"PERIOD_DURATION" NUMBER, 
	"PERIOD_DURATION_SUM" NUMBER, 
	"CSFB_REDIR_CR_ATT" NUMBER, 
	"CSFB_REDIR_CR_CMODE_ATT" NUMBER, 
	"CSFB_REDIR_CR_EMERGENCY_ATT" NUMBER, 
	"ISYS_HO_PREP" NUMBER, 
	"ISYS_HO_PREP_FAIL_TIM" NUMBER, 
	"ISYS_HO_PREP_FAIL_AC" NUMBER, 
	"ISYS_HO_PREP_FAIL_OTH" NUMBER, 
	"ISYS_HO_ATT" NUMBER, 
	"ISYS_HO_SUCC" NUMBER, 
	"ISYS_HO_FAIL" NUMBER, 
	"NACC_TO_GSM_ATT" NUMBER, 
	"NACC_TO_GSM_SUCC" NUMBER, 
	"NACC_TO_GSM_FAIL" NUMBER, 
	"ISYS_HO_UTRAN_SRVCC_ATT" NUMBER, 
	"ISYS_HO_UTRAN_SRVCC_SUCC" NUMBER, 
	"ISYS_HO_UTRAN_SRVCC_FAIL" NUMBER, 
	"CSFB_PSHO_UTRAN_ATT" NUMBER, 
	"ISYS_HO_GERAN_SRVCC_ATT" NUMBER, 
	"ISYS_HO_GERAN_SRVCC_SUCC" NUMBER, 
	"ISYS_HO_GERAN_SRVCC_FAIL" NUMBER
   ) ;
