--------------------------------------------------------
--  DDL for Table NOKLTE_PS_LRDB_MNC1_RAW
--------------------------------------------------------

  CREATE TABLE "HARRIAGUE"."NOKLTE_PS_LRDB_MNC1_RAW" 
   (	"INT_ID" NUMBER, 
	"CO_NAME" VARCHAR2(50 BYTE), 
	"MRBTS_ID" NUMBER, 
	"LNBTS_ID" NUMBER, 
	"LNCEL_ID" NUMBER, 
	"MCC_ID" VARCHAR2(10 BYTE), 
	"MNC_ID" VARCHAR2(10 BYTE), 
	"PERIOD_START_TIME" DATE, 
	"PERIOD_DURATION" NUMBER, 
	"PERIOD_DURATION_SUM" NUMBER, 
	"DATA_RB_STP_ATT" NUMBER, 
	"DATA_RB_STP_COMP" NUMBER, 
	"DATA_RB_STP_FAIL" NUMBER, 
	"RB_REL_REQ_NORM_REL" NUMBER, 
	"RB_REL_REQ_DETACH_PROC" NUMBER, 
	"RB_REL_REQ_RNL" NUMBER, 
	"RB_REL_REQ_OTHER" NUMBER, 
	"SRB1_SETUP_ATT" NUMBER, 
	"SRB1_SETUP_SUCC" NUMBER, 
	"SRB1_SETUP_FAIL" NUMBER, 
	"SRB2_SETUP_ATT" NUMBER, 
	"SRB2_SETUP_SUCC" NUMBER, 
	"SRB2_SETUP_FAIL" NUMBER, 
	"RB_REL_REQ_RNL_REDIR" NUMBER
   ) ;
