--------------------------------------------------------
--  DDL for Table NOKLTE_PS_LUEST_MNC1_RAW_TEST
--------------------------------------------------------

  CREATE TABLE "HARRIAGUE"."NOKLTE_PS_LUEST_MNC1_RAW_TEST" 
   (	"MRBTS_ID" NUMBER, 
	"LNBTS_ID" NUMBER, 
	"LNCEL_ID" NUMBER, 
	"MCC_ID" VARCHAR2(10 BYTE), 
	"MNC_ID" VARCHAR2(10 BYTE), 
	"PERIOD_START_TIME" DATE, 
	"PERIOD_DURATION" NUMBER, 
	"PERIOD_DURATION_SUM" NUMBER, 
	"SIGN_CONN_ESTAB_COMP" NUMBER, 
	"SIGN_EST_F_RRCCOMPL_MISSING" NUMBER, 
	"SIGN_EST_F_RRCCOMPL_ERROR" NUMBER, 
	"SIGN_CONN_ESTAB_FAIL_RRMRAC" NUMBER, 
	"EPC_INIT_TO_IDLE_UE_NORM_REL" NUMBER, 
	"EPC_INIT_TO_IDLE_DETACH" NUMBER, 
	"EPC_INIT_TO_IDLE_RNL" NUMBER, 
	"EPC_INIT_TO_IDLE_OTHER" NUMBER, 
	"ENB_INIT_TO_IDLE_NORM_REL" NUMBER, 
	"ENB_INIT_TO_IDLE_RNL" NUMBER, 
	"ENB_INIT_TO_IDLE_OTHER" NUMBER, 
	"SIGN_CONN_ESTAB_ATT_MO_S" NUMBER, 
	"SIGN_CONN_ESTAB_ATT_MT" NUMBER, 
	"SIGN_CONN_ESTAB_ATT_MO_D" NUMBER, 
	"SIGN_CONN_ESTAB_ATT_OTHERS" NUMBER, 
	"SIGN_CONN_ESTAB_ATT_EMG" NUMBER, 
	"SIGN_CONN_ESTAB_COMP_EMG" NUMBER, 
	"SIGN_CONN_ESTAB_FAIL_RB_EMG" NUMBER, 
	"SUBFRAME_DRX_ACTIVE_UE" NUMBER, 
	"SUBFRAME_DRX_SLEEP_UE" NUMBER, 
	"PRE_EMPT_UE_CONTEXT_NON_GBR" NUMBER
   ) ;
