--------------------------------------------------------
--  DDL for View NOKLTE_PS_LEPSB_MNC1_VW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."NOKLTE_PS_LEPSB_MNC1_VW" ("MRBTS_ID", "LNBTS_ID", "LNCEL_ID", "MCC_ID", "MNC_ID", "PERIOD_START_TIME", "PERIOD_DURATION", "PERIOD_DURATION_SUM", "EPS_BEARER_SETUP_ATTEMPTS", "EPS_BEARER_SETUP_COMPLETIONS", "EPS_BEARER_SETUP_FAIL_RNL", "EPS_BEARER_SETUP_FAIL_TRPORT", "EPS_BEARER_SETUP_FAIL_RESOUR", "EPS_BEARER_SETUP_FAIL_OTH", "EPC_EPS_BEARER_REL_REQ_NORM", "EPC_EPS_BEARER_REL_REQ_DETACH", "EPC_EPS_BEARER_REL_REQ_RNL", "EPC_EPS_BEARER_REL_REQ_OTH", "ENB_EPS_BEARER_REL_REQ_NORM", "ENB_EPS_BEARER_REL_REQ_RNL", "ENB_EPS_BEARER_REL_REQ_OTH", "ENB_EPS_BEARER_REL_REQ_TNL", "ENB_EPSBEAR_REL_REQ_RNL_REDIR", "EPS_BEARER_SETUP_FAIL_HO", "EPS_BEAR_SET_COM_ADDIT_QCI1", "EPC_EPS_BEAR_REL_REQ_N_QCI1", "EPC_EPS_BEAR_REL_REQ_D_QCI1", "EPC_EPS_BEAR_REL_REQ_R_QCI1", "EPC_EPS_BEAR_REL_REQ_O_QCI1", "ENB_EPS_BEAR_REL_REQ_N_QCI1", "ENB_EPS_BEAR_REL_REQ_O_QCI1", "ENB_EPS_BEAR_REL_REQ_T_QCI1", "EPS_BEARER_STP_ATT_INI_QCI_1", "EPS_BEAR_STP_ATT_INI_NON_GBR", "EPS_BEARER_STP_ATT_ADD_QCI_1", "EPS_BEARER_STP_COM_INI_QCI1", "EPS_BEAR_STP_COM_INI_NON_GBR", "ENB_EPS_BEAR_REL_REQ_R_QCI1", "ENB_EPS_BEAR_REL_REQ_RD_QCI1", "EPS_BEARER_STP_ATT_INI_QCI_2", "EPS_BEARER_STP_ATT_INI_QCI_3", "EPS_BEARER_STP_ATT_INI_QCI_4", "EPS_BEARER_STP_ATT_ADD_QCI_2", "EPS_BEARER_STP_ATT_ADD_QCI_3", "EPS_BEARER_STP_ATT_ADD_QCI_4", "EPS_BEARER_STP_COM_INI_QCI_2", "EPS_BEARER_STP_COM_INI_QCI_3", "EPS_BEARER_STP_COM_INI_QCI_4", "EPS_BEARER_STP_COM_ADD_QCI_2", "EPS_BEARER_STP_COM_ADD_QCI_3", "EPS_BEARER_STP_COM_ADD_QCI_4", "PRE_EMPT_GBR_BEARER", "PRE_EMPT_NON_GBR_BEARER", "ERAB_REL_ENB_ACT_QCI1", "ERAB_REL_ENB_ACT_QCI2", "ERAB_REL_ENB_ACT_QCI3", "ERAB_REL_ENB_ACT_QCI4", "ERAB_REL_ENB_ACT_NON_GBR", "ERAB_IN_SESSION_TIME_QCI1", "ERAB_IN_SESSION_TIME_QCI2", "ERAB_IN_SESSION_TIME_QCI3", "ERAB_IN_SESSION_TIME_QCI4", "ERAB_IN_SESSION_TIME_NON_GBR") AS 
  SELECT
F_LTE_GET_GID(3130,LNCEL,LNBTS,MRBTS,NULL,'MRBTS_ID')                          MRBTS_ID,
F_LTE_GET_GID(3130,LNCEL,LNBTS,MRBTS,NULL,'LNBTS_ID')                          LNBTS_ID,
F_LTE_GET_GID(3130,LNCEL,LNBTS,MRBTS,NULL,'LNCEL_ID')                          LNCEL_ID,
MCC                                                                            MCC_ID,
MNC                                                                            MNC_ID,
CAST(startTime AS DATE)                                                        PERIOD_START_TIME,
interval                                                                       PERIOD_DURATION,
interval                                                                       PERIOD_DURATION_SUM,
 M8006C0                                                                       EPS_BEARER_SETUP_ATTEMPTS,
 M8006C1                                                                       EPS_BEARER_SETUP_COMPLETIONS,
 M8006C2                                                                       EPS_BEARER_SETUP_FAIL_RNL,
 M8006C3                                                                       EPS_BEARER_SETUP_FAIL_TRPORT,
 M8006C4                                                                       EPS_BEARER_SETUP_FAIL_RESOUR,
 M8006C5                                                                       EPS_BEARER_SETUP_FAIL_OTH,
 M8006C6                                                                       EPC_EPS_BEARER_REL_REQ_NORM,
 M8006C7                                                                       EPC_EPS_BEARER_REL_REQ_DETACH,
 M8006C8                                                                       EPC_EPS_BEARER_REL_REQ_RNL,
 M8006C9                                                                       EPC_EPS_BEARER_REL_REQ_OTH,
 M8006C10                                                                       ENB_EPS_BEARER_REL_REQ_NORM,
 M8006C12                                                                       ENB_EPS_BEARER_REL_REQ_RNL,
 M8006C13                                                                       ENB_EPS_BEARER_REL_REQ_OTH,
 M8006C14                                                                       ENB_EPS_BEARER_REL_REQ_TNL,
 M8006C15                                                                       ENB_EPSBEAR_REL_REQ_RNL_REDIR,
 NULL                                                                EPS_BEARER_SETUP_FAIL_HO,
 M8006C44                                                                       EPS_BEAR_SET_COM_ADDIT_QCI1,
 M8006C89                                                                       EPC_EPS_BEAR_REL_REQ_N_QCI1,
 M8006C98                                                                       EPC_EPS_BEAR_REL_REQ_D_QCI1,
 M8006C107                                                                       EPC_EPS_BEAR_REL_REQ_R_QCI1,
 M8006C116                                                                       EPC_EPS_BEAR_REL_REQ_O_QCI1,
 M8006C125                                                                       ENB_EPS_BEAR_REL_REQ_N_QCI1,
 M8006C143                                                                       ENB_EPS_BEAR_REL_REQ_O_QCI1,
 M8006C152                                                                       ENB_EPS_BEAR_REL_REQ_T_QCI1,
 M8006C17                                                                       EPS_BEARER_STP_ATT_INI_QCI_1,
 M8006C18                                                                       EPS_BEAR_STP_ATT_INI_NON_GBR,
 M8006C26                                                                       EPS_BEARER_STP_ATT_ADD_QCI_1,
 M8006C35                                                                       EPS_BEARER_STP_COM_INI_QCI1,
 M8006C36                                                                       EPS_BEAR_STP_COM_INI_NON_GBR,
 M8006C134                                                                       ENB_EPS_BEAR_REL_REQ_R_QCI1,
 M8006C161                                                                       ENB_EPS_BEAR_REL_REQ_RD_QCI1,
 M8006C162                                                                       EPS_BEARER_STP_ATT_INI_QCI_2,
 M8006C163                                                                       EPS_BEARER_STP_ATT_INI_QCI_3,
 M8006C164                                                                       EPS_BEARER_STP_ATT_INI_QCI_4,
 M8006C165                                                                       EPS_BEARER_STP_ATT_ADD_QCI_2,
 M8006C166                                                                       EPS_BEARER_STP_ATT_ADD_QCI_3,
 M8006C167                                                                       EPS_BEARER_STP_ATT_ADD_QCI_4,
 M8006C168                                                                       EPS_BEARER_STP_COM_INI_QCI_2,
 M8006C169                                                                       EPS_BEARER_STP_COM_INI_QCI_3,
 M8006C170                                                                       EPS_BEARER_STP_COM_INI_QCI_4,
 M8006C171                                                                       EPS_BEARER_STP_COM_ADD_QCI_2,
 M8006C172                                                                       EPS_BEARER_STP_COM_ADD_QCI_3,
 M8006C173                                                                       EPS_BEARER_STP_COM_ADD_QCI_4,
 M8006C174                                                                       PRE_EMPT_GBR_BEARER,
 M8006C175                                                                       PRE_EMPT_NON_GBR_BEARER,
 M8006C176                                                                       ERAB_REL_ENB_ACT_QCI1,
 M8006C177                                                                       ERAB_REL_ENB_ACT_QCI2,
 M8006C178                                                                       ERAB_REL_ENB_ACT_QCI3,
 M8006C179                                                                       ERAB_REL_ENB_ACT_QCI4,
 M8006C180                                                                       ERAB_REL_ENB_ACT_NON_GBR,
 M8006C181                                                                       ERAB_IN_SESSION_TIME_QCI1,
 M8006C182                                                                       ERAB_IN_SESSION_TIME_QCI2,
 M8006C183                                                                       ERAB_IN_SESSION_TIME_QCI3,
 M8006C184                                                                       ERAB_IN_SESSION_TIME_QCI4,
 M8006C185                                                                      ERAB_IN_SESSION_TIME_NON_GBR

FROM LTE_C_NSN_LEPSB_MNC1_AUX
;
