--------------------------------------------------------
--  DDL for Procedure P_LTE_C_ENODEB_JOB_HOURLY_R
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HARRIAGUE"."P_LTE_C_ENODEB_JOB_HOURLY_R" (P_FECHA_DESDE     IN CHAR,
                                                                    P_FECHA_HASTA     IN CHAR)
IS
-- Autor: Mariano Moron. Fecha: 09.09.2015.
-- Validación de periodo
CURSOR PERIODO (P_FECHA_DESDE IN CHAR, P_FECHA_HASTA IN CHAR) IS
SELECT DIA,
       RESULTADO,
       MAX(FECHA_DESDE) FECHA_DESDE,
       MAX(FECHA_HASTA) FECHA_HASTA
  FROM (
SELECT DIA,
       RESULTADO,
       DECODE(RESTO, 0, FECHA) FECHA_DESDE,
       DECODE(RESTO, 5, FECHA) FECHA_HASTA
  FROM (
SELECT DIA,
       TO_CHAR(FECHA, 'DD.MM.YYYY HH24') FECHA,
       FLOOR(TO_NUMBER(HORA)/ 6) RESULTADO,
       MOD(TO_NUMBER(HORA), 6) RESTO
  FROM CALIDAD_STATUS_REFERENCES
WHERE FECHA BETWEEN TO_DATE(P_FECHA_DESDE, 'DD.MM.YYYY')
                 AND TO_DATE(P_FECHA_HASTA, 'DD.MM.YYYY') + 86399/86400
       )
       )
GROUP BY DIA, RESULTADO
ORDER BY DIA, RESULTADO;



 BEGIN
FOR SEN IN PERIODO (P_FECHA_DESDE, P_FECHA_HASTA) LOOP

  P_LTE_C_LCELAV_RAW_INS(SEN.FECHA_DESDE, SEN.FECHA_HASTA);

  P_LTE_C_LCELLD_RAW_INS(SEN.FECHA_DESDE, SEN.FECHA_HASTA);

  P_LTE_C_LCELLT_RAW_INS(SEN.FECHA_DESDE, SEN.FECHA_HASTA);

  P_LTE_C_LEPSB_RAW_INS(SEN.FECHA_DESDE, SEN.FECHA_HASTA);

  P_LTE_C_LPQDL_RAW_INS(SEN.FECHA_DESDE, SEN.FECHA_HASTA);

  P_LTE_C_LPQUL_RAW_INS(SEN.FECHA_DESDE, SEN.FECHA_HASTA);

  P_LTE_C_LRRC_RAW_INS(SEN.FECHA_DESDE, SEN.FECHA_HASTA);

  P_LTE_C_LUEST_RAW_INS(SEN.FECHA_DESDE, SEN.FECHA_HASTA);

END LOOP;
 END;

/
