--------------------------------------------------------
--  DDL for Procedure P_LTE_TRUNCATE_SPART_HOURLY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HARRIAGUE"."P_LTE_TRUNCATE_SPART_HOURLY" (P_FECHA_DESDE    IN CHAR,
                                                               P_FECHA_HASTA    IN CHAR,
                                                               P_CLASS_TABLE    IN CHAR,
                                                               P_SUBCLASS_TABLE IN CHAR) IS

-- Autor: Mariano Moron. Fecha: 10.09.2015.

CURSOR C_VENTANA (P_PARTICION_ESQUEMA_MSC_FECHA CHAR) IS
SELECT TO_CHAR(FECHA, P_PARTICION_ESQUEMA_MSC_FECHA) FECHA
  FROM CALIDAD_STATUS_REFERENCES
 WHERE FECHA BETWEEN TO_DATE(P_FECHA_DESDE, 'DD.MM.YYYY HH24')
                 AND TO_DATE(P_FECHA_HASTA, 'DD.MM.YYYY HH24')
   --AND DIA > TRUNC(SYSDATE) - (7 * 2)
 ORDER BY FECHA DESC;

V_NOMBRE_TABLA                 VARCHAR2(30);
V_PARTICION_ESQUEMA            VARCHAR2(30);
V_PARTICION_ESQUEMA_MSC_FECHA  VARCHAR2(30);
V_PARTICION_FORMATO_MSC_FECHA  VARCHAR2(30);
V_SUBPARTICION_NAME            VARCHAR2(10);
V_PARTITION_CLASS              VARCHAR2(20);

V_LINEA                        VARCHAR2(200);

BEGIN

SELECT A.NOMBRE_TABLA,
       A.PARTICION_ESQUEMA,
       A.PARTICION_ESQUEMA_MSC_FECHA,
       A.PARTICION_FORMATO_MSC_FECHA,
       CASE WHEN P_SUBCLASS_TABLE != 'LCE' THEN '_' ELSE NULL END ||
       CASE
            WHEN P_SUBCLASS_TABLE = 'LNBTS'   THEN 'LBS'
            WHEN P_SUBCLASS_TABLE = 'ALM'     THEN 'ALM'
            WHEN P_SUBCLASS_TABLE = 'MERCADO' THEN 'MKT'
            WHEN P_SUBCLASS_TABLE = 'PAIS'    THEN 'CTY'
            WHEN P_SUBCLASS_TABLE = 'CIUDAD'  THEN 'CDD'
            ELSE NULL END SUBPARTICION_NAME,
       CASE WHEN P_SUBCLASS_TABLE = 'LCE' THEN 'PARTITION'
                                          ELSE 'SUBPARTITION' END PARTITION_CLASS
  INTO V_NOMBRE_TABLA,
       V_PARTICION_ESQUEMA,
       V_PARTICION_ESQUEMA_MSC_FECHA,
       V_PARTICION_FORMATO_MSC_FECHA,
       V_SUBPARTICION_NAME,
       V_PARTITION_CLASS
  FROM CALIDAD_PARAMETROS_TABLAS A,
       (
SELECT CASE WHEN P_CLASS_TABLE = 'ServiceNeHour'             THEN 'LTE_NSN_SERVICE_NE_HOUR'
            WHEN P_CLASS_TABLE = 'AvailabilityNeHour'        THEN 'LTE_NSN_AVAIL_NE_HOUR'
            WHEN P_CLASS_TABLE = 'PowerAndQualityNeHour'     THEN 'LTE_NSN_PAQ_NE_HOUR'
            WHEN P_CLASS_TABLE = 'HandOverNeHour'            THEN 'LTE_NSN_HO_NE_HOUR'

            WHEN P_CLASS_TABLE = 'ServiceLceHour'            THEN 'LTE_NSN_SERVICE_LCEL_HOUR'
            WHEN P_CLASS_TABLE = 'AvailabilityLceHour'       THEN 'LTE_NSN_AVAIL_LCEL_HOUR'
            WHEN P_CLASS_TABLE = 'PowerAndQualityLceHour'    THEN 'LTE_NSN_PAQ_LCEL_HOUR'
            WHEN P_CLASS_TABLE = 'HandOverLceHour'           THEN 'LTE_NSN_HO_LCEL_HOUR'

            ELSE NULL END NOMBRE_TABLA
  FROM DUAL
       ) B
 WHERE A.NOMBRE_TABLA = B.NOMBRE_TABLA;

FOR SYN IN C_VENTANA (V_PARTICION_ESQUEMA_MSC_FECHA) LOOP


SELECT 'ALTER TABLE HARRIAGUE.'||V_NOMBRE_TABLA||' TRUNCATE '||V_PARTITION_CLASS||' '||
       V_PARTICION_ESQUEMA||SYN.FECHA||V_SUBPARTICION_NAME LINEA
  INTO V_LINEA
  FROM DUAL;

BEGIN

DBMS_OUTPUT.PUT_LINE(V_LINEA);
EXECUTE IMMEDIATE V_LINEA;


EXCEPTION

WHEN OTHERS THEN
NULL;

END;

END LOOP;

END;

/
