--------------------------------------------------------
--  DDL for Procedure P_LTE_C_ENODEB_JOB_HOURLY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HARRIAGUE"."P_LTE_C_ENODEB_JOB_HOURLY" 
IS
-- Autor: Mariano Moron. Fecha: 09.09.2015.
P_FECHA_DESDE VARCHAR2(15) := TO_CHAR( TRUNC(SYSDATE, 'HH24') - 5/24, 'DD.MM.YYYY HH24');
P_FECHA_HASTA VARCHAR2(15) := TO_CHAR( TRUNC(SYSDATE, 'HH24') - 1 , 'DD.MM.YYYY HH24');

 BEGIN

	P_LTE_C_LCELAV_RAW_INS(P_FECHA_DESDE, P_FECHA_HASTA);

	P_LTE_C_LCELLD_RAW_INS(P_FECHA_DESDE, P_FECHA_HASTA);

	P_LTE_C_LCELLT_RAW_INS(P_FECHA_DESDE, P_FECHA_HASTA);

	P_LTE_C_LEPSB_RAW_INS(P_FECHA_DESDE, P_FECHA_HASTA);

	P_LTE_C_LPQDL_RAW_INS(P_FECHA_DESDE, P_FECHA_HASTA);

	P_LTE_C_LPQUL_RAW_INS(P_FECHA_DESDE, P_FECHA_HASTA);

	P_LTE_C_LRRC_RAW_INS(P_FECHA_DESDE, P_FECHA_HASTA);

	P_LTE_C_LUEST_RAW_INS(P_FECHA_DESDE, P_FECHA_HASTA);

 END;

/
