--------------------------------------------------------
--  DDL for Procedure P_LTE_NSN_PAQ_NE_JOB_MONTHLY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HARRIAGUE"."P_LTE_NSN_PAQ_NE_JOB_MONTHLY" 
IS
-- Autor: Paula Fernandez. Fecha: 15.09.2015.
-- Actualizacion: Mariano Moron. Fecha 22.09.2015. Motivo: Se agregan calculo de IBHM.
P_FECHA_DESDE VARCHAR2(15) := TO_CHAR(add_months(TRUNC(SYSDATE, 'MONTH'), -1), 'DD.MM.YYYY HH24');
P_FECHA_HASTA VARCHAR2(15) := TO_CHAR((TRUNC(SYSDATE, 'MONTH') - 1+ (86399 / 86400)),'DD.MM.YYYY HH24');
P_LEVEL VARCHAR2(10) := 'DAYM';
P_LEVEL_IBHM VARCHAR2(10) := 'IBHM';

 BEGIN

-- Procesamiento de contadores mensuales
 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'LNBTS', P_LEVEL);

 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'ALM', P_LEVEL);

 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'MERCADO', P_LEVEL);

 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'PAIS', P_LEVEL);

 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'CIUDAD', P_LEVEL);

-- Procesamiento de Busy Hour Mensual
 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'LNBTS', P_LEVEL_IBHM);

 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'ALM', P_LEVEL_IBHM);

 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'MERCADO', P_LEVEL_IBHM);

 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'PAIS', P_LEVEL_IBHM);

 P_LTE_NSN_PAQ_NE_INS_MONTHLY(P_FECHA_DESDE, P_FECHA_HASTA, 'CIUDAD', P_LEVEL_IBHM);

 END;

/
