--------------------------------------------------------
--  DDL for Procedure P_LTE_NSN_PAQ_NE_JOB_HOURLY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HARRIAGUE"."P_LTE_NSN_PAQ_NE_JOB_HOURLY" 
IS
-- Autor: Paula Fernandez. Fecha: 11.09.2015.
P_FECHA_DESDE VARCHAR2(15) := TO_CHAR( TRUNC(SYSDATE, 'HH24') - 6/24, 'DD.MM.YYYY HH24');
P_FECHA_HASTA VARCHAR2(15) := TO_CHAR( TRUNC(SYSDATE, 'HH24'), 'DD.MM.YYYY HH24');
P_LEVEL VARCHAR2(10) := 'HOUR';


 BEGIN

 P_LTE_NSN_PAQ_NE_INS_HOURLY(P_FECHA_DESDE, P_FECHA_HASTA, 'LNBTS', P_LEVEL);

 P_LTE_NSN_PAQ_NE_INS_HOURLY(P_FECHA_DESDE, P_FECHA_HASTA, 'ALM', P_LEVEL);

 P_LTE_NSN_PAQ_NE_INS_HOURLY(P_FECHA_DESDE, P_FECHA_HASTA, 'MERCADO', P_LEVEL);

 P_LTE_NSN_PAQ_NE_INS_HOURLY(P_FECHA_DESDE, P_FECHA_HASTA, 'PAIS', P_LEVEL);

 P_LTE_NSN_PAQ_NE_INS_HOURLY(P_FECHA_DESDE, P_FECHA_HASTA, 'CIUDAD', P_LEVEL);

 END;

/
