--------------------------------------------------------
--  DDL for Procedure P_LTE_TRUNCATE_SPARTITION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HARRIAGUE"."P_LTE_TRUNCATE_SPARTITION" (P_FECHA_DESDE    IN CHAR,
                                                         P_FECHA_HASTA    IN CHAR,
                                                         P_CLASS_TABLE    IN CHAR,
                                                         P_SUBCLASS_TABLE IN CHAR) IS

-- Autor: Mariano Morsn. Fecha: 08.09.2015.
-- Actualizacion: Mario Heredia. Fecha: 10.09.2015.
-- Actualizacion: Mariano Moron. Fecha 14.09.2015. Motivo: Fix del P_SUBCLASS_TABLE

CURSOR C_VENTANA (P_PARTICION_ESQUEMA_MSC_FECHA CHAR) IS
SELECT TO_CHAR(DIA, P_PARTICION_ESQUEMA_MSC_FECHA) FECHA
  FROM CALIDAD_STATUS_REFERENCES
 WHERE DIA BETWEEN TO_DATE(P_FECHA_DESDE, 'DD.MM.YYYY')
               AND TO_DATE(P_FECHA_HASTA, 'DD.MM.YYYY')
   AND HORA = '00'
 ORDER BY DIA DESC;

V_NOMBRE_TABLA                 VARCHAR2(30);
V_PARTICION_ESQUEMA            VARCHAR2(30);
V_PARTICION_ESQUEMA_MSC_FECHA  VARCHAR2(30);
V_PARTICION_FORMATO_MSC_FECHA  VARCHAR2(30);
V_SUBPARTICION_NAME            VARCHAR2(10);
V_PARTITION_CLASS              VARCHAR2(20);

V_LINEA                        VARCHAR2(200);

BEGIN

SELECT A.NOMBRE_TABLA,
       A.PARTICION_ESQUEMA,
       A.PARTICION_ESQUEMA_MSC_FECHA,
       A.PARTICION_FORMATO_MSC_FECHA,
       CASE WHEN P_SUBCLASS_TABLE != 'LCE' THEN '_' ELSE NULL END ||
       CASE
            WHEN P_SUBCLASS_TABLE = 'LNBTS'    THEN 'LBS'
            WHEN P_SUBCLASS_TABLE = 'ALM'     THEN 'ALM'
            WHEN P_SUBCLASS_TABLE = 'MERCADO' THEN 'MKT'
            WHEN P_SUBCLASS_TABLE = 'PAIS'    THEN 'CTY'
            WHEN P_SUBCLASS_TABLE = 'CIUDAD'  THEN 'CDD'
            ELSE NULL END SUBPARTICION_NAME,
       CASE WHEN P_SUBCLASS_TABLE = 'LCE' THEN 'PARTITION'
                                          ELSE 'SUBPARTITION' END PARTITION_CLASS
  INTO V_NOMBRE_TABLA,
       V_PARTICION_ESQUEMA,
       V_PARTICION_ESQUEMA_MSC_FECHA,
       V_PARTICION_FORMATO_MSC_FECHA,
       V_SUBPARTICION_NAME,
       V_PARTITION_CLASS
  FROM CALIDAD_PARAMETROS_TABLAS A,
       (
SELECT CASE WHEN P_CLASS_TABLE = 'ServiceWcellDay'          THEN 'LTE_NSN_SERVICE_LCEL_DAY'
            WHEN P_CLASS_TABLE = 'ServiceWcellBH'           THEN 'LTE_NSN_SERVICE_LCEL_BH'
            WHEN P_CLASS_TABLE = 'ServiceNeDay'             THEN 'LTE_NSN_SERVICE_NE_DAY'
            WHEN P_CLASS_TABLE = 'ServiceNeBH'              THEN 'LTE_NSN_SERVICE_NE_BH'

            WHEN P_CLASS_TABLE = 'AvailabilityWcellDay'     THEN 'LTE_NSN_AVAIL_LCEL_DAY'
            WHEN P_CLASS_TABLE = 'AvailabilityWcellBH'      THEN 'LTE_NSN_AVAIL_LCEL_BH'
            WHEN P_CLASS_TABLE = 'AvailabilityNeDay'        THEN 'LTE_NSN_AVAIL_NE_DAY'
            WHEN P_CLASS_TABLE = 'AvailabilityNeBH'         THEN 'LTE_NSN_AVAIL_NE_BH'

            WHEN P_CLASS_TABLE = 'PowerAndQualityWcellDay'  THEN 'LTE_NSN_PAQ_LCEL_DAY'
            WHEN P_CLASS_TABLE = 'PowerAndQualityWcellBH'   THEN 'LTE_NSN_PAQ_LCEL_BH'
            WHEN P_CLASS_TABLE = 'PowerAndQualityNeDay'     THEN 'LTE_NSN_PAQ_NE_DAY'
            WHEN P_CLASS_TABLE = 'PowerAndQualityNeBH'      THEN 'LTE_NSN_PAQ_NE_BH'

            WHEN P_CLASS_TABLE = 'HOWcellDay'               THEN 'LTE_NSN_HO_LCEL_DAY'
            WHEN P_CLASS_TABLE = 'HOWcellBH'                THEN 'LTE_NSN_HO_LCEL_BH'
            WHEN P_CLASS_TABLE = 'HONeDay'                  THEN 'LTE_NSN_HO_NE_DAY'
            WHEN P_CLASS_TABLE = 'HONeBH'                   THEN 'LTE_NSN_HO_NE_BH'

            ELSE NULL END NOMBRE_TABLA
  FROM DUAL
       ) B
 WHERE A.NOMBRE_TABLA = B.NOMBRE_TABLA;

FOR SYN IN C_VENTANA (V_PARTICION_ESQUEMA_MSC_FECHA) LOOP


SELECT 'ALTER TABLE HARRIAGUE.'||V_NOMBRE_TABLA||' TRUNCATE '||V_PARTITION_CLASS||' '||
       V_PARTICION_ESQUEMA||SYN.FECHA||V_SUBPARTICION_NAME LINEA
  INTO V_LINEA
  FROM DUAL;

BEGIN

EXECUTE IMMEDIATE V_LINEA;
--DBMS_OUTPUT.PUT_LINE(V_LINEA);
EXCEPTION

WHEN OTHERS THEN
NULL;

END;

END LOOP;

END;

/
