--------------------------------------------------------
--  DDL for Procedure P_LTE_NSN_SRV_NE_JOB_WEEKLY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HARRIAGUE"."P_LTE_NSN_SRV_NE_JOB_WEEKLY" 
IS
-- Autor: Mariano Moron. Fecha: 14.09.2015.
-- Actualizacion: Mariano Moron. Fecha: 21.09.2015. Motivo: Se agrega procesamiento de BH.
P_FECHA_DESDE VARCHAR2(15) := TO_CHAR( TRUNC(SYSDATE, 'DAY') - 14, 'DD.MM.YYYY');
P_FECHA_HASTA VARCHAR2(15) := TO_CHAR( TRUNC(SYSDATE, 'DAY') - 1, 'DD.MM.YYYY');
P_LEVEL VARCHAR2(10) := 'DAYW';
P_LEVEL_IBHW VARCHAR2(10) := 'IBHW';


 BEGIN

--Procesamiento de contadores semanales
 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'LNBTS', P_LEVEL);

 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'ALM', P_LEVEL);

 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'MERCADO', P_LEVEL);

 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'PAIS', P_LEVEL);

 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'CIUDAD', P_LEVEL);

--Procesamiento de Busy hour weekly
 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'LNBTS', P_LEVEL_IBHW);

 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'ALM', P_LEVEL_IBHW);

 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'MERCADO', P_LEVEL_IBHW);

 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'PAIS', P_LEVEL_IBHW);

 P_LTE_NSN_SRV_NE_INS_WEEKLY(P_FECHA_DESDE, P_FECHA_HASTA, 'CIUDAD', P_LEVEL_IBHW);

 END;

/
