--------------------------------------------------------
--  Constraints for Table PCOFNS_PS_ULOAD_UNIT1_RAW
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_ULOAD_UNIT1_RAW" ADD CONSTRAINT "PCOFNS_PK_ULOAD_UNIT1_RAW" PRIMARY KEY ("FINS_ID", "PERIOD_START_TIME", "UNIT_ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_ULOAD_UNIT1_RAW" MODIFY ("FINS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_ULOAD_UNIT1_RAW" MODIFY ("UNIT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_ULOAD_UNIT1_RAW" MODIFY ("PERIOD_START_TIME" NOT NULL ENABLE);
