--------------------------------------------------------
--  Constraints for Table PCOFNS_PS_NEUM_FLEXINS_RAW
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_NEUM_FLEXINS_RAW" ADD CONSTRAINT "PCOFNS_PK_NEUM_FLEXINS_RAW" PRIMARY KEY ("PERIOD_START_TIME", "FINS_ID") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_NEUM_FLEXINS_RAW" MODIFY ("FINS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_NEUM_FLEXINS_RAW" MODIFY ("PERIOD_START_TIME" NOT NULL ENABLE);
