--------------------------------------------------------
--  DDL for View PCOFNS_PS_MMMT_TA_ISABHWEEK
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."PCOFNS_PS_MMMT_TA_ISABHWEEK" ("PERIOD_START_TIME", "FINS_ID", "TA_ID", "PERIOD_DURATION", "EPS_ATTACH_SUCC") AS 
  SELECT PERIOD_START_TIME, FINS_ID, TA_ID, PERIOD_DURATION, ROUND(BH/3,2) AS EPS_ATTACH_SUCC
  FROM (
        SELECT PERIOD_START_TIME, FINS_ID, TA_ID, PERIOD_DURATION, EPS_ATTACH_SUCC, SEQNUM,
          (SUM(EPS_ATTACH_SUCC) OVER(PARTITION BY PERIOD_START_TIME, FINS_ID, TA_ID, PERIOD_DURATION))AS BH
        FROM (
              SELECT TRUNC(PERIOD_START_TIME , 'DAY') AS PERIOD_START_TIME, FINS_ID, TA_ID, PERIOD_DURATION, EPS_ATTACH_SUCC, ROW_NUMBER()
                    OVER (
                      PARTITION BY TRUNC(PERIOD_START_TIME , 'DAY'), FINS_ID, TA_ID, PERIOD_DURATION
                      ORDER BY EPS_ATTACH_SUCC DESC) SEQNUM
              FROM PCOFNS_PS_MMMT_TA_BH
              )
        WHERE SEQNUM < 4
        )
  WHERE SEQNUM = 1
;
