--------------------------------------------------------
--  Constraints for Table PCOFNS_PS_MMMT_TA_RAW
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_MMMT_TA_RAW" MODIFY ("FINS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_MMMT_TA_RAW" MODIFY ("MCC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_MMMT_TA_RAW" MODIFY ("MNC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_MMMT_TA_RAW" MODIFY ("TA_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."PCOFNS_PS_MMMT_TA_RAW" MODIFY ("PERIOD_START_TIME" NOT NULL ENABLE);
