--------------------------------------------------------
--  DDL for Package PKG_LTE_CORE
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "HARRIAGUE"."PKG_LTE_CORE" AS 

  /**
  * Author: Carrasco Marcelo
  * Date: 11/02/2016
  * Comment: Paquete para la visualizaci?n de datos de LTE
  */

  --(P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL) 
  FUNCTION F_MMMT RETURN FLNS_MMMT_TAB PIPELINED;
  --(P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL)
  FUNCTION F_SMMT  RETURN FLNS_SMMT_TAB PIPELINED;
  --(P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL)
  FUNCTION F_UMLM_MMMT  RETURN FLNS_UMLM_MMMT_TAB PIPELINED;
  --(P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL)
  FUNCTION FLNS_SGSM  RETURN FLNS_SGSM_TAB PIPELINED;
 -- (P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL)
  FUNCTION F_TPS  RETURN FLNS_TAB PIPELINED;
  
  PROCEDURE P_TPS (RESULT_SET OUT SYS_REFCURSOR);
  --
  -- CON FECHA
  --
  --
  FUNCTION F_MMMT2(P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL)  RETURN FLNS_MMMT_TAB PIPELINED;
  --
  FUNCTION F_SMMT2 (P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL) RETURN FLNS_SMMT_TAB PIPELINED;
  --
  FUNCTION F_UMLM_MMMT2 (P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL) RETURN FLNS_UMLM_MMMT_TAB PIPELINED;
  --
  FUNCTION FLNS_SGSM2 (P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL) RETURN FLNS_SGSM_TAB PIPELINED;
 -- 
  FUNCTION F_TPS2 (P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL) RETURN FLNS_TAB PIPELINED;
  
   PROCEDURE P_TPS2 (P_FINI VARCHAR2,P_FFIN VARCHAR2 DEFAULT NULL,RESULT_SET OUT SYS_REFCURSOR);
END PKG_LTE_CORE;

/
