--------------------------------------------------------
--  DDL for View PRINCIP_KPI_DAY_OSSRC2
--------------------------------------------------------

  CREATE OR REPLACE VIEW "HARRIAGUE"."PRINCIP_KPI_DAY_OSSRC2" ("FECHA", "CO_NAME", "INT_ID", "LTE_139B_NUM", "LTE_139B_DEN", "LTE_139B", "PDSCH_TRANS_NACK_MCS0", "PDSCH_TRANS_NACK_MCS1", "PDSCH_TRANS_NACK_MCS2", "PDSCH_TRANS_NACK_MCS3", "PDSCH_TRANS_NACK_MCS4", "PDSCH_TRANS_NACK_MCS5", "PDSCH_TRANS_NACK_MCS6", "PDSCH_TRANS_NACK_MCS7", "PDSCH_TRANS_NACK_MCS8", "PDSCH_TRANS_NACK_MCS9", "PDSCH_TRANS_NACK_MCS10", "PDSCH_TRANS_NACK_MCS11", "PDSCH_TRANS_NACK_MCS12", "PDSCH_TRANS_NACK_MCS13", "PDSCH_TRANS_NACK_MCS14", "PDSCH_TRANS_NACK_MCS15", "PDSCH_TRANS_NACK_MCS16", "PDSCH_TRANS_NACK_MCS17", "PDSCH_TRANS_NACK_MCS18", "PDSCH_TRANS_NACK_MCS19", "PDSCH_TRANS_NACK_MCS20", "PDSCH_TRANS_NACK_MCS21", "PDSCH_TRANS_NACK_MCS22", "PDSCH_TRANS_NACK_MCS23", "PDSCH_TRANS_NACK_MCS24", "PDSCH_TRANS_NACK_MCS25", "PDSCH_TRANS_NACK_MCS26", "PDSCH_TRANS_NACK_MCS27", "PDSCH_TRANS_NACK_MCS28", "PDSCH_TRANS_NACK_MCS29", "PDSCH_TRANS_NACK_MCS30", "PDSCH_TRANS_NACK_MCS31", "PDSCH_TRANS_USING_MCS0", "PDSCH_TRANS_USING_MCS1", "PDSCH_TRANS_USING_MCS2", "PDSCH_TRANS_USING_MCS3", "PDSCH_TRANS_USING_MCS4", "PDSCH_TRANS_USING_MCS5", "PDSCH_TRANS_USING_MCS6", "PDSCH_TRANS_USING_MCS7", "PDSCH_TRANS_USING_MCS8", "PDSCH_TRANS_USING_MCS9", "PDSCH_TRANS_USING_MCS10", "PDSCH_TRANS_USING_MCS11", "PDSCH_TRANS_USING_MCS12", "PDSCH_TRANS_USING_MCS13", "PDSCH_TRANS_USING_MCS14", "PDSCH_TRANS_USING_MCS15", "PDSCH_TRANS_USING_MCS16", "PDSCH_TRANS_USING_MCS17", "PDSCH_TRANS_USING_MCS18", "PDSCH_TRANS_USING_MCS19", "PDSCH_TRANS_USING_MCS20", "PDSCH_TRANS_USING_MCS21", "PDSCH_TRANS_USING_MCS22", "PDSCH_TRANS_USING_MCS23", "PDSCH_TRANS_USING_MCS24", "PDSCH_TRANS_USING_MCS25", "PDSCH_TRANS_USING_MCS26", "PDSCH_TRANS_USING_MCS27", "PDSCH_TRANS_USING_MCS28", "PDSCH_TRANS_USING_MCS29", "PDSCH_TRANS_USING_MCS30", "PDSCH_TRANS_USING_MCS31", "LTE_140B_NUM", "LTE_140B_DEN", "LTE_140B", "PUSCH_TRANS_NACK_MCS0", "PUSCH_TRANS_NACK_MCS1", "PUSCH_TRANS_NACK_MCS2", "PUSCH_TRANS_NACK_MCS3", "PUSCH_TRANS_NACK_MCS4", "PUSCH_TRANS_NACK_MCS5", "PUSCH_TRANS_NACK_MCS6", "PUSCH_TRANS_NACK_MCS7", "PUSCH_TRANS_NACK_MCS8", "PUSCH_TRANS_NACK_MCS9", "PUSCH_TRANS_NACK_MCS10", "PUSCH_TRANS_NACK_MCS11", "PUSCH_TRANS_NACK_MCS12", "PUSCH_TRANS_NACK_MCS13", "PUSCH_TRANS_NACK_MCS14", "PUSCH_TRANS_NACK_MCS15", "PUSCH_TRANS_NACK_MCS16", "PUSCH_TRANS_NACK_MCS17", "PUSCH_TRANS_NACK_MCS18", "PUSCH_TRANS_NACK_MCS19", "PUSCH_TRANS_NACK_MCS20", "PUSCH_TRANS_NACK_MCS21", "PUSCH_TRANS_NACK_MCS22", "PUSCH_TRANS_NACK_MCS23", "PUSCH_TRANS_NACK_MCS24", "PUSCH_TRANS_NACK_MCS25", "PUSCH_TRANS_NACK_MCS26", "PUSCH_TRANS_NACK_MCS27", "PUSCH_TRANS_NACK_MCS28", "PUSCH_TRANS_USING_MCS0", "PUSCH_TRANS_USING_MCS1", "PUSCH_TRANS_USING_MCS2", "PUSCH_TRANS_USING_MCS3", "PUSCH_TRANS_USING_MCS4", "PUSCH_TRANS_USING_MCS5", "PUSCH_TRANS_USING_MCS6", "PUSCH_TRANS_USING_MCS7", "PUSCH_TRANS_USING_MCS8", "PUSCH_TRANS_USING_MCS9", "PUSCH_TRANS_USING_MCS10", "PUSCH_TRANS_USING_MCS11", "PUSCH_TRANS_USING_MCS12", "PUSCH_TRANS_USING_MCS13", "PUSCH_TRANS_USING_MCS14", "PUSCH_TRANS_USING_MCS15", "PUSCH_TRANS_USING_MCS16", "PUSCH_TRANS_USING_MCS17", "PUSCH_TRANS_USING_MCS18", "PUSCH_TRANS_USING_MCS19", "PUSCH_TRANS_USING_MCS20", "PUSCH_TRANS_USING_MCS21", "PUSCH_TRANS_USING_MCS22", "PUSCH_TRANS_USING_MCS23", "PUSCH_TRANS_USING_MCS24", "PUSCH_TRANS_USING_MCS25", "PUSCH_TRANS_USING_MCS26", "PUSCH_TRANS_USING_MCS27", "PUSCH_TRANS_USING_MCS28", "LTE_288B", "PDCP_DATA_RATE_MAX_UL", "LTE_291B", "PDCP_DATA_RATE_MAX_DL", "LTE_5017A_NUM", "LTE_5017A_DEN", "LTE_5017A", "EPS_BEARER_SETUP_COMPLETIONS", "EPS_BEARER_SETUP_ATTEMPTS", "LTE_5025D_NUM", "LTE_5025D_DEN", "LTE_5025D", "EPC_EPS_BEARER_REL_REQ_NORM", "EPC_EPS_BEARER_REL_REQ_DETACH", "EPC_EPS_BEARER_REL_REQ_RNL", "EPC_EPS_BEARER_REL_REQ_OTH", "ENB_EPSBEAR_REL_REQ_RNL_REDIR", "ENB_EPS_BEARER_REL_REQ_RNL", "ENB_EPS_BEARER_REL_REQ_TNL", "ENB_EPS_BEARER_REL_REQ_OTH", "PRE_EMPT_GBR_BEARER", "PRE_EMPT_NON_GBR_BEARER", "LTE_5031B_NUM", "LTE_5031B_DEN", "LTE_5031B", "DISC_RRC_PAGING", "RRC_PAGING_REQUESTS", "LTE_5134A", "PDCP_SDU_DELAY_DL_DTCH_MEAN", "LTE_5137A", "PDCP_SDU_DELAY_UL_DTCH_MEAN", "PDCP_SDU_VOL_DL", "LTE_5212A", "LTE_5213A", "LTE_5218C_NUM", "LTE_5218C_DEN", "LTE_5218C", "SIGN_CONN_ESTAB_COMP", "SIGN_CONN_ESTAB_ATT_MO_S", "SIGN_CONN_ESTAB_ATT_MT", "SIGN_CONN_ESTAB_ATT_MO_D", "SIGN_CONN_ESTAB_ATT_OTHERS", "SIGN_CONN_ESTAB_ATT_EMG", "LTE_5289D_NUM", "LTE_5289D_DEN", "LTE_5289D", "PDCP_SDU_VOL_UL", "ACTIVE_TTI_UL", "LTE_5292D_NUM", "LTE_5292D_DEN", "LTE_5292D", "ACTIVE_TTI_DL", "LTE_5427A_NUM", "LTE_5427A_DEN", "LTE_5427A", "UE_REP_CQI_LEVEL_00", "UE_REP_CQI_LEVEL_01", "UE_REP_CQI_LEVEL_02", "UE_REP_CQI_LEVEL_03", "UE_REP_CQI_LEVEL_04", "UE_REP_CQI_LEVEL_05", "UE_REP_CQI_LEVEL_06", "UE_REP_CQI_LEVEL_07", "UE_REP_CQI_LEVEL_08", "UE_REP_CQI_LEVEL_09", "UE_REP_CQI_LEVEL_10", "UE_REP_CQI_LEVEL_11", "UE_REP_CQI_LEVEL_12", "UE_REP_CQI_LEVEL_13", "UE_REP_CQI_LEVEL_14", "UE_REP_CQI_LEVEL_15", "LTE_5441B_NUM", "LTE_5441B_DEN", "LTE_5441B", "RSSI_PUCCH_LEVEL_01", "RSSI_PUCCH_LEVEL_02", "RSSI_PUCCH_LEVEL_03", "RSSI_PUCCH_LEVEL_04", "RSSI_PUCCH_LEVEL_05", "RSSI_PUCCH_LEVEL_06", "RSSI_PUCCH_LEVEL_07", "RSSI_PUCCH_LEVEL_08", "RSSI_PUCCH_LEVEL_09", "RSSI_PUCCH_LEVEL_10", "RSSI_PUCCH_LEVEL_11", "RSSI_PUCCH_LEVEL_12", "RSSI_PUCCH_LEVEL_13", "RSSI_PUCCH_LEVEL_14", "RSSI_PUCCH_LEVEL_15", "RSSI_PUCCH_LEVEL_16", "RSSI_PUCCH_LEVEL_17", "RSSI_PUCCH_LEVEL_18", "RSSI_PUCCH_LEVEL_19", "RSSI_PUCCH_LEVEL_20", "RSSI_PUCCH_LEVEL_21", "RSSI_PUCCH_LEVEL_22", "LTE_5444B_NUM", "LTE_5444B_DEN", "LTE_5444B", "RSSI_PUSCH_LEVEL_01", "RSSI_PUSCH_LEVEL_02", "RSSI_PUSCH_LEVEL_03", "RSSI_PUSCH_LEVEL_04", "RSSI_PUSCH_LEVEL_05", "RSSI_PUSCH_LEVEL_06", "RSSI_PUSCH_LEVEL_07", "RSSI_PUSCH_LEVEL_08", "RSSI_PUSCH_LEVEL_09", "RSSI_PUSCH_LEVEL_10", "RSSI_PUSCH_LEVEL_11", "RSSI_PUSCH_LEVEL_12", "RSSI_PUSCH_LEVEL_13", "RSSI_PUSCH_LEVEL_14", "RSSI_PUSCH_LEVEL_15", "RSSI_PUSCH_LEVEL_16", "RSSI_PUSCH_LEVEL_17", "RSSI_PUSCH_LEVEL_18", "RSSI_PUSCH_LEVEL_19", "RSSI_PUSCH_LEVEL_20", "RSSI_PUSCH_LEVEL_21", "RSSI_PUSCH_LEVEL_22", "LTE_5541B_NUM", "LTE_5541B_DEN", "LTE_5541B", "SINR_PUCCH_LEVEL_1", "SINR_PUCCH_LEVEL_2", "SINR_PUCCH_LEVEL_3", "SINR_PUCCH_LEVEL_4", "SINR_PUCCH_LEVEL_5", "SINR_PUCCH_LEVEL_6", "SINR_PUCCH_LEVEL_7", "SINR_PUCCH_LEVEL_8", "SINR_PUCCH_LEVEL_9", "SINR_PUCCH_LEVEL_10", "SINR_PUCCH_LEVEL_11", "SINR_PUCCH_LEVEL_12", "SINR_PUCCH_LEVEL_13", "SINR_PUCCH_LEVEL_14", "SINR_PUCCH_LEVEL_15", "SINR_PUCCH_LEVEL_16", "SINR_PUCCH_LEVEL_17", "SINR_PUCCH_LEVEL_18", "SINR_PUCCH_LEVEL_19", "SINR_PUCCH_LEVEL_20", "SINR_PUCCH_LEVEL_21", "SINR_PUCCH_LEVEL_22", "LTE_5544B_NUM", "LTE_5544B_DEN", "LTE_5544B", "LTE_5569A_NUM", "LTE_5569A_DEN", "LTE_5569A", "RACH_STP_COMPLETIONS", "RACH_STP_ATT_SMALL_MSG", "RACH_STP_ATT_LARGE_MSG", "RACH_STP_ATT_DEDICATED", "LTE_5750A_NUM", "LTE_5750A_DEN", "LTE_5750A", "SAMPLES_CELL_AVAIL", "DENOM_CELL_AVAIL", "LTE_5800D_NUM", "LTE_5800D_DEN", "LTE_5800D", "SUM_ACTIVE_UE_DATA_DL", "DENOM_ACTIVE_UE_DATA_DL", "LTE_5801D_NUM", "LTE_5801D_DEN", "LTE_5801D", "SUM_ACTIVE_UE_DATA_UL", "DENOM_ACTIVE_UE_DATA_UL", "LTE_5802A", "DL_UE_DATA_BUFF_MAX", "LTE_5803A", "UL_UE_DATA_BUFF_MAX", "M8013C6", "M8013C7", "M8013C8", "M8013C27", "M8006C2", "M8006C4", "M8006C3", "M8006C5", "M8006C12", "M8006C14", "M8006C13") AS 
  SELECT TO_DATE( SUBSTR( T1.PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR') AS FECHA,
        O1.CO_NAME, O1.CO_GID AS INT_ID,
        (SUM(PDSCH_TRANS_NACK_MCS0)+
        SUM(PDSCH_TRANS_NACK_MCS1)+
        SUM(PDSCH_TRANS_NACK_MCS2)+
        SUM(PDSCH_TRANS_NACK_MCS3)+
        SUM(PDSCH_TRANS_NACK_MCS4)+
        SUM(PDSCH_TRANS_NACK_MCS5)+
        SUM(PDSCH_TRANS_NACK_MCS6)+
        SUM(PDSCH_TRANS_NACK_MCS7)+
        SUM(PDSCH_TRANS_NACK_MCS8)+
        SUM(PDSCH_TRANS_NACK_MCS9)+
        SUM(PDSCH_TRANS_NACK_MCS10)+
        SUM(PDSCH_TRANS_NACK_MCS11)+
        SUM(PDSCH_TRANS_NACK_MCS12)+
        SUM(PDSCH_TRANS_NACK_MCS13)+
        SUM(PDSCH_TRANS_NACK_MCS14)+
        SUM(PDSCH_TRANS_NACK_MCS15)+
        SUM(PDSCH_TRANS_NACK_MCS16)+
        SUM(PDSCH_TRANS_NACK_MCS17)+
        SUM(PDSCH_TRANS_NACK_MCS18)+
        SUM(PDSCH_TRANS_NACK_MCS19)+
        SUM(PDSCH_TRANS_NACK_MCS20)+
        SUM(PDSCH_TRANS_NACK_MCS21)+
        SUM(PDSCH_TRANS_NACK_MCS22)+
        SUM(PDSCH_TRANS_NACK_MCS23)+
        SUM(PDSCH_TRANS_NACK_MCS24)+
        SUM(PDSCH_TRANS_NACK_MCS25)+
        SUM(PDSCH_TRANS_NACK_MCS26)+
        SUM(PDSCH_TRANS_NACK_MCS27)+
        SUM(PDSCH_TRANS_NACK_MCS28)+
        SUM(PDSCH_TRANS_NACK_MCS29)+
        SUM(PDSCH_TRANS_NACK_MCS30)+
        SUM(PDSCH_TRANS_NACK_MCS31)) AS  LTE_139B_NUM,
        (SUM(PDSCH_TRANS_USING_MCS0)+
        SUM(PDSCH_TRANS_USING_MCS1)+
        SUM(PDSCH_TRANS_USING_MCS2)+
        SUM(PDSCH_TRANS_USING_MCS3)+
        SUM(PDSCH_TRANS_USING_MCS4)+
        SUM(PDSCH_TRANS_USING_MCS5)+
        SUM(PDSCH_TRANS_USING_MCS6)+
        SUM(PDSCH_TRANS_USING_MCS7)+
        SUM(PDSCH_TRANS_USING_MCS8)+
        SUM(PDSCH_TRANS_USING_MCS9)+
        SUM(PDSCH_TRANS_USING_MCS10)+
        SUM(PDSCH_TRANS_USING_MCS11)+
        SUM(PDSCH_TRANS_USING_MCS12)+
        SUM(PDSCH_TRANS_USING_MCS13)+
        SUM(PDSCH_TRANS_USING_MCS14)+
        SUM(PDSCH_TRANS_USING_MCS15)+
        SUM(PDSCH_TRANS_USING_MCS16)+
        SUM(PDSCH_TRANS_USING_MCS17)+
        SUM(PDSCH_TRANS_USING_MCS18)+
        SUM(PDSCH_TRANS_USING_MCS19)+
        SUM(PDSCH_TRANS_USING_MCS20)+
        SUM(PDSCH_TRANS_USING_MCS21)+
        SUM(PDSCH_TRANS_USING_MCS22)+
        SUM(PDSCH_TRANS_USING_MCS23)+
        SUM(PDSCH_TRANS_USING_MCS24)+
        SUM(PDSCH_TRANS_USING_MCS25)+
        SUM(PDSCH_TRANS_USING_MCS26)+
        SUM(PDSCH_TRANS_USING_MCS27)+
        SUM(PDSCH_TRANS_USING_MCS28)+
        SUM(PDSCH_TRANS_USING_MCS29)+
        SUM(PDSCH_TRANS_USING_MCS30)+
        SUM(PDSCH_TRANS_USING_MCS31)) AS LTE_139B_DEN,
        ROUND ( DECODE(
                (SUM(PDSCH_TRANS_NACK_MCS0)+
                SUM(PDSCH_TRANS_NACK_MCS1)+
                SUM(PDSCH_TRANS_NACK_MCS2)+
                SUM(PDSCH_TRANS_NACK_MCS3)+
                SUM(PDSCH_TRANS_NACK_MCS4)+
                SUM(PDSCH_TRANS_NACK_MCS5)+
                SUM(PDSCH_TRANS_NACK_MCS6)+
                SUM(PDSCH_TRANS_NACK_MCS7)+
                SUM(PDSCH_TRANS_NACK_MCS8)+
                SUM(PDSCH_TRANS_NACK_MCS9)+
                SUM(PDSCH_TRANS_NACK_MCS10)+
                SUM(PDSCH_TRANS_NACK_MCS11)+
                SUM(PDSCH_TRANS_NACK_MCS12)+
                SUM(PDSCH_TRANS_NACK_MCS13)+
                SUM(PDSCH_TRANS_NACK_MCS14)+
                SUM(PDSCH_TRANS_NACK_MCS15)+
                SUM(PDSCH_TRANS_NACK_MCS16)+
                SUM(PDSCH_TRANS_NACK_MCS17)+
                SUM(PDSCH_TRANS_NACK_MCS18)+
                SUM(PDSCH_TRANS_NACK_MCS19)+
                SUM(PDSCH_TRANS_NACK_MCS20)+
                SUM(PDSCH_TRANS_NACK_MCS21)+
                SUM(PDSCH_TRANS_NACK_MCS22)+
                SUM(PDSCH_TRANS_NACK_MCS23)+
                SUM(PDSCH_TRANS_NACK_MCS24)+
                SUM(PDSCH_TRANS_NACK_MCS25)+
                SUM(PDSCH_TRANS_NACK_MCS26)+
                SUM(PDSCH_TRANS_NACK_MCS27)+
                SUM(PDSCH_TRANS_NACK_MCS28)+
                SUM(PDSCH_TRANS_NACK_MCS29)+
                SUM(PDSCH_TRANS_NACK_MCS30)+
                SUM(PDSCH_TRANS_NACK_MCS31)), 0, 0,
                (SUM(PDSCH_TRANS_USING_MCS0)+
                SUM(PDSCH_TRANS_USING_MCS1)+
                SUM(PDSCH_TRANS_USING_MCS2)+
                SUM(PDSCH_TRANS_USING_MCS3)+
                SUM(PDSCH_TRANS_USING_MCS4)+
                SUM(PDSCH_TRANS_USING_MCS5)+
                SUM(PDSCH_TRANS_USING_MCS6)+
                SUM(PDSCH_TRANS_USING_MCS7)+
                SUM(PDSCH_TRANS_USING_MCS8)+
                SUM(PDSCH_TRANS_USING_MCS9)+
                SUM(PDSCH_TRANS_USING_MCS10)+
                SUM(PDSCH_TRANS_USING_MCS11)+
                SUM(PDSCH_TRANS_USING_MCS12)+
                SUM(PDSCH_TRANS_USING_MCS13)+
                SUM(PDSCH_TRANS_USING_MCS14)+
                SUM(PDSCH_TRANS_USING_MCS15)+
                SUM(PDSCH_TRANS_USING_MCS16)+
                SUM(PDSCH_TRANS_USING_MCS17)+
                SUM(PDSCH_TRANS_USING_MCS18)+
                SUM(PDSCH_TRANS_USING_MCS19)+
                SUM(PDSCH_TRANS_USING_MCS20)+
                SUM(PDSCH_TRANS_USING_MCS21)+
                SUM(PDSCH_TRANS_USING_MCS22)+
                SUM(PDSCH_TRANS_USING_MCS23)+
                SUM(PDSCH_TRANS_USING_MCS24)+
                SUM(PDSCH_TRANS_USING_MCS25)+
                SUM(PDSCH_TRANS_USING_MCS26)+
                SUM(PDSCH_TRANS_USING_MCS27)+
                SUM(PDSCH_TRANS_USING_MCS28)+
                SUM(PDSCH_TRANS_USING_MCS29)+
                SUM(PDSCH_TRANS_USING_MCS30)+
                SUM(PDSCH_TRANS_USING_MCS31)) /
                (SUM(PDSCH_TRANS_NACK_MCS0)+
                SUM(PDSCH_TRANS_NACK_MCS1)+
                SUM(PDSCH_TRANS_NACK_MCS2)+
                SUM(PDSCH_TRANS_NACK_MCS3)+
                SUM(PDSCH_TRANS_NACK_MCS4)+
                SUM(PDSCH_TRANS_NACK_MCS5)+
                SUM(PDSCH_TRANS_NACK_MCS6)+
                SUM(PDSCH_TRANS_NACK_MCS7)+
                SUM(PDSCH_TRANS_NACK_MCS8)+
                SUM(PDSCH_TRANS_NACK_MCS9)+
                SUM(PDSCH_TRANS_NACK_MCS10)+
                SUM(PDSCH_TRANS_NACK_MCS11)+
                SUM(PDSCH_TRANS_NACK_MCS12)+
                SUM(PDSCH_TRANS_NACK_MCS13)+
                SUM(PDSCH_TRANS_NACK_MCS14)+
                SUM(PDSCH_TRANS_NACK_MCS15)+
                SUM(PDSCH_TRANS_NACK_MCS16)+
                SUM(PDSCH_TRANS_NACK_MCS17)+
                SUM(PDSCH_TRANS_NACK_MCS18)+
                SUM(PDSCH_TRANS_NACK_MCS19)+
                SUM(PDSCH_TRANS_NACK_MCS20)+
                SUM(PDSCH_TRANS_NACK_MCS21)+
                SUM(PDSCH_TRANS_NACK_MCS22)+
                SUM(PDSCH_TRANS_NACK_MCS23)+
                SUM(PDSCH_TRANS_NACK_MCS24)+
                SUM(PDSCH_TRANS_NACK_MCS25)+
                SUM(PDSCH_TRANS_NACK_MCS26)+
                SUM(PDSCH_TRANS_NACK_MCS27)+
                SUM(PDSCH_TRANS_NACK_MCS28)+
                SUM(PDSCH_TRANS_NACK_MCS29)+
                SUM(PDSCH_TRANS_NACK_MCS30)+
                SUM(PDSCH_TRANS_NACK_MCS31))
                ) *100 ,2) AS LTE_139B,
        SUM(PDSCH_TRANS_NACK_MCS0) AS PDSCH_TRANS_NACK_MCS0,
        SUM(PDSCH_TRANS_NACK_MCS1) AS PDSCH_TRANS_NACK_MCS1,
        SUM(PDSCH_TRANS_NACK_MCS2) AS PDSCH_TRANS_NACK_MCS2,
        SUM(PDSCH_TRANS_NACK_MCS3) AS PDSCH_TRANS_NACK_MCS3,
        SUM(PDSCH_TRANS_NACK_MCS4) AS PDSCH_TRANS_NACK_MCS4,
        SUM(PDSCH_TRANS_NACK_MCS5) AS PDSCH_TRANS_NACK_MCS5,
        SUM(PDSCH_TRANS_NACK_MCS6) AS PDSCH_TRANS_NACK_MCS6,
        SUM(PDSCH_TRANS_NACK_MCS7) AS PDSCH_TRANS_NACK_MCS7,
        SUM(PDSCH_TRANS_NACK_MCS8) AS PDSCH_TRANS_NACK_MCS8,
        SUM(PDSCH_TRANS_NACK_MCS9) AS PDSCH_TRANS_NACK_MCS9,
        SUM(PDSCH_TRANS_NACK_MCS10) AS PDSCH_TRANS_NACK_MCS10,
        SUM(PDSCH_TRANS_NACK_MCS11) AS PDSCH_TRANS_NACK_MCS11,
        SUM(PDSCH_TRANS_NACK_MCS12) AS PDSCH_TRANS_NACK_MCS12,
        SUM(PDSCH_TRANS_NACK_MCS13) AS PDSCH_TRANS_NACK_MCS13,
        SUM(PDSCH_TRANS_NACK_MCS14) AS PDSCH_TRANS_NACK_MCS14,
        SUM(PDSCH_TRANS_NACK_MCS15) AS PDSCH_TRANS_NACK_MCS15,
        SUM(PDSCH_TRANS_NACK_MCS16) AS PDSCH_TRANS_NACK_MCS16,
        SUM(PDSCH_TRANS_NACK_MCS17) AS PDSCH_TRANS_NACK_MCS17,
        SUM(PDSCH_TRANS_NACK_MCS18) AS PDSCH_TRANS_NACK_MCS18,
        SUM(PDSCH_TRANS_NACK_MCS19) AS PDSCH_TRANS_NACK_MCS19,
        SUM(PDSCH_TRANS_NACK_MCS20) AS PDSCH_TRANS_NACK_MCS20,
        SUM(PDSCH_TRANS_NACK_MCS21) AS PDSCH_TRANS_NACK_MCS21,
        SUM(PDSCH_TRANS_NACK_MCS22) AS PDSCH_TRANS_NACK_MCS22,
        SUM(PDSCH_TRANS_NACK_MCS23) AS PDSCH_TRANS_NACK_MCS23,
        SUM(PDSCH_TRANS_NACK_MCS24) AS PDSCH_TRANS_NACK_MCS24,
        SUM(PDSCH_TRANS_NACK_MCS25) AS PDSCH_TRANS_NACK_MCS25,
        SUM(PDSCH_TRANS_NACK_MCS26) AS PDSCH_TRANS_NACK_MCS26,
        SUM(PDSCH_TRANS_NACK_MCS27) AS PDSCH_TRANS_NACK_MCS27,
        SUM(PDSCH_TRANS_NACK_MCS28) AS PDSCH_TRANS_NACK_MCS28,
        SUM(PDSCH_TRANS_NACK_MCS29) AS PDSCH_TRANS_NACK_MCS29,
        SUM(PDSCH_TRANS_NACK_MCS30) AS PDSCH_TRANS_NACK_MCS30,
        SUM(PDSCH_TRANS_NACK_MCS31) AS PDSCH_TRANS_NACK_MCS31,
        SUM(PDSCH_TRANS_USING_MCS0) AS PDSCH_TRANS_USING_MCS0,
        SUM(PDSCH_TRANS_USING_MCS1) AS PDSCH_TRANS_USING_MCS1,
        SUM(PDSCH_TRANS_USING_MCS2) AS PDSCH_TRANS_USING_MCS2,
        SUM(PDSCH_TRANS_USING_MCS3) AS PDSCH_TRANS_USING_MCS3,
        SUM(PDSCH_TRANS_USING_MCS4) AS PDSCH_TRANS_USING_MCS4,
        SUM(PDSCH_TRANS_USING_MCS5) AS PDSCH_TRANS_USING_MCS5,
        SUM(PDSCH_TRANS_USING_MCS6) AS PDSCH_TRANS_USING_MCS6,
        SUM(PDSCH_TRANS_USING_MCS7) AS PDSCH_TRANS_USING_MCS7,
        SUM(PDSCH_TRANS_USING_MCS8) AS PDSCH_TRANS_USING_MCS8,
        SUM(PDSCH_TRANS_USING_MCS9) AS PDSCH_TRANS_USING_MCS9,
        SUM(PDSCH_TRANS_USING_MCS10) AS PDSCH_TRANS_USING_MCS10,
        SUM(PDSCH_TRANS_USING_MCS11) AS PDSCH_TRANS_USING_MCS11,
        SUM(PDSCH_TRANS_USING_MCS12) AS PDSCH_TRANS_USING_MCS12,
        SUM(PDSCH_TRANS_USING_MCS13) AS PDSCH_TRANS_USING_MCS13,
        SUM(PDSCH_TRANS_USING_MCS14) AS PDSCH_TRANS_USING_MCS14,
        SUM(PDSCH_TRANS_USING_MCS15) AS PDSCH_TRANS_USING_MCS15,
        SUM(PDSCH_TRANS_USING_MCS16) AS PDSCH_TRANS_USING_MCS16,
        SUM(PDSCH_TRANS_USING_MCS17) AS PDSCH_TRANS_USING_MCS17,
        SUM(PDSCH_TRANS_USING_MCS18) AS PDSCH_TRANS_USING_MCS18,
        SUM(PDSCH_TRANS_USING_MCS19) AS PDSCH_TRANS_USING_MCS19,
        SUM(PDSCH_TRANS_USING_MCS20) AS PDSCH_TRANS_USING_MCS20,
        SUM(PDSCH_TRANS_USING_MCS21) AS PDSCH_TRANS_USING_MCS21,
        SUM(PDSCH_TRANS_USING_MCS22) AS PDSCH_TRANS_USING_MCS22,
        SUM(PDSCH_TRANS_USING_MCS23) AS PDSCH_TRANS_USING_MCS23,
        SUM(PDSCH_TRANS_USING_MCS24) AS PDSCH_TRANS_USING_MCS24,
        SUM(PDSCH_TRANS_USING_MCS25) AS PDSCH_TRANS_USING_MCS25,
        SUM(PDSCH_TRANS_USING_MCS26) AS PDSCH_TRANS_USING_MCS26,
        SUM(PDSCH_TRANS_USING_MCS27) AS PDSCH_TRANS_USING_MCS27,
        SUM(PDSCH_TRANS_USING_MCS28) AS PDSCH_TRANS_USING_MCS28,
        SUM(PDSCH_TRANS_USING_MCS29) AS PDSCH_TRANS_USING_MCS29,
        SUM(PDSCH_TRANS_USING_MCS30) AS PDSCH_TRANS_USING_MCS30,
        SUM(PDSCH_TRANS_USING_MCS31) AS PDSCH_TRANS_USING_MCS31,
        ----------------- END LTE_139B
        (SUM(PUSCH_TRANS_NACK_MCS0)+
        SUM(PUSCH_TRANS_NACK_MCS1)+
        SUM(PUSCH_TRANS_NACK_MCS2)+
        SUM(PUSCH_TRANS_NACK_MCS3)+
        SUM(PUSCH_TRANS_NACK_MCS4)+
        SUM(PUSCH_TRANS_NACK_MCS5)+
        SUM(PUSCH_TRANS_NACK_MCS6)+
        SUM(PUSCH_TRANS_NACK_MCS7)+
        SUM(PUSCH_TRANS_NACK_MCS8)+
        SUM(PUSCH_TRANS_NACK_MCS9)+
        SUM(PUSCH_TRANS_NACK_MCS10)+
        SUM(PUSCH_TRANS_NACK_MCS11)+
        SUM(PUSCH_TRANS_NACK_MCS12)+
        SUM(PUSCH_TRANS_NACK_MCS13)+
        SUM(PUSCH_TRANS_NACK_MCS14)+
        SUM(PUSCH_TRANS_NACK_MCS15)+
        SUM(PUSCH_TRANS_NACK_MCS16)+
        SUM(PUSCH_TRANS_NACK_MCS17)+
        SUM(PUSCH_TRANS_NACK_MCS18)+
        SUM(PUSCH_TRANS_NACK_MCS19)+
        SUM(PUSCH_TRANS_NACK_MCS20)+
        SUM(PUSCH_TRANS_NACK_MCS21)+
        SUM(PUSCH_TRANS_NACK_MCS22)+
        SUM(PUSCH_TRANS_NACK_MCS23)+
        SUM(PUSCH_TRANS_NACK_MCS24)+
        SUM(PUSCH_TRANS_NACK_MCS25)+
        SUM(PUSCH_TRANS_NACK_MCS26)+
        SUM(PUSCH_TRANS_NACK_MCS27)+
        SUM(PUSCH_TRANS_NACK_MCS28)) AS  LTE_140B_NUM,
        (SUM(PUSCH_TRANS_USING_MCS0)+
        SUM(PUSCH_TRANS_USING_MCS1)+
        SUM(PUSCH_TRANS_USING_MCS2)+
        SUM(PUSCH_TRANS_USING_MCS3)+
        SUM(PUSCH_TRANS_USING_MCS4)+
        SUM(PUSCH_TRANS_USING_MCS5)+
        SUM(PUSCH_TRANS_USING_MCS6)+
        SUM(PUSCH_TRANS_USING_MCS7)+
        SUM(PUSCH_TRANS_USING_MCS8)+
        SUM(PUSCH_TRANS_USING_MCS9)+
        SUM(PUSCH_TRANS_USING_MCS10)+
        SUM(PUSCH_TRANS_USING_MCS11)+
        SUM(PUSCH_TRANS_USING_MCS12)+
        SUM(PUSCH_TRANS_USING_MCS13)+
        SUM(PUSCH_TRANS_USING_MCS14)+
        SUM(PUSCH_TRANS_USING_MCS15)+
        SUM(PUSCH_TRANS_USING_MCS16)+
        SUM(PUSCH_TRANS_USING_MCS17)+
        SUM(PUSCH_TRANS_USING_MCS18)+
        SUM(PUSCH_TRANS_USING_MCS19)+
        SUM(PUSCH_TRANS_USING_MCS20)+
        SUM(PUSCH_TRANS_USING_MCS21)+
        SUM(PUSCH_TRANS_USING_MCS22)+
        SUM(PUSCH_TRANS_USING_MCS23)+
        SUM(PUSCH_TRANS_USING_MCS24)+
        SUM(PUSCH_TRANS_USING_MCS25)+
        SUM(PUSCH_TRANS_USING_MCS26)+
        SUM(PUSCH_TRANS_USING_MCS27)+
        SUM(PUSCH_TRANS_USING_MCS28)) AS LTE_140B_DEN,
        ROUND ( DECODE(
                (SUM(PUSCH_TRANS_USING_MCS0)+
                SUM(PUSCH_TRANS_USING_MCS1)+
                SUM(PUSCH_TRANS_USING_MCS2)+
                SUM(PUSCH_TRANS_USING_MCS3)+
                SUM(PUSCH_TRANS_USING_MCS4)+
                SUM(PUSCH_TRANS_USING_MCS5)+
                SUM(PUSCH_TRANS_USING_MCS6)+
                SUM(PUSCH_TRANS_USING_MCS7)+
                SUM(PUSCH_TRANS_USING_MCS8)+
                SUM(PUSCH_TRANS_USING_MCS9)+
                SUM(PUSCH_TRANS_USING_MCS10)+
                SUM(PUSCH_TRANS_USING_MCS11)+
                SUM(PUSCH_TRANS_USING_MCS12)+
                SUM(PUSCH_TRANS_USING_MCS13)+
                SUM(PUSCH_TRANS_USING_MCS14)+
                SUM(PUSCH_TRANS_USING_MCS15)+
                SUM(PUSCH_TRANS_USING_MCS16)+
                SUM(PUSCH_TRANS_USING_MCS17)+
                SUM(PUSCH_TRANS_USING_MCS18)+
                SUM(PUSCH_TRANS_USING_MCS19)+
                SUM(PUSCH_TRANS_USING_MCS20)+
                SUM(PUSCH_TRANS_USING_MCS21)+
                SUM(PUSCH_TRANS_USING_MCS22)+
                SUM(PUSCH_TRANS_USING_MCS23)+
                SUM(PUSCH_TRANS_USING_MCS24)+
                SUM(PUSCH_TRANS_USING_MCS25)+
                SUM(PUSCH_TRANS_USING_MCS26)+
                SUM(PUSCH_TRANS_USING_MCS27)+
                SUM(PUSCH_TRANS_USING_MCS28)), 0, 0,
                (
                (SUM(PUSCH_TRANS_NACK_MCS0)+
                SUM(PUSCH_TRANS_NACK_MCS1)+
                SUM(PUSCH_TRANS_NACK_MCS2)+
                SUM(PUSCH_TRANS_NACK_MCS3)+
                SUM(PUSCH_TRANS_NACK_MCS4)+
                SUM(PUSCH_TRANS_NACK_MCS5)+
                SUM(PUSCH_TRANS_NACK_MCS6)+
                SUM(PUSCH_TRANS_NACK_MCS7)+
                SUM(PUSCH_TRANS_NACK_MCS8)+
                SUM(PUSCH_TRANS_NACK_MCS9)+
                SUM(PUSCH_TRANS_NACK_MCS10)+
                SUM(PUSCH_TRANS_NACK_MCS11)+
                SUM(PUSCH_TRANS_NACK_MCS12)+
                SUM(PUSCH_TRANS_NACK_MCS13)+
                SUM(PUSCH_TRANS_NACK_MCS14)+
                SUM(PUSCH_TRANS_NACK_MCS15)+
                SUM(PUSCH_TRANS_NACK_MCS16)+
                SUM(PUSCH_TRANS_NACK_MCS17)+
                SUM(PUSCH_TRANS_NACK_MCS18)+
                SUM(PUSCH_TRANS_NACK_MCS19)+
                SUM(PUSCH_TRANS_NACK_MCS20)+
                SUM(PUSCH_TRANS_NACK_MCS21)+
                SUM(PUSCH_TRANS_NACK_MCS22)+
                SUM(PUSCH_TRANS_NACK_MCS23)+
                SUM(PUSCH_TRANS_NACK_MCS24)+
                SUM(PUSCH_TRANS_NACK_MCS25)+
                SUM(PUSCH_TRANS_NACK_MCS26)+
                SUM(PUSCH_TRANS_NACK_MCS27)+
                SUM(PUSCH_TRANS_NACK_MCS28)) /
                (SUM(PUSCH_TRANS_USING_MCS0)+
                SUM(PUSCH_TRANS_USING_MCS1)+
                SUM(PUSCH_TRANS_USING_MCS2)+
                SUM(PUSCH_TRANS_USING_MCS3)+
                SUM(PUSCH_TRANS_USING_MCS4)+
                SUM(PUSCH_TRANS_USING_MCS5)+
                SUM(PUSCH_TRANS_USING_MCS6)+
                SUM(PUSCH_TRANS_USING_MCS7)+
                SUM(PUSCH_TRANS_USING_MCS8)+
                SUM(PUSCH_TRANS_USING_MCS9)+
                SUM(PUSCH_TRANS_USING_MCS10)+
                SUM(PUSCH_TRANS_USING_MCS11)+
                SUM(PUSCH_TRANS_USING_MCS12)+
                SUM(PUSCH_TRANS_USING_MCS13)+
                SUM(PUSCH_TRANS_USING_MCS14)+
                SUM(PUSCH_TRANS_USING_MCS15)+
                SUM(PUSCH_TRANS_USING_MCS16)+
                SUM(PUSCH_TRANS_USING_MCS17)+
                SUM(PUSCH_TRANS_USING_MCS18)+
                SUM(PUSCH_TRANS_USING_MCS19)+
                SUM(PUSCH_TRANS_USING_MCS20)+
                SUM(PUSCH_TRANS_USING_MCS21)+
                SUM(PUSCH_TRANS_USING_MCS22)+
                SUM(PUSCH_TRANS_USING_MCS23)+
                SUM(PUSCH_TRANS_USING_MCS24)+
                SUM(PUSCH_TRANS_USING_MCS25)+
                SUM(PUSCH_TRANS_USING_MCS26)+
                SUM(PUSCH_TRANS_USING_MCS27)+
                SUM(PUSCH_TRANS_USING_MCS28))
                )*100
                )  ,2) AS LTE_140B,

        SUM(PUSCH_TRANS_NACK_MCS0) AS PUSCH_TRANS_NACK_MCS0,
        SUM(PUSCH_TRANS_NACK_MCS1) AS PUSCH_TRANS_NACK_MCS1,
        SUM(PUSCH_TRANS_NACK_MCS2) AS PUSCH_TRANS_NACK_MCS2,
        SUM(PUSCH_TRANS_NACK_MCS3) AS PUSCH_TRANS_NACK_MCS3,
        SUM(PUSCH_TRANS_NACK_MCS4) AS PUSCH_TRANS_NACK_MCS4,
        SUM(PUSCH_TRANS_NACK_MCS5) AS PUSCH_TRANS_NACK_MCS5,
        SUM(PUSCH_TRANS_NACK_MCS6) AS PUSCH_TRANS_NACK_MCS6,
        SUM(PUSCH_TRANS_NACK_MCS7) AS PUSCH_TRANS_NACK_MCS7,
        SUM(PUSCH_TRANS_NACK_MCS8) AS PUSCH_TRANS_NACK_MCS8,
        SUM(PUSCH_TRANS_NACK_MCS9) AS PUSCH_TRANS_NACK_MCS9,
        SUM(PUSCH_TRANS_NACK_MCS10) AS PUSCH_TRANS_NACK_MCS10,
        SUM(PUSCH_TRANS_NACK_MCS11) AS PUSCH_TRANS_NACK_MCS11,
        SUM(PUSCH_TRANS_NACK_MCS12) AS PUSCH_TRANS_NACK_MCS12,
        SUM(PUSCH_TRANS_NACK_MCS13) AS PUSCH_TRANS_NACK_MCS13,
        SUM(PUSCH_TRANS_NACK_MCS14) AS PUSCH_TRANS_NACK_MCS14,
        SUM(PUSCH_TRANS_NACK_MCS15) AS PUSCH_TRANS_NACK_MCS15,
        SUM(PUSCH_TRANS_NACK_MCS16) AS PUSCH_TRANS_NACK_MCS16,
        SUM(PUSCH_TRANS_NACK_MCS17) AS PUSCH_TRANS_NACK_MCS17,
        SUM(PUSCH_TRANS_NACK_MCS18) AS PUSCH_TRANS_NACK_MCS18,
        SUM(PUSCH_TRANS_NACK_MCS19) AS PUSCH_TRANS_NACK_MCS19,
        SUM(PUSCH_TRANS_NACK_MCS20) AS PUSCH_TRANS_NACK_MCS20,
        SUM(PUSCH_TRANS_NACK_MCS21) AS PUSCH_TRANS_NACK_MCS21,
        SUM(PUSCH_TRANS_NACK_MCS22) AS PUSCH_TRANS_NACK_MCS22,
        SUM(PUSCH_TRANS_NACK_MCS23) AS PUSCH_TRANS_NACK_MCS23,
        SUM(PUSCH_TRANS_NACK_MCS24) AS PUSCH_TRANS_NACK_MCS24,
        SUM(PUSCH_TRANS_NACK_MCS25) AS PUSCH_TRANS_NACK_MCS25,
        SUM(PUSCH_TRANS_NACK_MCS26) AS PUSCH_TRANS_NACK_MCS26,
        SUM(PUSCH_TRANS_NACK_MCS27) AS PUSCH_TRANS_NACK_MCS27,
        SUM(PUSCH_TRANS_NACK_MCS28) AS PUSCH_TRANS_NACK_MCS28,
        SUM(PUSCH_TRANS_USING_MCS0) AS PUSCH_TRANS_USING_MCS0,
        SUM(PUSCH_TRANS_USING_MCS1) AS PUSCH_TRANS_USING_MCS1,
        SUM(PUSCH_TRANS_USING_MCS2) AS PUSCH_TRANS_USING_MCS2,
        SUM(PUSCH_TRANS_USING_MCS3) AS PUSCH_TRANS_USING_MCS3,
        SUM(PUSCH_TRANS_USING_MCS4) AS PUSCH_TRANS_USING_MCS4,
        SUM(PUSCH_TRANS_USING_MCS5) AS PUSCH_TRANS_USING_MCS5,
        SUM(PUSCH_TRANS_USING_MCS6) AS PUSCH_TRANS_USING_MCS6,
        SUM(PUSCH_TRANS_USING_MCS7) AS PUSCH_TRANS_USING_MCS7,
        SUM(PUSCH_TRANS_USING_MCS8) AS PUSCH_TRANS_USING_MCS8,
        SUM(PUSCH_TRANS_USING_MCS9) AS PUSCH_TRANS_USING_MCS9,
        SUM(PUSCH_TRANS_USING_MCS10) AS PUSCH_TRANS_USING_MCS10,
        SUM(PUSCH_TRANS_USING_MCS11) AS PUSCH_TRANS_USING_MCS11,
        SUM(PUSCH_TRANS_USING_MCS12) AS PUSCH_TRANS_USING_MCS12,
        SUM(PUSCH_TRANS_USING_MCS13) AS PUSCH_TRANS_USING_MCS13,
        SUM(PUSCH_TRANS_USING_MCS14) AS PUSCH_TRANS_USING_MCS14,
        SUM(PUSCH_TRANS_USING_MCS15) AS PUSCH_TRANS_USING_MCS15,
        SUM(PUSCH_TRANS_USING_MCS16) AS PUSCH_TRANS_USING_MCS16,
        SUM(PUSCH_TRANS_USING_MCS17) AS PUSCH_TRANS_USING_MCS17,
        SUM(PUSCH_TRANS_USING_MCS18) AS PUSCH_TRANS_USING_MCS18,
        SUM(PUSCH_TRANS_USING_MCS19) AS PUSCH_TRANS_USING_MCS19,
        SUM(PUSCH_TRANS_USING_MCS20) AS PUSCH_TRANS_USING_MCS20,
        SUM(PUSCH_TRANS_USING_MCS21) AS PUSCH_TRANS_USING_MCS21,
        SUM(PUSCH_TRANS_USING_MCS22) AS PUSCH_TRANS_USING_MCS22,
        SUM(PUSCH_TRANS_USING_MCS23) AS PUSCH_TRANS_USING_MCS23,
        SUM(PUSCH_TRANS_USING_MCS24) AS PUSCH_TRANS_USING_MCS24,
        SUM(PUSCH_TRANS_USING_MCS25) AS PUSCH_TRANS_USING_MCS25,
        SUM(PUSCH_TRANS_USING_MCS26) AS PUSCH_TRANS_USING_MCS26,
        SUM(PUSCH_TRANS_USING_MCS27) AS PUSCH_TRANS_USING_MCS27,
        SUM(PUSCH_TRANS_USING_MCS28) AS PUSCH_TRANS_USING_MCS28,
        ----------------- END LTE_140B
        MAX(PDCP_DATA_RATE_MAX_UL) AS LTE_288B,
        SUM(PDCP_DATA_RATE_MAX_UL) AS PDCP_DATA_RATE_MAX_UL,
        ----------------- END LTE_288B
        MAX(PDCP_DATA_RATE_MAX_DL) AS LTE_291B,
        SUM(PDCP_DATA_RATE_MAX_DL) AS PDCP_DATA_RATE_MAX_DL,
        ----------------- END LTE_291B
        SUM(EPS_BEARER_SETUP_COMPLETIONS) AS LTE_5017A_NUM,
        SUM(EPS_BEARER_SETUP_ATTEMPTS) AS LTE_5017A_DEN,
        ROUND (
                (
                DECODE (
                        SUM(EPS_BEARER_SETUP_ATTEMPTS), 0, 0,
                        SUM(EPS_BEARER_SETUP_COMPLETIONS) /
                        SUM(EPS_BEARER_SETUP_ATTEMPTS)
                        ) *100
                ),2
        ) as LTE_5017A,
        SUM(EPS_BEARER_SETUP_COMPLETIONS) AS EPS_BEARER_SETUP_COMPLETIONS,
        SUM(EPS_BEARER_SETUP_ATTEMPTS) AS EPS_BEARER_SETUP_ATTEMPTS,
        ----------------- END LTE_5017A
        (SUM(ENB_EPS_BEARER_REL_REQ_RNL)+
        SUM(ENB_EPS_BEARER_REL_REQ_TNL)+
        SUM(ENB_EPS_BEARER_REL_REQ_OTH)) AS LTE_5025D_NUM,
        (SUM(EPC_EPS_BEARER_REL_REQ_NORM)+
        SUM(EPC_EPS_BEARER_REL_REQ_DETACH)+
        SUM(EPC_EPS_BEARER_REL_REQ_RNL)+
        SUM(EPC_EPS_BEARER_REL_REQ_OTH)+
        SUM(ENB_EPSBEAR_REL_REQ_RNL_REDIR)+
        SUM(ENB_EPS_BEARER_REL_REQ_RNL)+
        SUM(ENB_EPS_BEARER_REL_REQ_TNL)+
        SUM(ENB_EPS_BEARER_REL_REQ_OTH)+
        SUM(PRE_EMPT_GBR_BEARER)+
        SUM(PRE_EMPT_NON_GBR_BEARER)) AS LTE_5025D_DEN,
        ROUND (
                (

                                DECODE (
                                                (
                                                SUM(EPC_EPS_BEARER_REL_REQ_NORM)+
                                                SUM(EPC_EPS_BEARER_REL_REQ_DETACH)+
                                                SUM(EPC_EPS_BEARER_REL_REQ_RNL)+
                                                SUM(EPC_EPS_BEARER_REL_REQ_OTH)+
                                                SUM(ENB_EPSBEAR_REL_REQ_RNL_REDIR)+
                                                SUM(ENB_EPS_BEARER_REL_REQ_RNL)+
                                                SUM(ENB_EPS_BEARER_REL_REQ_TNL)+
                                                SUM(ENB_EPS_BEARER_REL_REQ_OTH)+
                                                SUM(PRE_EMPT_GBR_BEARER)+
                                                SUM(PRE_EMPT_NON_GBR_BEARER)
                                                ), 0, 0,

                                                        (
                                                                SUM(ENB_EPS_BEARER_REL_REQ_RNL)+
                                                                SUM(ENB_EPS_BEARER_REL_REQ_TNL)+
                                                                SUM(ENB_EPS_BEARER_REL_REQ_OTH)
                                                        ) /
                                                        (
                                                                SUM(EPC_EPS_BEARER_REL_REQ_NORM)+
                                                                SUM(EPC_EPS_BEARER_REL_REQ_DETACH)+
                                                                SUM(EPC_EPS_BEARER_REL_REQ_RNL)+
                                                                SUM(EPC_EPS_BEARER_REL_REQ_OTH)+
                                                                SUM(ENB_EPSBEAR_REL_REQ_RNL_REDIR)+
                                                                SUM(ENB_EPS_BEARER_REL_REQ_RNL)+
                                                                SUM(ENB_EPS_BEARER_REL_REQ_TNL)+
                                                                SUM(ENB_EPS_BEARER_REL_REQ_OTH)+
                                                                SUM(PRE_EMPT_GBR_BEARER)+
                                                                SUM(PRE_EMPT_NON_GBR_BEARER)
                                                        )

                                        )
                        *100
                ),2
        ) as LTE_5025D,

        SUM(EPC_EPS_BEARER_REL_REQ_NORM) AS EPC_EPS_BEARER_REL_REQ_NORM,
        SUM(EPC_EPS_BEARER_REL_REQ_DETACH) AS EPC_EPS_BEARER_REL_REQ_DETACH,
        SUM(EPC_EPS_BEARER_REL_REQ_RNL) AS EPC_EPS_BEARER_REL_REQ_RNL,
        SUM(EPC_EPS_BEARER_REL_REQ_OTH) AS EPC_EPS_BEARER_REL_REQ_OTH,
        SUM(ENB_EPSBEAR_REL_REQ_RNL_REDIR) AS ENB_EPSBEAR_REL_REQ_RNL_REDIR,
        SUM(ENB_EPS_BEARER_REL_REQ_RNL) AS ENB_EPS_BEARER_REL_REQ_RNL,
        SUM(ENB_EPS_BEARER_REL_REQ_TNL) AS ENB_EPS_BEARER_REL_REQ_TNL,
        SUM(ENB_EPS_BEARER_REL_REQ_OTH) AS ENB_EPS_BEARER_REL_REQ_OTH,
        SUM(PRE_EMPT_GBR_BEARER) AS PRE_EMPT_GBR_BEARER,
        SUM(PRE_EMPT_NON_GBR_BEARER) AS PRE_EMPT_NON_GBR_BEARER,
        ----------------- END LTE_5025D
        SUM(DISC_RRC_PAGING) AS LTE_5031B_NUM,
        SUM(RRC_PAGING_REQUESTS) AS LTE_5031B_DEN,
        ROUND ( DECODE(SUM(RRC_PAGING_REQUESTS), 0, 0, SUM(DISC_RRC_PAGING) / SUM(RRC_PAGING_REQUESTS)) *100 ,2) AS LTE_5031B,
        SUM(DISC_RRC_PAGING) AS DISC_RRC_PAGING,
        SUM(RRC_PAGING_REQUESTS) AS RRC_PAGING_REQUESTS,
        ----------------- END LTE_5031B
        ROUND(AVG(PDCP_SDU_DELAY_DL_DTCH_MEAN),2) AS LTE_5134A,
        SUM(PDCP_SDU_DELAY_DL_DTCH_MEAN) AS PDCP_SDU_DELAY_DL_DTCH_MEAN,
        ----------------- END LTE_5134A
        ROUND(AVG(PDCP_SDU_DELAY_UL_DTCH_MEAN),2) AS LTE_5137A,
        SUM(PDCP_SDU_DELAY_UL_DTCH_MEAN) AS PDCP_SDU_DELAY_UL_DTCH_MEAN,
        ----------------- END LTE_5137A
        SUM(PDCP_SDU_VOL_DL) AS PDCP_SDU_VOL_DL,
        ROUND(SUM(PDCP_SDU_VOL_DL)/(1000*1000),2) AS LTE_5212A,
        ----------------- END LTE_5212A
        --SUM(PDCP_SDU_VOL_UL) AS PDCP_SDU_VOL_UL,
        ROUND(SUM(PDCP_SDU_VOL_UL)/(1000*1000),2) AS LTE_5213A,
        ----------------- END LTE_5213A
        SUM(SIGN_CONN_ESTAB_COMP) AS LTE_5218C_NUM,
        (SUM(SIGN_CONN_ESTAB_ATT_MO_S)+
        SUM(SIGN_CONN_ESTAB_ATT_MT)+
        SUM(SIGN_CONN_ESTAB_ATT_MO_D)+
        SUM(SIGN_CONN_ESTAB_ATT_OTHERS)+
        SUM(SIGN_CONN_ESTAB_ATT_EMG)) AS LTE_5218C_DEN,
        ROUND (
                (

                                DECODE (
                                        (
                                                SUM(SIGN_CONN_ESTAB_ATT_MO_S)+
                                                SUM(SIGN_CONN_ESTAB_ATT_MT)+
                                                SUM(SIGN_CONN_ESTAB_ATT_MO_D)+
                                                SUM(SIGN_CONN_ESTAB_ATT_OTHERS)+
                                                SUM(SIGN_CONN_ESTAB_ATT_EMG)
                                        ), 0, 0,
                                        SUM(SIGN_CONN_ESTAB_COMP) /
                                                (
                                                        SUM(SIGN_CONN_ESTAB_ATT_MO_S)+
                                                        SUM(SIGN_CONN_ESTAB_ATT_MT)+
                                                        SUM(SIGN_CONN_ESTAB_ATT_MO_D)+
                                                        SUM(SIGN_CONN_ESTAB_ATT_OTHERS)+
                                                        SUM(SIGN_CONN_ESTAB_ATT_EMG)
                                                )
                                        )
                        *100
                ),2
        ) as LTE_5218C,

        SUM(SIGN_CONN_ESTAB_COMP) AS  SIGN_CONN_ESTAB_COMP,
        SUM(SIGN_CONN_ESTAB_ATT_MO_S) AS SIGN_CONN_ESTAB_ATT_MO_S,
        SUM(SIGN_CONN_ESTAB_ATT_MT) AS SIGN_CONN_ESTAB_ATT_MT,
        SUM(SIGN_CONN_ESTAB_ATT_MO_D) AS SIGN_CONN_ESTAB_ATT_MO_D,
        SUM(SIGN_CONN_ESTAB_ATT_OTHERS) AS SIGN_CONN_ESTAB_ATT_OTHERS,
        SUM(SIGN_CONN_ESTAB_ATT_EMG) AS SIGN_CONN_ESTAB_ATT_EMG,
        ----------------- END LTE_5218C
        SUM(PDCP_SDU_VOL_UL) AS LTE_5289D_NUM,
        SUM(ACTIVE_TTI_UL) AS LTE_5289D_DEN,
        ROUND ( DECODE(SUM(ACTIVE_TTI_UL), 0, 0, SUM(PDCP_SDU_VOL_UL) / SUM(ACTIVE_TTI_UL))*8 ,2) AS LTE_5289D,
        SUM(PDCP_SDU_VOL_UL) AS PDCP_SDU_VOL_UL,
        SUM(ACTIVE_TTI_UL) AS ACTIVE_TTI_UL,
        ----------------- END LTE_5289D
        SUM(PDCP_SDU_VOL_DL) AS LTE_5292D_NUM,
        SUM(ACTIVE_TTI_DL) AS LTE_5292D_DEN,
        ROUND ( DECODE(SUM(ACTIVE_TTI_DL), 0, 0, SUM(PDCP_SDU_VOL_DL) / SUM(ACTIVE_TTI_DL))*8 ,2) AS LTE_5292D,
        --SUM(PDCP_SDU_VOL_DL) AS PDCP_SDU_VOL_DL,
        SUM(ACTIVE_TTI_DL) AS ACTIVE_TTI_DL,
        ----------------- END LTE_5292D
        (SUM(1*UE_REP_CQI_LEVEL_01)+
        SUM(2*UE_REP_CQI_LEVEL_02)+
        SUM(3*UE_REP_CQI_LEVEL_03)+
        SUM(4*UE_REP_CQI_LEVEL_04)+
        SUM(5*UE_REP_CQI_LEVEL_05)+
        SUM(6*UE_REP_CQI_LEVEL_06)+
        SUM(7*UE_REP_CQI_LEVEL_07)+
        SUM(8*UE_REP_CQI_LEVEL_08)+
        SUM(9*UE_REP_CQI_LEVEL_09)+
        SUM(10*UE_REP_CQI_LEVEL_10)+
        SUM(11*UE_REP_CQI_LEVEL_11)+
        SUM(12*UE_REP_CQI_LEVEL_12)+
        SUM(13*UE_REP_CQI_LEVEL_13)+
        SUM(14*UE_REP_CQI_LEVEL_14)+
        SUM(15*UE_REP_CQI_LEVEL_15)) AS LTE_5427A_NUM,
        (SUM(UE_REP_CQI_LEVEL_00)+SUM(UE_REP_CQI_LEVEL_01)+
        SUM(UE_REP_CQI_LEVEL_02)+SUM(UE_REP_CQI_LEVEL_03)+
        SUM(UE_REP_CQI_LEVEL_04)+SUM(UE_REP_CQI_LEVEL_05)+
        SUM(UE_REP_CQI_LEVEL_06)+SUM(UE_REP_CQI_LEVEL_07)+
        SUM(UE_REP_CQI_LEVEL_08)+SUM(UE_REP_CQI_LEVEL_09)+
        SUM(UE_REP_CQI_LEVEL_10)+SUM(UE_REP_CQI_LEVEL_11)+
        SUM(UE_REP_CQI_LEVEL_12)+SUM(UE_REP_CQI_LEVEL_13)+
        SUM(UE_REP_CQI_LEVEL_14)+SUM(UE_REP_CQI_LEVEL_15)) AS LTE_5427A_DEN,
        ROUND (
                (

                                DECODE
                                        (
                                                (
                                                        SUM(UE_REP_CQI_LEVEL_00)+SUM(UE_REP_CQI_LEVEL_01)+
                                                        SUM(UE_REP_CQI_LEVEL_02)+SUM(UE_REP_CQI_LEVEL_03)+
                                                        SUM(UE_REP_CQI_LEVEL_04)+SUM(UE_REP_CQI_LEVEL_05)+
                                                        SUM(UE_REP_CQI_LEVEL_06)+SUM(UE_REP_CQI_LEVEL_07)+
                                                        SUM(UE_REP_CQI_LEVEL_08)+SUM(UE_REP_CQI_LEVEL_09)+
                                                        SUM(UE_REP_CQI_LEVEL_10)+SUM(UE_REP_CQI_LEVEL_11)+
                                                        SUM(UE_REP_CQI_LEVEL_12)+SUM(UE_REP_CQI_LEVEL_13)+
                                                        SUM(UE_REP_CQI_LEVEL_14)+SUM(UE_REP_CQI_LEVEL_15)
                                                ), 0, 0,
                                                (
                                                        SUM(1*UE_REP_CQI_LEVEL_01)+
                                                        SUM(2*UE_REP_CQI_LEVEL_02)+
                                                        SUM(3*UE_REP_CQI_LEVEL_03)+
                                                        SUM(4*UE_REP_CQI_LEVEL_04)+
                                                        SUM(5*UE_REP_CQI_LEVEL_05)+
                                                        SUM(6*UE_REP_CQI_LEVEL_06)+
                                                        SUM(7*UE_REP_CQI_LEVEL_07)+
                                                        SUM(8*UE_REP_CQI_LEVEL_08)+
                                                        SUM(9*UE_REP_CQI_LEVEL_09)+
                                                        SUM(10*UE_REP_CQI_LEVEL_10)+
                                                        SUM(11*UE_REP_CQI_LEVEL_11)+
                                                        SUM(12*UE_REP_CQI_LEVEL_12)+
                                                        SUM(13*UE_REP_CQI_LEVEL_13)+
                                                        SUM(14*UE_REP_CQI_LEVEL_14)+
                                                        SUM(15*UE_REP_CQI_LEVEL_15)
                                                )  /
                                                (
                                                        SUM(UE_REP_CQI_LEVEL_00)+SUM(UE_REP_CQI_LEVEL_01)+
                                                        SUM(UE_REP_CQI_LEVEL_02)+SUM(UE_REP_CQI_LEVEL_03)+
                                                        SUM(UE_REP_CQI_LEVEL_04)+SUM(UE_REP_CQI_LEVEL_05)+
                                                        SUM(UE_REP_CQI_LEVEL_06)+SUM(UE_REP_CQI_LEVEL_07)+
                                                        SUM(UE_REP_CQI_LEVEL_08)+SUM(UE_REP_CQI_LEVEL_09)+
                                                        SUM(UE_REP_CQI_LEVEL_10)+SUM(UE_REP_CQI_LEVEL_11)+
                                                        SUM(UE_REP_CQI_LEVEL_12)+SUM(UE_REP_CQI_LEVEL_13)+
                                                        SUM(UE_REP_CQI_LEVEL_14)+SUM(UE_REP_CQI_LEVEL_15)
                                                )
                                        )

                ),2
        ) as LTE_5427A,

        SUM(UE_REP_CQI_LEVEL_00) AS UE_REP_CQI_LEVEL_00,
        SUM(UE_REP_CQI_LEVEL_01) as UE_REP_CQI_LEVEL_01,
        SUM(UE_REP_CQI_LEVEL_02) AS UE_REP_CQI_LEVEL_02,
        SUM(UE_REP_CQI_LEVEL_03) AS UE_REP_CQI_LEVEL_03,
        SUM(UE_REP_CQI_LEVEL_04) AS UE_REP_CQI_LEVEL_04,
        SUM(UE_REP_CQI_LEVEL_05) AS UE_REP_CQI_LEVEL_05,
        SUM(UE_REP_CQI_LEVEL_06) AS UE_REP_CQI_LEVEL_06,
        SUM(UE_REP_CQI_LEVEL_07) AS UE_REP_CQI_LEVEL_07,
        SUM(UE_REP_CQI_LEVEL_08) AS UE_REP_CQI_LEVEL_08,
        SUM(UE_REP_CQI_LEVEL_09) AS UE_REP_CQI_LEVEL_09,
        SUM(UE_REP_CQI_LEVEL_10) AS UE_REP_CQI_LEVEL_10,
        SUM(UE_REP_CQI_LEVEL_11) AS UE_REP_CQI_LEVEL_11,
        SUM(UE_REP_CQI_LEVEL_12) AS UE_REP_CQI_LEVEL_12,
        SUM(UE_REP_CQI_LEVEL_13) AS UE_REP_CQI_LEVEL_13,
        SUM(UE_REP_CQI_LEVEL_14) AS UE_REP_CQI_LEVEL_14,
        SUM(UE_REP_CQI_LEVEL_15) AS  UE_REP_CQI_LEVEL_15,
        ----------------- END LTE_5427A
        (-120*SUM(RSSI_PUCCH_LEVEL_01)
        -119*SUM(RSSI_PUCCH_LEVEL_02)
        -117*SUM(RSSI_PUCCH_LEVEL_03)
        -115*SUM(RSSI_PUCCH_LEVEL_04)
        -113*SUM(RSSI_PUCCH_LEVEL_05)
        -111*SUM(RSSI_PUCCH_LEVEL_06)
        -109*SUM(RSSI_PUCCH_LEVEL_07)
        -107*SUM(RSSI_PUCCH_LEVEL_08)
        -105*SUM(RSSI_PUCCH_LEVEL_09)
        -103*SUM(RSSI_PUCCH_LEVEL_10)
        -101*SUM(RSSI_PUCCH_LEVEL_11)
        -99*SUM(RSSI_PUCCH_LEVEL_12)
        -97*SUM(RSSI_PUCCH_LEVEL_13)
        -95*SUM(RSSI_PUCCH_LEVEL_14)
        -93*SUM(RSSI_PUCCH_LEVEL_15)
        -91*SUM(RSSI_PUCCH_LEVEL_16)
        -89*SUM(RSSI_PUCCH_LEVEL_17)
        -87*SUM(RSSI_PUCCH_LEVEL_18)
        -85*SUM(RSSI_PUCCH_LEVEL_19)
        -83*SUM(RSSI_PUCCH_LEVEL_20)
        -81*SUM(RSSI_PUCCH_LEVEL_21)
        -80*SUM(RSSI_PUCCH_LEVEL_22)) AS LTE_5441B_NUM,
        (SUM(RSSI_PUCCH_LEVEL_01)+
        SUM(RSSI_PUCCH_LEVEL_02)+
        SUM(RSSI_PUCCH_LEVEL_03)+
        SUM(RSSI_PUCCH_LEVEL_04)+
        SUM(RSSI_PUCCH_LEVEL_05)+
        SUM(RSSI_PUCCH_LEVEL_06)+
        SUM(RSSI_PUCCH_LEVEL_07)+
        SUM(RSSI_PUCCH_LEVEL_08)+
        SUM(RSSI_PUCCH_LEVEL_09)+
        SUM(RSSI_PUCCH_LEVEL_10)+
        SUM(RSSI_PUCCH_LEVEL_11)+
        SUM(RSSI_PUCCH_LEVEL_12)+
        SUM(RSSI_PUCCH_LEVEL_13)+
        SUM(RSSI_PUCCH_LEVEL_14)+
        SUM(RSSI_PUCCH_LEVEL_15)+
        SUM(RSSI_PUCCH_LEVEL_16)+
        SUM(RSSI_PUCCH_LEVEL_17)+
        SUM(RSSI_PUCCH_LEVEL_18)+
        SUM(RSSI_PUCCH_LEVEL_19)+
        SUM(RSSI_PUCCH_LEVEL_20)+
        SUM(RSSI_PUCCH_LEVEL_21)+
        SUM(RSSI_PUCCH_LEVEL_22)) AS LTE_5441B_DEN,
        ROUND (
                DECODE
                (
                        (
                                SUM(RSSI_PUCCH_LEVEL_01)+
                                SUM(RSSI_PUCCH_LEVEL_02)+
                                SUM(RSSI_PUCCH_LEVEL_03)+
                                SUM(RSSI_PUCCH_LEVEL_04)+
                                SUM(RSSI_PUCCH_LEVEL_05)+
                                SUM(RSSI_PUCCH_LEVEL_06)+
                                SUM(RSSI_PUCCH_LEVEL_07)+
                                SUM(RSSI_PUCCH_LEVEL_08)+
                                SUM(RSSI_PUCCH_LEVEL_09)+
                                SUM(RSSI_PUCCH_LEVEL_10)+
                                SUM(RSSI_PUCCH_LEVEL_11)+
                                SUM(RSSI_PUCCH_LEVEL_12)+
                                SUM(RSSI_PUCCH_LEVEL_13)+
                                SUM(RSSI_PUCCH_LEVEL_14)+
                                SUM(RSSI_PUCCH_LEVEL_15)+
                                SUM(RSSI_PUCCH_LEVEL_16)+
                                SUM(RSSI_PUCCH_LEVEL_17)+
                                SUM(RSSI_PUCCH_LEVEL_18)+
                                SUM(RSSI_PUCCH_LEVEL_19)+
                                SUM(RSSI_PUCCH_LEVEL_20)+
                                SUM(RSSI_PUCCH_LEVEL_21)+
                                SUM(RSSI_PUCCH_LEVEL_22)
                        ), 0, 0,
                        (
                                -120*SUM(RSSI_PUCCH_LEVEL_01)
                                -119*SUM(RSSI_PUCCH_LEVEL_02)
                                -117*SUM(RSSI_PUCCH_LEVEL_03)
                                -115*SUM(RSSI_PUCCH_LEVEL_04)
                                -113*SUM(RSSI_PUCCH_LEVEL_05)
                                -111*SUM(RSSI_PUCCH_LEVEL_06)
                                -109*SUM(RSSI_PUCCH_LEVEL_07)
                                -107*SUM(RSSI_PUCCH_LEVEL_08)
                                -105*SUM(RSSI_PUCCH_LEVEL_09)
                                -103*SUM(RSSI_PUCCH_LEVEL_10)
                                -101*SUM(RSSI_PUCCH_LEVEL_11)
                                -99*SUM(RSSI_PUCCH_LEVEL_12)
                                -97*SUM(RSSI_PUCCH_LEVEL_13)
                                -95*SUM(RSSI_PUCCH_LEVEL_14)
                                -93*SUM(RSSI_PUCCH_LEVEL_15)
                                -91*SUM(RSSI_PUCCH_LEVEL_16)
                                -89*SUM(RSSI_PUCCH_LEVEL_17)
                                -87*SUM(RSSI_PUCCH_LEVEL_18)
                                -85*SUM(RSSI_PUCCH_LEVEL_19)
                                -83*SUM(RSSI_PUCCH_LEVEL_20)
                                -81*SUM(RSSI_PUCCH_LEVEL_21)
                                -80*SUM(RSSI_PUCCH_LEVEL_22)
                        ) /
                        (
                                SUM(RSSI_PUCCH_LEVEL_01)+
                                SUM(RSSI_PUCCH_LEVEL_02)+
                                SUM(RSSI_PUCCH_LEVEL_03)+
                                SUM(RSSI_PUCCH_LEVEL_04)+
                                SUM(RSSI_PUCCH_LEVEL_05)+
                                SUM(RSSI_PUCCH_LEVEL_06)+
                                SUM(RSSI_PUCCH_LEVEL_07)+
                                SUM(RSSI_PUCCH_LEVEL_08)+
                                SUM(RSSI_PUCCH_LEVEL_09)+
                                SUM(RSSI_PUCCH_LEVEL_10)+
                                SUM(RSSI_PUCCH_LEVEL_11)+
                                SUM(RSSI_PUCCH_LEVEL_12)+
                                SUM(RSSI_PUCCH_LEVEL_13)+
                                SUM(RSSI_PUCCH_LEVEL_14)+
                                SUM(RSSI_PUCCH_LEVEL_15)+
                                SUM(RSSI_PUCCH_LEVEL_16)+
                                SUM(RSSI_PUCCH_LEVEL_17)+
                                SUM(RSSI_PUCCH_LEVEL_18)+
                                SUM(RSSI_PUCCH_LEVEL_19)+
                                SUM(RSSI_PUCCH_LEVEL_20)+
                                SUM(RSSI_PUCCH_LEVEL_21)+
                                SUM(RSSI_PUCCH_LEVEL_22)
                        )
                ) ,2
        ) AS LTE_5441B,
        SUM(RSSI_PUCCH_LEVEL_01) AS RSSI_PUCCH_LEVEL_01,
        SUM(RSSI_PUCCH_LEVEL_02) AS RSSI_PUCCH_LEVEL_02,
        SUM(RSSI_PUCCH_LEVEL_03) AS RSSI_PUCCH_LEVEL_03,
        SUM(RSSI_PUCCH_LEVEL_04) AS RSSI_PUCCH_LEVEL_04,
        SUM(RSSI_PUCCH_LEVEL_05) AS RSSI_PUCCH_LEVEL_05,
        SUM(RSSI_PUCCH_LEVEL_06) AS RSSI_PUCCH_LEVEL_06,
        SUM(RSSI_PUCCH_LEVEL_07) AS RSSI_PUCCH_LEVEL_07,
        SUM(RSSI_PUCCH_LEVEL_08) AS RSSI_PUCCH_LEVEL_08,
        SUM(RSSI_PUCCH_LEVEL_09) AS RSSI_PUCCH_LEVEL_09,
        SUM(RSSI_PUCCH_LEVEL_10) AS RSSI_PUCCH_LEVEL_10,
        SUM(RSSI_PUCCH_LEVEL_11) AS RSSI_PUCCH_LEVEL_11,
        SUM(RSSI_PUCCH_LEVEL_12) AS RSSI_PUCCH_LEVEL_12,
        SUM(RSSI_PUCCH_LEVEL_13) AS RSSI_PUCCH_LEVEL_13,
        SUM(RSSI_PUCCH_LEVEL_14) AS RSSI_PUCCH_LEVEL_14,
        SUM(RSSI_PUCCH_LEVEL_15) AS RSSI_PUCCH_LEVEL_15,
        SUM(RSSI_PUCCH_LEVEL_16) AS RSSI_PUCCH_LEVEL_16,
        SUM(RSSI_PUCCH_LEVEL_17) AS RSSI_PUCCH_LEVEL_17,
        SUM(RSSI_PUCCH_LEVEL_18) AS RSSI_PUCCH_LEVEL_18,
        SUM(RSSI_PUCCH_LEVEL_19) AS RSSI_PUCCH_LEVEL_19,
        SUM(RSSI_PUCCH_LEVEL_20) AS RSSI_PUCCH_LEVEL_20,
        SUM(RSSI_PUCCH_LEVEL_21) AS RSSI_PUCCH_LEVEL_21,
        SUM(RSSI_PUCCH_LEVEL_22) AS RSSI_PUCCH_LEVEL_22,
        ----------------- END LTE_5441B
        (-120*SUM(RSSI_PUSCH_LEVEL_01)
        -119*SUM(RSSI_PUSCH_LEVEL_02)
        -117*SUM(RSSI_PUSCH_LEVEL_03)
        -115*SUM(RSSI_PUSCH_LEVEL_04)
        -113*SUM(RSSI_PUSCH_LEVEL_05)
        -111*SUM(RSSI_PUSCH_LEVEL_06)
        -109*SUM(RSSI_PUSCH_LEVEL_07)
        -107*SUM(RSSI_PUSCH_LEVEL_08)
        -105*SUM(RSSI_PUSCH_LEVEL_09)
        -103*SUM(RSSI_PUSCH_LEVEL_10)
        -101*SUM(RSSI_PUSCH_LEVEL_11)
        -99*SUM(RSSI_PUSCH_LEVEL_12)
        -97*SUM(RSSI_PUSCH_LEVEL_13)
        -95*SUM(RSSI_PUSCH_LEVEL_14)
        -93*SUM(RSSI_PUSCH_LEVEL_15)
        -91*SUM(RSSI_PUSCH_LEVEL_16)
        -89*SUM(RSSI_PUSCH_LEVEL_17)
        -87*SUM(RSSI_PUSCH_LEVEL_18)
        -85*SUM(RSSI_PUSCH_LEVEL_19)
        -83*SUM(RSSI_PUSCH_LEVEL_20)
        -81*SUM(RSSI_PUSCH_LEVEL_21)
        -80*SUM(RSSI_PUSCH_LEVEL_22)) AS LTE_5444B_NUM,
        (SUM(RSSI_PUSCH_LEVEL_01)+
        SUM(RSSI_PUSCH_LEVEL_02)+
        SUM(RSSI_PUSCH_LEVEL_03)+
        SUM(RSSI_PUSCH_LEVEL_04)+
        SUM(RSSI_PUSCH_LEVEL_05)+
        SUM(RSSI_PUSCH_LEVEL_06)+
        SUM(RSSI_PUSCH_LEVEL_07)+
        SUM(RSSI_PUSCH_LEVEL_08)+
        SUM(RSSI_PUSCH_LEVEL_09)+
        SUM(RSSI_PUSCH_LEVEL_10)+
        SUM(RSSI_PUSCH_LEVEL_11)+
        SUM(RSSI_PUSCH_LEVEL_12)+
        SUM(RSSI_PUSCH_LEVEL_13)+
        SUM(RSSI_PUSCH_LEVEL_14)+
        SUM(RSSI_PUSCH_LEVEL_15)+
        SUM(RSSI_PUSCH_LEVEL_16)+
        SUM(RSSI_PUSCH_LEVEL_17)+
        SUM(RSSI_PUSCH_LEVEL_18)+
        SUM(RSSI_PUSCH_LEVEL_19)+
        SUM(RSSI_PUSCH_LEVEL_20)+
        SUM(RSSI_PUSCH_LEVEL_21)+
        SUM(RSSI_PUSCH_LEVEL_22)) AS LTE_5444B_DEN,
        ROUND (
                DECODE
                        (
                                (
                                        SUM(RSSI_PUSCH_LEVEL_01)+
                                        SUM(RSSI_PUSCH_LEVEL_02)+
                                        SUM(RSSI_PUSCH_LEVEL_03)+
                                        SUM(RSSI_PUSCH_LEVEL_04)+
                                        SUM(RSSI_PUSCH_LEVEL_05)+
                                        SUM(RSSI_PUSCH_LEVEL_06)+
                                        SUM(RSSI_PUSCH_LEVEL_07)+
                                        SUM(RSSI_PUSCH_LEVEL_08)+
                                        SUM(RSSI_PUSCH_LEVEL_09)+
                                        SUM(RSSI_PUSCH_LEVEL_10)+
                                        SUM(RSSI_PUSCH_LEVEL_11)+
                                        SUM(RSSI_PUSCH_LEVEL_12)+
                                        SUM(RSSI_PUSCH_LEVEL_13)+
                                        SUM(RSSI_PUSCH_LEVEL_14)+
                                        SUM(RSSI_PUSCH_LEVEL_15)+
                                        SUM(RSSI_PUSCH_LEVEL_16)+
                                        SUM(RSSI_PUSCH_LEVEL_17)+
                                        SUM(RSSI_PUSCH_LEVEL_18)+
                                        SUM(RSSI_PUSCH_LEVEL_19)+
                                        SUM(RSSI_PUSCH_LEVEL_20)+
                                        SUM(RSSI_PUSCH_LEVEL_21)+
                                        SUM(RSSI_PUSCH_LEVEL_22)
                                ), 0, 0,
                                (
                                        -120*SUM(RSSI_PUSCH_LEVEL_01)
                                        -119*SUM(RSSI_PUSCH_LEVEL_02)
                                        -117*SUM(RSSI_PUSCH_LEVEL_03)
                                        -115*SUM(RSSI_PUSCH_LEVEL_04)
                                        -113*SUM(RSSI_PUSCH_LEVEL_05)
                                        -111*SUM(RSSI_PUSCH_LEVEL_06)
                                        -109*SUM(RSSI_PUSCH_LEVEL_07)
                                        -107*SUM(RSSI_PUSCH_LEVEL_08)
                                        -105*SUM(RSSI_PUSCH_LEVEL_09)
                                        -103*SUM(RSSI_PUSCH_LEVEL_10)
                                        -101*SUM(RSSI_PUSCH_LEVEL_11)
                                        -99*SUM(RSSI_PUSCH_LEVEL_12)
                                        -97*SUM(RSSI_PUSCH_LEVEL_13)
                                        -95*SUM(RSSI_PUSCH_LEVEL_14)
                                        -93*SUM(RSSI_PUSCH_LEVEL_15)
                                        -91*SUM(RSSI_PUSCH_LEVEL_16)
                                        -89*SUM(RSSI_PUSCH_LEVEL_17)
                                        -87*SUM(RSSI_PUSCH_LEVEL_18)
                                        -85*SUM(RSSI_PUSCH_LEVEL_19)
                                        -83*SUM(RSSI_PUSCH_LEVEL_20)
                                        -81*SUM(RSSI_PUSCH_LEVEL_21)
                                        -80*SUM(RSSI_PUSCH_LEVEL_22)
                                ) /
                                (
                                        SUM(RSSI_PUSCH_LEVEL_01)+
                                        SUM(RSSI_PUSCH_LEVEL_02)+
                                        SUM(RSSI_PUSCH_LEVEL_03)+
                                        SUM(RSSI_PUSCH_LEVEL_04)+
                                        SUM(RSSI_PUSCH_LEVEL_05)+
                                        SUM(RSSI_PUSCH_LEVEL_06)+
                                        SUM(RSSI_PUSCH_LEVEL_07)+
                                        SUM(RSSI_PUSCH_LEVEL_08)+
                                        SUM(RSSI_PUSCH_LEVEL_09)+
                                        SUM(RSSI_PUSCH_LEVEL_10)+
                                        SUM(RSSI_PUSCH_LEVEL_11)+
                                        SUM(RSSI_PUSCH_LEVEL_12)+
                                        SUM(RSSI_PUSCH_LEVEL_13)+
                                        SUM(RSSI_PUSCH_LEVEL_14)+
                                        SUM(RSSI_PUSCH_LEVEL_15)+
                                        SUM(RSSI_PUSCH_LEVEL_16)+
                                        SUM(RSSI_PUSCH_LEVEL_17)+
                                        SUM(RSSI_PUSCH_LEVEL_18)+
                                        SUM(RSSI_PUSCH_LEVEL_19)+
                                        SUM(RSSI_PUSCH_LEVEL_20)+
                                        SUM(RSSI_PUSCH_LEVEL_21)+
                                        SUM(RSSI_PUSCH_LEVEL_22)
                                )
                        ) ,2
        ) AS LTE_5444B,
        SUM(RSSI_PUSCH_LEVEL_01) AS RSSI_PUSCH_LEVEL_01,
        SUM(RSSI_PUSCH_LEVEL_02) AS RSSI_PUSCH_LEVEL_02,
        SUM(RSSI_PUSCH_LEVEL_03) AS RSSI_PUSCH_LEVEL_03,
        SUM(RSSI_PUSCH_LEVEL_04) AS RSSI_PUSCH_LEVEL_04,
        SUM(RSSI_PUSCH_LEVEL_05) AS RSSI_PUSCH_LEVEL_05,
        SUM(RSSI_PUSCH_LEVEL_06) AS RSSI_PUSCH_LEVEL_06,
        SUM(RSSI_PUSCH_LEVEL_07) AS RSSI_PUSCH_LEVEL_07,
        SUM(RSSI_PUSCH_LEVEL_08) AS RSSI_PUSCH_LEVEL_08,
        SUM(RSSI_PUSCH_LEVEL_09) AS RSSI_PUSCH_LEVEL_09,
        SUM(RSSI_PUSCH_LEVEL_10) AS RSSI_PUSCH_LEVEL_10,
        SUM(RSSI_PUSCH_LEVEL_11) AS RSSI_PUSCH_LEVEL_11,
        SUM(RSSI_PUSCH_LEVEL_12) AS RSSI_PUSCH_LEVEL_12,
        SUM(RSSI_PUSCH_LEVEL_13) AS RSSI_PUSCH_LEVEL_13,
        SUM(RSSI_PUSCH_LEVEL_14) AS RSSI_PUSCH_LEVEL_14,
        SUM(RSSI_PUSCH_LEVEL_15) AS RSSI_PUSCH_LEVEL_15,
        SUM(RSSI_PUSCH_LEVEL_16) AS RSSI_PUSCH_LEVEL_16,
        SUM(RSSI_PUSCH_LEVEL_17) AS RSSI_PUSCH_LEVEL_17,
        SUM(RSSI_PUSCH_LEVEL_18) AS RSSI_PUSCH_LEVEL_18,
        SUM(RSSI_PUSCH_LEVEL_19) AS RSSI_PUSCH_LEVEL_19,
        SUM(RSSI_PUSCH_LEVEL_20) AS RSSI_PUSCH_LEVEL_20,
        SUM(RSSI_PUSCH_LEVEL_21) AS RSSI_PUSCH_LEVEL_21,
        SUM(RSSI_PUSCH_LEVEL_22) AS RSSI_PUSCH_LEVEL_22,
        ----------------- END LTE_5444B
        (-10*SUM(SINR_PUCCH_LEVEL_1)
        -9*SUM(SINR_PUCCH_LEVEL_2)
        -7*SUM(SINR_PUCCH_LEVEL_3)
        -5*SUM(SINR_PUCCH_LEVEL_4)
        -3*SUM(SINR_PUCCH_LEVEL_5)
        -1*SUM(SINR_PUCCH_LEVEL_6)
        +1*SUM(SINR_PUCCH_LEVEL_7)
        +3*SUM(SINR_PUCCH_LEVEL_8)
        +5*SUM(SINR_PUCCH_LEVEL_9)
        +7*SUM(SINR_PUCCH_LEVEL_10)
        +9*SUM(SINR_PUCCH_LEVEL_11)
        +11*SUM(SINR_PUCCH_LEVEL_12)
        +13*SUM(SINR_PUCCH_LEVEL_13)
        +15*SUM(SINR_PUCCH_LEVEL_14)
        +17*SUM(SINR_PUCCH_LEVEL_15)
        +19*SUM(SINR_PUCCH_LEVEL_16)
        +21*SUM(SINR_PUCCH_LEVEL_17)
        +23*SUM(SINR_PUCCH_LEVEL_18)
        +25*SUM(SINR_PUCCH_LEVEL_19)
        +27*SUM(SINR_PUCCH_LEVEL_20)
        +29*SUM(SINR_PUCCH_LEVEL_21)
        +30*SUM(SINR_PUCCH_LEVEL_22)) AS LTE_5541B_NUM,
        (SUM(SINR_PUCCH_LEVEL_1)+
        SUM(SINR_PUCCH_LEVEL_2)+
        SUM(SINR_PUCCH_LEVEL_3)+
        SUM(SINR_PUCCH_LEVEL_4)+
        SUM(SINR_PUCCH_LEVEL_5)+
        SUM(SINR_PUCCH_LEVEL_6)+
        SUM(SINR_PUCCH_LEVEL_7)+
        SUM(SINR_PUCCH_LEVEL_8)+
        SUM(SINR_PUCCH_LEVEL_9)+
        SUM(SINR_PUCCH_LEVEL_10)+
        SUM(SINR_PUCCH_LEVEL_11)+
        SUM(SINR_PUCCH_LEVEL_12)+
        SUM(SINR_PUCCH_LEVEL_13)+
        SUM(SINR_PUCCH_LEVEL_14)+
        SUM(SINR_PUCCH_LEVEL_15)+
        SUM(SINR_PUCCH_LEVEL_16)+
        SUM(SINR_PUCCH_LEVEL_17)+
        SUM(SINR_PUCCH_LEVEL_18)+
        SUM(SINR_PUCCH_LEVEL_19)+
        SUM(SINR_PUCCH_LEVEL_20)+
        SUM(SINR_PUCCH_LEVEL_21)+
        SUM(SINR_PUCCH_LEVEL_22)) AS LTE_5541B_DEN,
        ROUND (
                DECODE (
                                (
                                SUM(SINR_PUCCH_LEVEL_1)+
                                SUM(SINR_PUCCH_LEVEL_2)+
                                SUM(SINR_PUCCH_LEVEL_3)+
                                SUM(SINR_PUCCH_LEVEL_4)+
                                SUM(SINR_PUCCH_LEVEL_5)+
                                SUM(SINR_PUCCH_LEVEL_6)+
                                SUM(SINR_PUCCH_LEVEL_7)+
                                SUM(SINR_PUCCH_LEVEL_8)+
                                SUM(SINR_PUCCH_LEVEL_9)+
                                SUM(SINR_PUCCH_LEVEL_10)+
                                SUM(SINR_PUCCH_LEVEL_11)+
                                SUM(SINR_PUCCH_LEVEL_12)+
                                SUM(SINR_PUCCH_LEVEL_13)+
                                SUM(SINR_PUCCH_LEVEL_14)+
                                SUM(SINR_PUCCH_LEVEL_15)+
                                SUM(SINR_PUCCH_LEVEL_16)+
                                SUM(SINR_PUCCH_LEVEL_17)+
                                SUM(SINR_PUCCH_LEVEL_18)+
                                SUM(SINR_PUCCH_LEVEL_19)+
                                SUM(SINR_PUCCH_LEVEL_20)+
                                SUM(SINR_PUCCH_LEVEL_21)+
                                SUM(SINR_PUCCH_LEVEL_22)
                                ), 0, 0,
                                (
                                        -10*SUM(SINR_PUCCH_LEVEL_1)
                                        -9*SUM(SINR_PUCCH_LEVEL_2)
                                        -7*SUM(SINR_PUCCH_LEVEL_3)
                                        -5*SUM(SINR_PUCCH_LEVEL_4)
                                        -3*SUM(SINR_PUCCH_LEVEL_5)
                                        -1*SUM(SINR_PUCCH_LEVEL_6)
                                        +1*SUM(SINR_PUCCH_LEVEL_7)
                                        +3*SUM(SINR_PUCCH_LEVEL_8)
                                        +5*SUM(SINR_PUCCH_LEVEL_9)
                                        +7*SUM(SINR_PUCCH_LEVEL_10)
                                        +9*SUM(SINR_PUCCH_LEVEL_11)
                                        +11*SUM(SINR_PUCCH_LEVEL_12)
                                        +13*SUM(SINR_PUCCH_LEVEL_13)
                                        +15*SUM(SINR_PUCCH_LEVEL_14)
                                        +17*SUM(SINR_PUCCH_LEVEL_15)
                                        +19*SUM(SINR_PUCCH_LEVEL_16)
                                        +21*SUM(SINR_PUCCH_LEVEL_17)
                                        +23*SUM(SINR_PUCCH_LEVEL_18)
                                        +25*SUM(SINR_PUCCH_LEVEL_19)
                                        +27*SUM(SINR_PUCCH_LEVEL_20)
                                        +29*SUM(SINR_PUCCH_LEVEL_21)
                                        +30*SUM(SINR_PUCCH_LEVEL_22)
                                ) /
                                (
                                        SUM(SINR_PUCCH_LEVEL_1)+
                                        SUM(SINR_PUCCH_LEVEL_2)+
                                        SUM(SINR_PUCCH_LEVEL_3)+
                                        SUM(SINR_PUCCH_LEVEL_4)+
                                        SUM(SINR_PUCCH_LEVEL_5)+
                                        SUM(SINR_PUCCH_LEVEL_6)+
                                        SUM(SINR_PUCCH_LEVEL_7)+
                                        SUM(SINR_PUCCH_LEVEL_8)+
                                        SUM(SINR_PUCCH_LEVEL_9)+
                                        SUM(SINR_PUCCH_LEVEL_10)+
                                        SUM(SINR_PUCCH_LEVEL_11)+
                                        SUM(SINR_PUCCH_LEVEL_12)+
                                        SUM(SINR_PUCCH_LEVEL_13)+
                                        SUM(SINR_PUCCH_LEVEL_14)+
                                        SUM(SINR_PUCCH_LEVEL_15)+
                                        SUM(SINR_PUCCH_LEVEL_16)+
                                        SUM(SINR_PUCCH_LEVEL_17)+
                                        SUM(SINR_PUCCH_LEVEL_18)+
                                        SUM(SINR_PUCCH_LEVEL_19)+
                                        SUM(SINR_PUCCH_LEVEL_20)+
                                        SUM(SINR_PUCCH_LEVEL_21)+
                                        SUM(SINR_PUCCH_LEVEL_22)
                                )

                        ) ,2
                ) AS LTE_5541B,
        SUM(SINR_PUCCH_LEVEL_1) AS SINR_PUCCH_LEVEL_1,
        SUM(SINR_PUCCH_LEVEL_2) AS SINR_PUCCH_LEVEL_2,
        SUM(SINR_PUCCH_LEVEL_3) AS SINR_PUCCH_LEVEL_3,
        SUM(SINR_PUCCH_LEVEL_4) AS SINR_PUCCH_LEVEL_4,
        SUM(SINR_PUCCH_LEVEL_5) AS SINR_PUCCH_LEVEL_5,
        SUM(SINR_PUCCH_LEVEL_6) AS SINR_PUCCH_LEVEL_6,
        SUM(SINR_PUCCH_LEVEL_7) AS SINR_PUCCH_LEVEL_7,
        SUM(SINR_PUCCH_LEVEL_8) AS SINR_PUCCH_LEVEL_8,
        SUM(SINR_PUCCH_LEVEL_9) AS SINR_PUCCH_LEVEL_9,
        SUM(SINR_PUCCH_LEVEL_10) AS SINR_PUCCH_LEVEL_10,
        SUM(SINR_PUCCH_LEVEL_11) AS SINR_PUCCH_LEVEL_11,
        SUM(SINR_PUCCH_LEVEL_12) AS SINR_PUCCH_LEVEL_12,
        SUM(SINR_PUCCH_LEVEL_13) AS SINR_PUCCH_LEVEL_13,
        SUM(SINR_PUCCH_LEVEL_14) AS SINR_PUCCH_LEVEL_14,
        SUM(SINR_PUCCH_LEVEL_15) AS SINR_PUCCH_LEVEL_15,
        SUM(SINR_PUCCH_LEVEL_16) AS SINR_PUCCH_LEVEL_16,
        SUM(SINR_PUCCH_LEVEL_17) AS SINR_PUCCH_LEVEL_17,
        SUM(SINR_PUCCH_LEVEL_18) AS SINR_PUCCH_LEVEL_18,
        SUM(SINR_PUCCH_LEVEL_19) AS SINR_PUCCH_LEVEL_19,
        SUM(SINR_PUCCH_LEVEL_20) AS SINR_PUCCH_LEVEL_20,
        SUM(SINR_PUCCH_LEVEL_21) AS SINR_PUCCH_LEVEL_21,
        SUM(SINR_PUCCH_LEVEL_22) AS SINR_PUCCH_LEVEL_22,
        ----------------- END LTE_5541B
        (-10*SUM(SINR_PUSCH_LEVEL_1)
        -9*SUM(SINR_PUSCH_LEVEL_2)
        -7*SUM(SINR_PUSCH_LEVEL_3)
        -5*SUM(SINR_PUSCH_LEVEL_4)
        -3*SUM(SINR_PUSCH_LEVEL_5)
        -1*SUM(SINR_PUSCH_LEVEL_6)
        +1*SUM(SINR_PUSCH_LEVEL_7)
        +3*SUM(SINR_PUSCH_LEVEL_8)
        +5*SUM(SINR_PUSCH_LEVEL_9)
        +7*SUM(SINR_PUSCH_LEVEL_10)
        +9*SUM(SINR_PUSCH_LEVEL_11)
        +11*SUM(SINR_PUSCH_LEVEL_12)
        +13*SUM(SINR_PUSCH_LEVEL_13)
        +15*SUM(SINR_PUSCH_LEVEL_14)
        +17*SUM(SINR_PUSCH_LEVEL_15)
        +19*SUM(SINR_PUSCH_LEVEL_16)
        +21*SUM(SINR_PUSCH_LEVEL_17)
        +23*SUM(SINR_PUSCH_LEVEL_18)
        +25*SUM(SINR_PUSCH_LEVEL_19)
        +27*SUM(SINR_PUSCH_LEVEL_20)
        +29*SUM(SINR_PUSCH_LEVEL_21)
        +30*SUM(SINR_PUSCH_LEVEL_22)) AS LTE_5544B_NUM,
        (SUM(SINR_PUSCH_LEVEL_1)+
        SUM(SINR_PUSCH_LEVEL_2)+
        SUM(SINR_PUSCH_LEVEL_3)+
        SUM(SINR_PUSCH_LEVEL_4)+
        SUM(SINR_PUSCH_LEVEL_5)+
        SUM(SINR_PUSCH_LEVEL_6)+
        SUM(SINR_PUSCH_LEVEL_7)+
        SUM(SINR_PUSCH_LEVEL_8)+
        SUM(SINR_PUSCH_LEVEL_9)+
        SUM(SINR_PUSCH_LEVEL_10)+
        SUM(SINR_PUSCH_LEVEL_11)+
        SUM(SINR_PUSCH_LEVEL_12)+
        SUM(SINR_PUSCH_LEVEL_13)+
        SUM(SINR_PUSCH_LEVEL_14)+
        SUM(SINR_PUSCH_LEVEL_15)+
        SUM(SINR_PUSCH_LEVEL_16)+
        SUM(SINR_PUSCH_LEVEL_17)+
        SUM(SINR_PUSCH_LEVEL_18)+
        SUM(SINR_PUSCH_LEVEL_19)+
        SUM(SINR_PUSCH_LEVEL_20)+
        SUM(SINR_PUSCH_LEVEL_21)+
        SUM(SINR_PUSCH_LEVEL_22)) AS LTE_5544B_DEN,
        ROUND ( DECODE(
                (SUM(SINR_PUSCH_LEVEL_1)+
                SUM(SINR_PUSCH_LEVEL_2)+
                SUM(SINR_PUSCH_LEVEL_3)+
                SUM(SINR_PUSCH_LEVEL_4)+
                SUM(SINR_PUSCH_LEVEL_5)+
                SUM(SINR_PUSCH_LEVEL_6)+
                SUM(SINR_PUSCH_LEVEL_7)+
                SUM(SINR_PUSCH_LEVEL_8)+
                SUM(SINR_PUSCH_LEVEL_9)+
                SUM(SINR_PUSCH_LEVEL_10)+
                SUM(SINR_PUSCH_LEVEL_11)+
                SUM(SINR_PUSCH_LEVEL_12)+
                SUM(SINR_PUSCH_LEVEL_13)+
                SUM(SINR_PUSCH_LEVEL_14)+
                SUM(SINR_PUSCH_LEVEL_15)+
                SUM(SINR_PUSCH_LEVEL_16)+
                SUM(SINR_PUSCH_LEVEL_17)+
                SUM(SINR_PUSCH_LEVEL_18)+
                SUM(SINR_PUSCH_LEVEL_19)+
                SUM(SINR_PUSCH_LEVEL_20)+
                SUM(SINR_PUSCH_LEVEL_21)+
                SUM(SINR_PUSCH_LEVEL_22)) , 0, 0,
                (-10*SUM(SINR_PUSCH_LEVEL_1)
                -9*SUM(SINR_PUSCH_LEVEL_2)
                -7*SUM(SINR_PUSCH_LEVEL_3)
                -5*SUM(SINR_PUSCH_LEVEL_4)
                -3*SUM(SINR_PUSCH_LEVEL_5)
                -1*SUM(SINR_PUSCH_LEVEL_6)
                +1*SUM(SINR_PUSCH_LEVEL_7)
                +3*SUM(SINR_PUSCH_LEVEL_8)
                +5*SUM(SINR_PUSCH_LEVEL_9)
                +7*SUM(SINR_PUSCH_LEVEL_10)
                +9*SUM(SINR_PUSCH_LEVEL_11)
                +11*SUM(SINR_PUSCH_LEVEL_12)
                +13*SUM(SINR_PUSCH_LEVEL_13)
                +15*SUM(SINR_PUSCH_LEVEL_14)
                +17*SUM(SINR_PUSCH_LEVEL_15)
                +19*SUM(SINR_PUSCH_LEVEL_16)
                +21*SUM(SINR_PUSCH_LEVEL_17)
                +23*SUM(SINR_PUSCH_LEVEL_18)
                +25*SUM(SINR_PUSCH_LEVEL_19)
                +27*SUM(SINR_PUSCH_LEVEL_20)
                +29*SUM(SINR_PUSCH_LEVEL_21)
                +30*SUM(SINR_PUSCH_LEVEL_22)) /
                (SUM(SINR_PUSCH_LEVEL_1)+
                SUM(SINR_PUSCH_LEVEL_2)+
                SUM(SINR_PUSCH_LEVEL_3)+
                SUM(SINR_PUSCH_LEVEL_4)+
                SUM(SINR_PUSCH_LEVEL_5)+
                SUM(SINR_PUSCH_LEVEL_6)+
                SUM(SINR_PUSCH_LEVEL_7)+
                SUM(SINR_PUSCH_LEVEL_8)+
                SUM(SINR_PUSCH_LEVEL_9)+
                SUM(SINR_PUSCH_LEVEL_10)+
                SUM(SINR_PUSCH_LEVEL_11)+
                SUM(SINR_PUSCH_LEVEL_12)+
                SUM(SINR_PUSCH_LEVEL_13)+
                SUM(SINR_PUSCH_LEVEL_14)+
                SUM(SINR_PUSCH_LEVEL_15)+
                SUM(SINR_PUSCH_LEVEL_16)+
                SUM(SINR_PUSCH_LEVEL_17)+
                SUM(SINR_PUSCH_LEVEL_18)+
                SUM(SINR_PUSCH_LEVEL_19)+
                SUM(SINR_PUSCH_LEVEL_20)+
                SUM(SINR_PUSCH_LEVEL_21)+
                SUM(SINR_PUSCH_LEVEL_22)) ) ,2) AS LTE_5544B,
        --SUM(SINR_PUCCH_LEVEL_1) AS SINR_PUCCH_LEVEL_1,
        --SUM(SINR_PUCCH_LEVEL_2) AS SINR_PUCCH_LEVEL_2,
        --SUM(SINR_PUCCH_LEVEL_3) AS SINR_PUCCH_LEVEL_3,
        --SUM(SINR_PUCCH_LEVEL_4) AS SINR_PUCCH_LEVEL_4,
        --SUM(SINR_PUCCH_LEVEL_5) AS SINR_PUCCH_LEVEL_5,
        --SUM(SINR_PUCCH_LEVEL_6) AS SINR_PUCCH_LEVEL_6,
        --SUM(SINR_PUCCH_LEVEL_7) AS SINR_PUCCH_LEVEL_7,
        --SUM(SINR_PUCCH_LEVEL_8) AS SINR_PUCCH_LEVEL_8,
        --SUM(SINR_PUCCH_LEVEL_9) AS SINR_PUCCH_LEVEL_9,
        --SUM(SINR_PUCCH_LEVEL_10) AS SINR_PUCCH_LEVEL_10,
        --SUM(SINR_PUCCH_LEVEL_11) AS SINR_PUCCH_LEVEL_11,
        --SUM(SINR_PUCCH_LEVEL_12) AS SINR_PUCCH_LEVEL_12,
        --SUM(SINR_PUCCH_LEVEL_13) AS SINR_PUCCH_LEVEL_13,
        --SUM(SINR_PUCCH_LEVEL_14) AS SINR_PUCCH_LEVEL_14,
        --SUM(SINR_PUCCH_LEVEL_15) AS SINR_PUCCH_LEVEL_15,
        --SUM(SINR_PUCCH_LEVEL_16) AS SINR_PUCCH_LEVEL_16,
        --SUM(SINR_PUCCH_LEVEL_17) AS SINR_PUCCH_LEVEL_17,
        --SUM(SINR_PUCCH_LEVEL_18) AS SINR_PUCCH_LEVEL_18,
        --SUM(SINR_PUCCH_LEVEL_19) AS SINR_PUCCH_LEVEL_19,
        --SUM(SINR_PUCCH_LEVEL_20) AS SINR_PUCCH_LEVEL_20,
        --SUM(SINR_PUCCH_LEVEL_21) AS SINR_PUCCH_LEVEL_21,
        --SUM(SINR_PUCCH_LEVEL_22) AS SINR_PUCCH_LEVEL_22,
        ----------------- END LTE_5544B
        SUM(RACH_STP_COMPLETIONS) AS LTE_5569A_NUM,
        (SUM(RACH_STP_ATT_SMALL_MSG)+
        SUM(RACH_STP_ATT_LARGE_MSG)+
        SUM(RACH_STP_ATT_DEDICATED)) AS LTE_5569A_DEN,
        ROUND ( DECODE(
                (SUM(RACH_STP_ATT_SMALL_MSG)+
                SUM(RACH_STP_ATT_LARGE_MSG)+
                SUM(RACH_STP_ATT_DEDICATED)), 0, 0,
                SUM(RACH_STP_COMPLETIONS) /
                (SUM(RACH_STP_ATT_SMALL_MSG)+
                SUM(RACH_STP_ATT_LARGE_MSG)+
                SUM(RACH_STP_ATT_DEDICATED))) *100 ,2) AS LTE_5569A,
        SUM(RACH_STP_COMPLETIONS) AS RACH_STP_COMPLETIONS,
        SUM(RACH_STP_ATT_SMALL_MSG) AS RACH_STP_ATT_SMALL_MSG,
        SUM(RACH_STP_ATT_LARGE_MSG) AS RACH_STP_ATT_LARGE_MSG,
        SUM(RACH_STP_ATT_DEDICATED) AS RACH_STP_ATT_DEDICATED,
        ----------------- END LTE_5569A
        SUM(SAMPLES_CELL_AVAIL) AS LTE_5750A_NUM ,
        SUM(DENOM_CELL_AVAIL) AS LTE_5750A_DEN,
        ROUND ((DECODE (SUM(DENOM_CELL_AVAIL), 0 ,0, SUM(SAMPLES_CELL_AVAIL) / SUM(DENOM_CELL_AVAIL) ) ) * 100, 2) AS LTE_5750A,
        SUM(SAMPLES_CELL_AVAIL) AS SAMPLES_CELL_AVAIL,
        SUM(DENOM_CELL_AVAIL) AS DENOM_CELL_AVAIL,
        ----------------- END LTE_5750A
        SUM(SUM_ACTIVE_UE_DATA_DL) AS LTE_5800D_NUM,
        SUM(DENOM_ACTIVE_UE_DATA_DL) AS LTE_5800D_DEN,
        ROUND ( DECODE(SUM(DENOM_ACTIVE_UE_DATA_DL), 0, 0, SUM(SUM_ACTIVE_UE_DATA_DL) / SUM(DENOM_ACTIVE_UE_DATA_DL)) ,2) AS LTE_5800D,
        SUM(SUM_ACTIVE_UE_DATA_DL) AS SUM_ACTIVE_UE_DATA_DL,
        SUM(DENOM_ACTIVE_UE_DATA_DL) AS DENOM_ACTIVE_UE_DATA_DL,
        ----------------- END LTE_5800D
        SUM(SUM_ACTIVE_UE_DATA_UL) AS LTE_5801D_NUM,
        SUM(DENOM_ACTIVE_UE_DATA_UL) AS LTE_5801D_DEN,
        ROUND ( DECODE(SUM(DENOM_ACTIVE_UE_DATA_UL), 0, 0, SUM(SUM_ACTIVE_UE_DATA_UL) / SUM(DENOM_ACTIVE_UE_DATA_UL)) ,2) AS LTE_5801D,
        SUM(SUM_ACTIVE_UE_DATA_UL) AS SUM_ACTIVE_UE_DATA_UL,
        SUM(DENOM_ACTIVE_UE_DATA_UL) AS DENOM_ACTIVE_UE_DATA_UL,
        ----------------- END LTE_5801D
        MAX(DL_UE_DATA_BUFF_MAX) AS LTE_5802A,
        SUM(DL_UE_DATA_BUFF_MAX) AS DL_UE_DATA_BUFF_MAX,
        ----------------- END LTE_5802A
        MAX(UL_UE_DATA_BUFF_MAX) AS LTE_5803A,
        SUM(UL_UE_DATA_BUFF_MAX) AS UL_UE_DATA_BUFF_MAX,
        ----------------- END LTE_5803A
        SUM(SIGN_EST_F_RRCCOMPL_MISSING) AS  M8013C6,
        SUM(SIGN_EST_F_RRCCOMPL_ERROR) AS M8013C7,
        SUM(SIGN_CONN_ESTAB_FAIL_RRMRAC) AS M8013C8,
        SUM(SIGN_CONN_ESTAB_FAIL_RB_EMG) AS M8013C27,
        SUM(EPS_BEARER_SETUP_FAIL_RNL) AS M8006C2,
        SUM(EPS_BEARER_SETUP_FAIL_RESOUR) AS M8006C4,
        SUM(EPS_BEARER_SETUP_FAIL_TRPORT) AS M8006C3,
        SUM(EPS_BEARER_SETUP_FAIL_OTH) AS M8006C5,
        SUM(ENB_EPS_BEARER_REL_REQ_RNL) AS M8006C12,
        SUM(ENB_EPS_BEARER_REL_REQ_TNL) AS M8006C14,
        SUM(ENB_EPS_BEARER_REL_REQ_OTH) AS M8006C13
        ----------------- END Principales Counters
FROM NOKLTE_PS_LCELLD_MNC1_RAW@OSSRC2.WORLD T1
LEFT OUTER JOIN NOKLTE_PS_LCELLT_MNC1_RAW@OSSRC2.WORLD T2
ON T1.PERIOD_START_TIME = T2.PERIOD_START_TIME
AND T1.LNCEL_ID = T2.LNCEL_ID
LEFT OUTER JOIN NOKLTE_PS_LEPSB_MNC1_RAW@OSSRC2.WORLD T3
ON T2.PERIOD_START_TIME = T3.PERIOD_START_TIME
AND T2.LNCEL_ID = T3.LNCEL_ID
LEFT OUTER JOIN NOKLTE_PS_LRRC_MNC1_RAW@OSSRC2.WORLD T4
ON T3.PERIOD_START_TIME = T4.PERIOD_START_TIME
AND T3.LNCEL_ID = T4.LNCEL_ID
LEFT OUTER JOIN NOKLTE_PS_LUEST_MNC1_RAW@OSSRC2.WORLD T5
ON T4.PERIOD_START_TIME = T5.PERIOD_START_TIME
AND T4.LNCEL_ID = T5.LNCEL_ID
LEFT OUTER JOIN NOKLTE_PS_LPQDL_MNC1_RAW@OSSRC2.WORLD T6
ON T5.PERIOD_START_TIME = T6.PERIOD_START_TIME
AND T5.LNCEL_ID = T6.LNCEL_ID
LEFT OUTER JOIN NOKLTE_PS_LPQUL_MNC1_RAW@OSSRC2.WORLD T7
ON T6.PERIOD_START_TIME = T7.PERIOD_START_TIME
AND T6.LNCEL_ID = T7.LNCEL_ID
LEFT OUTER JOIN NOKLTE_PS_LCELAV_MNC1_RAW@OSSRC2.WORLD T8
ON T7.PERIOD_START_TIME = T8.PERIOD_START_TIME
AND T7.LNCEL_ID = T8.LNCEL_ID
LEFT OUTER JOIN UTP_COMMON_OBJECTS@OSSRC2       O1
ON T1.LNCEL_ID = O1.CO_GID
WHERE O1.CO_OC_ID = 3130
AND O1.CO_STATE = 0
GROUP BY TO_DATE( SUBSTR( T1.PERIOD_START_TIME, 0, 10), 'DD/MM/RRRR'), O1.CO_NAME, O1.CO_GID
;
