--------------------------------------------------------
--  Constraints for Table STATUS_PROCESS_ETL
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."STATUS_PROCESS_ETL" ADD CONSTRAINT "STATUS_PROCESS_ETL_PK" PRIMARY KEY ("FILENAME", "MEASUREMENT_TYPE", "DATE_IMPORT", "STATUS") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."STATUS_PROCESS_ETL" MODIFY ("DATE_IMPORT" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."STATUS_PROCESS_ETL" MODIFY ("STATUS" NOT NULL ENABLE);
