--------------------------------------------------------
--  Constraints for Table STATUS_PROCESS_ETL_TEST
--------------------------------------------------------

  ALTER TABLE "HARRIAGUE"."STATUS_PROCESS_ETL_TEST" ADD CONSTRAINT "STATUS_PROCESS_ETL_TEST_PK" PRIMARY KEY ("FILENAME", "MEASUREMENT_TYPE") ENABLE;
 
  ALTER TABLE "HARRIAGUE"."STATUS_PROCESS_ETL_TEST" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."STATUS_PROCESS_ETL_TEST" MODIFY ("DATE_IMPORT" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."STATUS_PROCESS_ETL_TEST" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "HARRIAGUE"."STATUS_PROCESS_ETL_TEST" MODIFY ("MEASUREMENT_TYPE" NOT NULL ENABLE);
